### ISSUE TITLE
Ensure Registration link is a valid URL

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#120]
This line https://github.com/BCcampus/eypd/blob/dev/plugins/events-manager/templates/event-single.php#L22 singles out 'Registration Link' and forces it to be hyperlinked without checking to see if a valid protocol (http/https) is set. 

Would like to put in a check to see that the link provided is a valid url to avoid creating links like `<a href="www.somedomain.com">www.somedomain.com</a>`

**Comment by bdolor** [comment]
This may have been addressed already, there is currently https://github.com/BCcampus/eypd/pull/500/commits/d6fb2ee9c3b02e9554d22545e427d3cf94558820

**Comment by kkilbey** [comment]
The Registration Link field seems to hyperlink any text that is entered into it, whether the text constitutes a valid URL or not. I created an event called Sign Language for ECEs (https://eypd.bccampus.ca/events/sign-language-for-eces/) and used it to test five different registration links.

**1. Entered link:** bccampus.ca (without https://)
After saving the event, this link displayed as https://eypd.bccampus.ca/events/sign-language-for-eces/bccampus.ca and led to an error page (see below) in Chrome, Firefox, Edge, and on mobile (iPhone 6S Safari).
![image](https://user-images.githubusercontent.com/44710357/49107679-3d493400-f23b-11e8-8610-ca6f7ef1a21d.png)

**2. Entered link:** 7789775357
Using a phone number as the registration link caused the site to behave a bit differently. After saving the event, this link displayed as https://eypd.bccampus.ca/events/sign-language-for-eces/7789775357/ and led to what looked like the same event page (as if I'd hit "refresh"). However, selecting the registration link again from this page changed the URL to https://eypd.bccampus.ca/events/sign-language-for-eces/7789775357/7789775357 and that link then led to the same error page as above. This happened in Chrome, Firefox, Edge, and on mobile (iPhone 6S Safari).

**3. Entered link:** 0123
The same thing as 2. (above) happened when I tried entering another string of numbers as the registration link. After saving the event with this link, the link displayed as https://eypd.bccampus.ca/events/sign-language-for-eces/123/ and led to the same event page (again, as if I'd hit "refresh"). Selecting the registration link from this page changed the URL to https://eypd.bccampus.ca/events/sign-language-for-eces/123/0123 and led to the error page again. This happened in Chrome, Firefox, Edge, and on mobile (iPhone 6S Safari).

**4. Entered link:** */$
Tried random characters. After saving the event, this link displayed as https://eypd.bccampus.ca/events/sign-language-for-eces/*/$ and led to the error page pictured above. This happened in Chrome, Firefox, Edge, and on mobile (iPhone 6S Safari).

**5. Entered link:** https://bccampus.ca
This registration link successfully directed me to the BCcampus home page in Chrome, Firefox, Edge, and on mobile (iPhone 6S Safari). It was quite slow on Firefox and mobile--not sure if that is relevant.

**Comment by bdolor** [comment]
Thanks @kkilbey for such a thorough analysis. I've moved the validation routine to the input side via https://github.com/BCcampus/eypd/commit/468d006133862df544d1e49719497b794a0d5b4b which will generate an error if anything that is not a URL is detected.

![image](https://user-images.githubusercontent.com/2048170/49183742-7c968400-f312-11e8-87aa-d9e667604be4.png)

**Comment by bdolor** [comment]
excellent @kkilbey - good sleuthing.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/eypd/commit/7ed4b842d3ddd0dbeb46bdff3cfd07b48542c51c

**Comment by paulagaube** [comment]
@bdolor I just tried to add an event without anything in the "Registration Link" field, and was unable to Post the event. I received the error message you showed above, which is: "Registration Link is not a valid URL". 

Since this is not a "required" field, (i.e., there is no asterisk* after the text Registration Link and the text below says "if available"): I believe leaving this field empty must also be allowed without generating an error message. @kathreenriel your thoughts? It's possible that an event will not have a web URL, is that correct?

**Comment by bdolor** [comment]
that makes sense. boy, this is the ticket that just won't quit  
¯\_(ツ)_/¯

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/eypd/commit/650e46e77b292be73d330dbb0f5ca785de5471ee

**Comment by paulagaube** [comment]
Kelsey and I tested and this works for us now. Thanks, @bdolor 

@kathreenriel I'm moving this to done, but you may want to check it too?

**Comment by kathreenriel** [comment]
@paulagaube yes, I'll check it

**Comment by kkilbey** [comment]
This looks good on prod.
Perhaps in a future sprint, these registration links could be set to open in a new tab? But in regards to this ticket: mission accomplished.
