### ISSUE TITLE
Automatically change the display name on sign up for organizers

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#123]
display name is currently taken from the 'First and Last Name Field' 

This is undesirable for Organizers. Preferable would be to take the value of 'Name of your Place of Work Field' and make it the display name on sign up. Only for Organizers.

**Comment by kathreenriel** [comment]
We worked around this by manually changing names of Organizers to improve clarity of identity of organizations and adding best practice  to FAQ's
