### ISSUE TITLE
Notification System: Set up and Test

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#199]
Set up the rss-to-email feature, create/import the subscriber list
create the template
test it with specified audience

**Comment by kathreenriel** [comment]
Based on feedback from advisory group and EYPD sector this needs to be a notification system that is more customized based on:
- topic
- category
- presenter
- location
Would like to revisit/review during Sprint - November 14-17

**Comment by alexpflores** [comment]
Location Example: https://earlyyearsbc.ca/feed/?post_type=event&event_location=vancouver

**Comment by alexpflores** [comment]
With the additional features, consider using a different solution such as [mailpoet ](https://www.mailpoet.com/)
