### ISSUE TITLE
Images Glitch with Blog Posts

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#268]
When publishing a new blog post it is not possible to integrate images within the text of the blog. Issues:
 Images get "pushed" to the bottom of the post. 
Adding more than one image replaces the previously inserted image and moves it to the bottom of the post. 
To test, see New Test Post: https://eypd.bccampus.ca/wp-admin/post.php?post=2344&action=edit

**Comment by bdolor** [comment]
Documenting problems/observations here: Users can add multiple images to a post without knowing it...ends up being visible in the edit view of the post (dashboard) if a banner image is modified, using the front end form 'edit events' 

![image](https://user-images.githubusercontent.com/2048170/33346132-890bb21c-d443-11e7-9254-a9af2d8a295f.png)

**Comment by alexpflores** [comment]
@bdolor Good notes, since Events are only created on the front-end right now, we can avoid this issue when/if we move to using the back-end to author events. The content_pre_filter is applied after they hit the publish/update button, it'll remove all of these images except the latest on they've added, which becomes their banner image.

**Comment by bdolor** [comment]
Rather, this creates an issue for us when we move to the back end. If it's not addressed now, we have problems later. The `content_pre_filter` only tiggers in the dashboard, so the 'fix' for the cloodge only causes more problems.

**Comment by alexpflores** [comment]
@bdolor  The road back to using the back-end and featured image, would be removing that function which contains `content_save_pre`,  we can nuke along with `eypd_banner_image`. 

Removing those two functions, and uncommenting the featured image in the theme, will let us use the back-end as per normal (along with featured image.)

**Comment by bdolor** [comment]
there are also roles to roll back, not to mention the modifications to existing content/images that are currently using this system of displaying images.

**Comment by bdolor** [comment]
This isolates the undesirable behaviour to 'event' post types only. Can't say that it's a satisfactory solution, but it's fixed as far as the problem has been defined. https://github.com/BCcampus/eypd/commit/fce7db4dc740860f307eb54d5726c9f03dfd1455 ready for validation

**Comment by kathreenriel** [comment]
Yes, this image issue was described as a problem with images and blog posts not event posts - although I realize they're related. As a result, validation will be reviewed with images integrated in blog posts if necessary.

**Comment by alexpflores** [comment]
I went through every published event on PROD and found there are **18** events using banner images at this time. So if we chose to roll this back, it should be a quick task (~1hr) to edit these events to use a featured image instead.  

Here's the list:
https://earlyyearsbc.ca/events/child-care-provider-networking-night-christmas-themed/ 
https://earlyyearsbc.ca/events/to-celebrate-or-not-to-celebrate/
https://earlyyearsbc.ca/events/blocks-whod-a-thought-learning-could-be-such-fun/
https://earlyyearsbc.ca/events/exploring-light-and-shadows/
https://earlyyearsbc.ca/events/kids-have-stress-too/
https://earlyyearsbc.ca/events/children-the-heart-of-the-matter-conference/
https://earlyyearsbc.ca/events/your-childcare-promote-learn-and-share/
https://earlyyearsbc.ca/events/appetite-to-play-7/
https://earlyyearsbc.ca/events/emergency-child-care-first-aid-cpr-level-b/
https://earlyyearsbc.ca/events/sign-me-a-story-volume-two/
https://earlyyearsbc.ca/events/high-five-quest-2/
https://earlyyearsbc.ca/events/setting-up-ece-environments-for-success-making-math-and-science-concepts-fun/
https://earlyyearsbc.ca/events/high-five-trainer-course/
https://earlyyearsbc.ca/events/what-childrens-behaviour-might-be-telling-us/
https://earlyyearsbc.ca/events/20-hour-responsible-adult-course-7/
https://earlyyearsbc.ca/events/should-i-refer-when-and-how-to-talk-to-parents/
https://earlyyearsbc.ca/events/nourish-why-food-and-relationships-belong-together/
https://earlyyearsbc.ca/events/to-celebrate-or-not-to-celebrate-5/

**Comment by kathreenriel** [comment]
Wouldn't we  need to save the current image used for each event in order to match the images and events?

**Comment by alexpflores** [comment]
@kathreenriel the image will be in the media library from the first time they uploaded it

**Comment by kathreenriel** [comment]
We have created several blog posts since Nov. 30 and there is not issue with formatting.
