### ISSUE TITLE
Lazy-loading images

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#270]
Find the best way to lazy load images/ Consider using an IntersectionObserver to intelligently determine when to lazy-load offscreen images.

**Comment by alexpflores** [comment]
<img width="553" alt="lazy" src="https://user-images.githubusercontent.com/17072191/32186420-47aafd28-bd5f-11e7-850a-c14be7acb18e.png">

**Comment by alexpflores** [comment]
Installing this [WordPress image lazy load](https://wordpress.org/plugins/bj-lazy-load/) plugin solved this for us.  Here's a comparison audit for the home page. **Note:** The biggest benefit here will be for mobile devices, this improvement in the audit is focused on lazy-loading off-screen images only. 

The difference in the audit now that all of our offscreen images in our theme and content are lazyloaded, so we are 100% meeting this requirement. BUT unfortunately the Audit complains about images which are coming from google maps. Lazy loading these may not be possible, and requires additional resources/time to investigate. 

<img width="683" alt="new_lazy" src="https://user-images.githubusercontent.com/17072191/32201521-b95010c8-bd94-11e7-82ff-722a8befea7c.png">

**Comment by alexpflores** [comment]
Moved lazy-loading of google maps to it's own issue #280

**Comment by alexpflores** [comment]
Looking into [PWP Lazy Image](https://github.com/GoogleChromeLabs/ProgressiveWordPress/blob/master/src/pwp-lazy-image-plugin/pwp-lazy-image-plugin.php) Plugin to see if it solves this problem in a better way for us.

**Comment by alexpflores** [comment]
**Results of testing PWP Lazy Image:**
No improvements on Audit gained from Google's PWP Lazy Image. The problem with lazy loading plugins for WordPress, is that they are only concerned on lazy-load images **inside** the post/page content. So if our Website was heavy on images within pages/posts, we'd see great benefits. But any images outside of that are ignored. Our theme images (the two in the footer) were not Lazy-loaded, along with the external images that are coming from Google maps. 

**The originally proposed solution (on cert now):** 
This does Lazy-Load both the images in the content, and in our theme, hence the _**slight**_ improvement. But it does not do anything with the externally hosted images coming from Google Maps, resulting in the low audit score. 

**Next Steps:** 
I attempted to modify Google's plugin in an effort to include our theme images, along with external images. I was not successful in this endeavor. At this time, it is my view is that it may not be feasible within this sprint. Please see #280 in the product backlog.

**Comment by alexpflores** [comment]
@kathreenriel If you're satisfied with the solution on cert now ([image lazyl-oad plugi](https://wordpress.org/plugins/bj-lazy-load/)n) this can be considered done/closed.
