### ISSUE TITLE
Reduce Render-Blocking scripts

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#271]
For critical scripts, consider inlining them in your HTML. For non-critical scripts, consider marking them with the async or defer attributes.

**Comment by bdolor** [comment]
hooking into script_loader_tag is the current way to add async loading to scripts:

References:
https://core.trac.wordpress.org/ticket/12009
https://developers.google.com/speed/pagespeed/insights/

Something like the following might be a start:

```
/* ------------------------------------------------------------------------ *
 * Asyncronous loading to improve speed of page load
 * ------------------------------------------------------------------------ */
add_filter( 'script_loader_tag', function ( $tag, $handle, $src ) {
	$async = array(
		'script1',
		'script2',
		'script3',
	);
	if ( in_array( $handle, $async ) ) {
		return "<script async type='text/javascript' src='{$src}'></script>" . "\n";
	}
	return $tag;
},10,3)
```

**Comment by bdolor** [comment]
moved our scripts to the footer, added asynchronous loading to common js scripts via https://github.com/BCcampus/eypd/commit/43dc7dc108434896fa8d4d03a78953ad73ea0919

improves page performance from low 20s to 34 
![image](https://user-images.githubusercontent.com/2048170/32383909-890f87d8-c076-11e7-853d-ac36635c9b05.png)

gtmetrix at 87

![image](https://user-images.githubusercontent.com/2048170/32384043-e6b33fc4-c076-11e7-9a68-4878a8bfc75a.png)

**Comment by kathreenriel** [comment]
Up to 88 
<img width="525" alt="screen shot 2017-11-03 at 5 45 27 pm" src="https://user-images.githubusercontent.com/16693738/32400554-e6b28b7c-c0be-11e7-8a4b-dda1616fbb09.png">
