### ISSUE TITLE
Server Optimization - find ways to improve the speed of the server

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#272]
Etag headers, HTTP2 

implement some of the configuration suggestions here: 
https://github.com/h5bp/server-configs-apache/tree/master/src

**Comment by bdolor** [comment]
a number of server performance measures have been made bringing the gtmetric from an `F` to a `B`: 

![image](https://user-images.githubusercontent.com/2048170/32199419-a9da9cc2-bd89-11e7-90a2-0fac14a1e4c1.png)

https://github.com/h5bp/server-configs-apache/tree/master/src/web_performance
https://github.com/h5bp/server-configs-apache/tree/master/src/cross-origin

a JIRA ticket has been opened to look at enabling HTTP/2

**Comment by alexpflores** [comment]
Waiting on George to do stuff

**Comment by kathreenriel** [comment]
I didn't follow up with George. I'll do this in person next week.

**Comment by kathreenriel** [comment]
I checked in with George about this on Tuesday, November 21. The server isn't responding as expected George doesn't know why - yet.
