### ISSUE TITLE
Make a manifest

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#277]
To get it recognized as an application

**Comment by alexpflores** [comment]
Depends on app icons (have to add path to manifest)

**Comment by bdolor** [comment]
@kathreenriel — you can verify this with Dev Tools, under the 'Applications' tab - look for the manifest. As it is you won't get prompted to 'Add to Home Screen' b/c there is no service worker. One thing I'm keeping my eye on also, is the location of the `manifest.json` file. Right now it's in with the theme directory but as I get into the service worker part, I'm learning that there may be reason to place at the root of the WP installation. 

![image](https://user-images.githubusercontent.com/2048170/32287434-11102280-beee-11e7-8328-995999833fb4.png)

We've moved the PWA metric up to 55, but could move it up further if we include a 512x512 icon for a splash screen. 

![image](https://user-images.githubusercontent.com/2048170/32287635-b7b81e62-beee-11e7-9a05-5c2b1493ece5.png)

**Comment by kathreenriel** [comment]
I checked this out following your instructions.  Robyn is off now but let me see if I can get/create a 512 icon
