### ISSUE TITLE
Create APP icon

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#278]
Get different app icon sizes as required, see:
https://developer.mozilla.org/en-US/docs/Web/Manifest
https://developers.google.com/web/fundamentals/web-app-manifest/

**Comment by alexpflores** [comment]
@kathreenriel  Waiting for the app icon images.

**Comment by kathreenriel** [comment]
Images from Robyn
[EYPD Hand for Mobile.zip](https://github.com/BCcampus/eypd/files/1431400/EYPD.Hand.for.Mobile.zip)

**Comment by kathreenriel** [comment]
@alexpflores @bdolor Please take a look to see if these are the correct images that you need. Robyn is working limited hours today and tomorrow and then off Thurs. and Friday

**Comment by bdolor** [comment]
sizes aren't quite rectangular 

![image](https://user-images.githubusercontent.com/2048170/32239934-32bb8c28-be29-11e7-99ea-c0afa0ac67f0.png)

it's a fairly minimal discrepancy. Resizing them to the correct dimensions will modify the proportions. How much of a distortion it will cause to the image is likely to be minimal.

**Comment by kathreenriel** [comment]
Not sure why Robyn created them this way. Shall I resize them to the original specs?

**Comment by bdolor** [comment]
if you have the power...

**Comment by kathreenriel** [comment]
![eypd-hand-192x192px](https://user-images.githubusercontent.com/16693738/32241526-a38be624-be2d-11e7-8889-10eaf3c68272.png)
![eypd-hand-168x168px](https://user-images.githubusercontent.com/16693738/32241527-a3a5a79e-be2d-11e7-8e42-390f930545c9.png)
![eypd-hand-144x144px](https://user-images.githubusercontent.com/16693738/32241528-a3bec2ba-be2d-11e7-8c5a-eb4ffa01b04a.png)
![eypd-hand-96x96px](https://user-images.githubusercontent.com/16693738/32241529-a3d8eaa0-be2d-11e7-9a0e-4cbf5acb4d25.png)
![eypd-hand-72x72px](https://user-images.githubusercontent.com/16693738/32241530-a3f3da72-be2d-11e7-9cb0-25f610f78e55.png)
![eypd-hand-48x48px](https://user-images.githubusercontent.com/16693738/32241531-a411387e-be2d-11e7-9a24-04416c734edd.png)

**Comment by kathreenriel** [comment]
Just adjusted the sizes in Preview. Hopefully that works.

**Comment by kathreenriel** [comment]
![eypd- hand-512x512](https://user-images.githubusercontent.com/16693738/32294504-9efd7cfe-bf03-11e7-8d5f-a9bf8d5b33d8.png)

**Comment by kathreenriel** [comment]
512X512 image

**Comment by kathreenriel** [comment]
Added image to meet the needs expressed in Issue #277 "We've moved the PWA metric up to 55, but could move it up further if we include a 512x512 icon for a splash screen."
