### ISSUE TITLE
Network/Cache Service Worker

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#279]
Add a [cache service worker](https://serviceworke.rs/strategy-network-or-cache_service-worker_doc.html). Determine which strategy to use with input from @kathreenriel on the specific use case for a learner/organizer.

**Comment by alexpflores** [comment]
@kathreenriel Waiting for the use case to choose appropriate strategy.

**Comment by kathreenriel** [comment]
Based on what I have read here - https://developers.google.com/web/ilt/pwa/caching-files-with-service-worker I think, Cache then network is the best option...I think

**Comment by alexpflores** [comment]
We officially have a PWA ! 
![app_icon](https://user-images.githubusercontent.com/17072191/32355832-5fba326c-bfee-11e7-9532-28b80c4600c2.png)

![app_loading](https://user-images.githubusercontent.com/17072191/32355834-5feec5ea-bfee-11e7-9176-9fac1e127960.png)

![app_landing](https://user-images.githubusercontent.com/17072191/32355833-5fd6e466-bfee-11e7-9e31-982b999e9ab6.png)

**Comment by kathreenriel** [comment]
Ahhhhhh!! That’s so GREAT!
