### ISSUE TITLE
Homepage: Make banner image and words bigger and bolder

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#292]
The words and banner on the early years homepage need to be enlarged and made bolder (slightly) to appear more proportional  with the surround blue space and the logos at the top. 
![earlyyearsbanner](https://user-images.githubusercontent.com/16693738/32455111-298f1528-c2d6-11e7-9a04-602dff2af8ea.png)

**Comment by alexpflores** [comment]
@kathreenriel  Waiting for assets to make this change

**Comment by kathreenriel** [comment]
Talked with Robyn about this this morning. She will try to get the assets to us this week.

**Comment by alexpflores** [comment]
@kathreenriel Missed that e-mail, please forward. For the screenshot you posted of the bc/eypd logo missing, was that on eypd.bccampus.ca and on an iphone? tnx

**Comment by kathreenriel** [comment]
For mobile devices(smaller than an iPad/tablet)  Robyn suggested omitting the BC ministry and EYPD logos.

**Comment by kathreenriel** [comment]
Will email you the svg images she sent

**Comment by alexpflores** [comment]
Taken care of in #309 will be ready for validation once that's merged.

**Comment by alexpflores** [comment]
Ready for validation

**Comment by kathreenriel** [comment]
The title is duplicated? <img width="1062" alt="screen shot 2017-11-17 at 10 38 22 am" src="https://user-images.githubusercontent.com/16693738/32963034-794363f2-cb83-11e7-84b1-5e92a8f63f05.png">

**Comment by bdolor** [comment]
refresh cache.

**Comment by kathreenriel** [comment]
thanks  :)

**Comment by bdolor** [comment]
just noticed this anomaly - @alexpflores `.container-fluid` is controlled by bootstrap which centers the logo(s). bootstrap isn't loaded when logged in as an admin (and shouldn't be) but the result is the logo(s) are shoved to the left: 

![image](https://user-images.githubusercontent.com/2048170/32963273-5361e176-cb84-11e7-9148-6c879ff043aa.png)

**Comment by alexpflores** [comment]
Thanks @bdolor will wait for any additional changes from @kathreenriel before moving this back to doing to see how to tackle that one.

**Comment by kathreenriel** [comment]
1. Yes, the logo/words shift to the left when one is logged in as a Learner, Organizer and Admin.
2. Checked this on my iPhone and also when not logged in you see the entire title of the site (includes Explore Learn Grow) but once logged in the qualifying statement disappears. (see pics below)
3. EYPD with the Provincial Map logo looks quite big on the phone.
Before login 
![img_1620](https://user-images.githubusercontent.com/16693738/32965924-0aa6e3c4-cb8d-11e7-944f-0d038d5eb534.png)
After login 
![img_1622](https://user-images.githubusercontent.com/16693738/32965951-1cb1f964-cb8d-11e7-9d04-84265e9162cf.png)

**Comment by alexpflores** [comment]
must've closed by accident, #butterfingers

**Comment by bdolor** [comment]
@kathreenriel — ready for validation

**Comment by kathreenriel** [comment]
![img_1633](https://user-images.githubusercontent.com/16693738/33294594-36a51882-d386-11e7-8f0b-986ffed9b165.png)

The title is duplicated in the top banner on iPhone using Chrome

**Comment by bdolor** [comment]
please confirm this is not a cache problem. This looks very 'cache-y'

**Comment by kathreenriel** [comment]
Yep. Humbly...taking back the issue to validation

**Comment by kathreenriel** [comment]
@paulagaube would you check this everyone's favourite browser -I.E.?
Merci

**Comment by paulagaube** [comment]
@kathreenriel  The eypd site and banner looks good in I.E.! The title is not duplicated.

**Comment by kathreenriel** [comment]
Thanks @paulagaube

**Comment by kathreenriel** [comment]
Conducted user testing on the EYPD (dev) site this morning and the banner was missing when looking at the EYPD site on my phone. Trying to replicate

**Comment by kathreenriel** [comment]
Seems to appear in Safari and Chrome
