### ISSUE TITLE
Service Worker Strategy Investigation

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#295]
Figure out how to implement Cache then Network strategy.

**Comment by bdolor** [comment]
Adding the 'Add to Homescreen' popup on mobile

![screenshot_20171117-123723](https://user-images.githubusercontent.com/2048170/32968321-b3259902-cb95-11e7-8825-5b97fe922ee5.png)

and ability to add as an application in Chrome: 

![image](https://user-images.githubusercontent.com/2048170/32968064-bd519b16-cb94-11e7-9b1b-020974fc66e0.png)

**Comment by kathreenriel** [comment]
How do I get this ADD pop up to show on my iPhone?

**Comment by bdolor** [comment]
maybe use chrome?

**Comment by alexpflores** [comment]
Works on Chrome for me on android.

**Comment by bdolor** [comment]
support for service workers is browser based:

![image](https://user-images.githubusercontent.com/2048170/32974006-ed5bb02e-cbaf-11e7-8dec-db30f21ae6eb.png)

**Comment by kathreenriel** [comment]
Yes I'm using chrome..hmm..will keep looking

**Comment by kathreenriel** [comment]
I can't get this to work on my Apple devices. :(
