### ISSUE TITLE
Post An Event Page and Edit An Event: Icons Illustrated - Firefox Issue, Safari Issue

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#298]
Conducted user testing this morning and the user noticed the "edit" icon and wondered why it was there. She was using Firefox. Checked later and yes the edit icons appear on the Post and Event and Edit An Event pages. See below 
<img width="444" alt="editevents" src="https://user-images.githubusercontent.com/16693738/32859335-031bd29e-ca03-11e7-8442-2298aaaf3f1f.png">

<img width="868" alt="screen shot 2017-11-15 at 12 46 08 pm" src="https://user-images.githubusercontent.com/16693738/32859329-ff9077ce-ca02-11e7-9177-345ce4d8271c.png">

10% of visitors are Firefox users.
<img width="378" alt="screen shot 2017-11-15 at 12 39 04 pm" src="https://user-images.githubusercontent.com/16693738/32859239-bc4913fe-ca02-11e7-8c04-63bb16e984d7.png">

**Comment by kathreenriel** [comment]
Saw this on Safari on a iPad 

![ipad using safari](https://user-images.githubusercontent.com/16693738/32967434-87e5837c-cb92-11e7-8e73-76979561d9e8.jpg)

**Comment by kathreenriel** [comment]
Icons appear when user is logged in

**Comment by alexpflores** [comment]
Hand is now gone, please clear browser cache.

**Comment by kathreenriel** [comment]
I don't see it in Safari, or Firefox anymore @paulagaube please check I.E.

**Comment by kathreenriel** [comment]
Note to self: Before moving to done check formatting of  paragraph at the top of the MyEYPD page. 
<img width="749" alt="screen shot 2017-11-29 at 2 51 40 pm" src="https://user-images.githubusercontent.com/16693738/33403360-f3353092-d514-11e7-9f31-8f0b8934283e.png">

**Comment by paulagaube** [comment]
@kathreenriel I checked in IE 11 and there is no hand showing. Also checked Chrome and Firefox on PC, and confirm no hand appears. Also checked on my iPhone in Safari. All good.
