### ISSUE TITLE
Edit Event Page: Column Issue- Firefox

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#299]
In Firefox, the events do not render correctly and are squished into three columns. Instead of neatly arrayed in three columns as seen in Chrome

**Firefox** 
<img width="408" alt="firefox" src="https://user-images.githubusercontent.com/16693738/32859506-8d3c7636-ca03-11e7-80c7-70f380a4b754.png">

**Chrome**
<img width="732" alt="chrome" src="https://user-images.githubusercontent.com/16693738/32859511-91010822-ca03-11e7-9110-cb95345932c1.png">

**Comment by alexpflores** [comment]
Ready for validation, here's a screenshot of fire fox: 
![screen shot 2017-11-27 at 3 28 54 pm](https://user-images.githubusercontent.com/17072191/33295413-0c66a780-d38a-11e7-8eeb-5dbbf22a334f.png)

**Comment by kathreenriel** [comment]
Yes this looks good in Firefox and Safari

**Comment by paulagaube** [comment]
I.E. 11 on Win 7 is still squished to the left.
![2017-11-28-ie11-editevents](https://user-images.githubusercontent.com/26391359/33338694-b7182d9c-d42b-11e7-8ad4-3b1998e3a5ae.png)

**Comment by alexpflores** [comment]
@paulagaube Please confirm this is still an issue after browser cache is cleared? The proposed solution added `table-layout:fixed` styling to the table, and appears to be supported by IE 11.

**Comment by paulagaube** [comment]
@alexpflores Hurray! I cleared my cache in IE 11 and the table is full-width. (D'oh!) Sorry about that. The Edit Events list looks great now.
