### ISSUE TITLE
Async/Non-blocking Script Pattern for JS/CSS with Lazy-Loading

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#317]
As it relates to WordPress, for the purpose of performance gains on the **first paint.** 

**Please note:** It's unclear what observable performance gains can be expected, the biggest gain will come from a page with the greatest amount of resources, which currently pause/slow down page execution. If first-paint is currently at an satisfactory level, this endeavor might not be worth it. 

This will require:
1. A way to identify critical JS and CSS on a page as it's requested. Be it an external resource, or from our plugins and theme. 

2. Inline those critical resources, while async/defer and lazy-loading the rest so that first paint is as fast as possible.

2. The fallback code for each resource, for browsers that don't support the feature, or have JS disabled.

**Comment by kathreenriel** [comment]
I think it's okay
![screen shot 2018-10-23 at 1 00 47 pm](https://user-images.githubusercontent.com/16693738/47387297-c234b100-d6c3-11e8-9411-04a32384f312.png)
