### ISSUE TITLE
Homepage: Add video image to footer

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#318]

**Comment by kathreenriel** [comment]
This is a follow-up to #267. Awaiting image

**Comment by alexpflores** [comment]
Throw into New WordPress image widget.

**Comment by kathreenriel** [comment]
![thumbnail](https://user-images.githubusercontent.com/16693738/33288334-bd5b21de-d370-11e7-854e-3e6f3c4f3506.png)

**Comment by kathreenriel** [comment]
Hi Alex, 

Here is the image Robyn resized to the parameters according to your specifications. Hmm.. does it seem a little too wide?

**Comment by alexpflores** [comment]
@kathreenriel Please see https://eypd.bccampus.ca/, the image is in an image widget, can be easily changed if you'd prefer a different size. Videos are usually wide screen, so it makes sense it'd be wider I think, but really doesn't matter, up to you!

**Comment by kathreenriel** [comment]
Oh it does look good! Great! It just needs a title above it that says, "EYPD Overview" in the same format as the titles, "Support" and "Policies".

**Comment by alexpflores** [comment]
@kathreenriel Title added.

**Comment by kathreenriel** [comment]
Title looks good. The original plan in issue #267 was to have the video open in a modal box. Right the link opens a new tab and goes...to ubc? 
![modalbox](https://user-images.githubusercontent.com/16693738/33293294-33caf302-d381-11e7-8065-5887e3159f09.jpg)
<img width="1176" alt="screen shot 2017-11-27 at 2 43 07 pm" src="https://user-images.githubusercontent.com/16693738/33293363-61ad78d0-d381-11e7-8205-65992b76fbd7.png">

**Comment by paulagaube** [comment]
Here is the link to the video on the video.bccampus.ca (Kaltura). Is this where the link is supposed to go? 
https://video.bccampus.ca/media/The+Early+Years+Professional+Development+Web+Portal+%E2%80%93+An+Overview/0_6bvdeq5p/21249

**Comment by paulagaube** [comment]
Hi - here is what the footer looks like on my Windows computer, using Firefox (also looks the same in Chrome). The image looks transparent as it blends in with the background, so to my eye, the black lines look more like a dotted road line than a filmstrip. How about putting a black border around the image to contain it? See images below:
![video-image-noborder](https://user-images.githubusercontent.com/26391359/33294492-b726cb96-d385-11e7-9a9d-b37be1af1f66.jpg)
![video-image-border](https://user-images.githubusercontent.com/26391359/33294494-ba60c7ee-d385-11e7-80fb-ad2f542c92a8.jpg)

**Comment by paulagaube** [comment]
@kathreenriel side note: if we are going to use the Kaltura version of that video, I think I can change the first image on the video to be the same as the new video image Robyn created if you'd like.

**Comment by kathreenriel** [comment]
@paulagaube I wasn't aware that we were using Kaltura - the video source on the dev site is different from the video source on the prod site.

**Comment by paulagaube** [comment]
Interesting. I think UBC is hosting Kaltura for us, so that is probably why the other link shows video.ubc.ca, though I hadn't noticed that before. 
It looks like the vimeo video version has the most views so far. Maybe that's the one to use to keep it consistent? :)

**Comment by kathreenriel** [comment]
There is the word, test appearing on homepage. 
<img width="1195" alt="screen shot 2017-11-28 at 12 53 58 pm" src="https://user-images.githubusercontent.com/16693738/33343793-813673ae-d43b-11e7-8072-82addefd0d33.png">

**Comment by alexpflores** [comment]
@kathreenriel That's a custom html widget to test the modal functionality, please disregard the EYPD overview section until I've moved over into validating.

**Comment by alexpflores** [comment]
@kathreenriel I've fixed this, but it'll still look a bit off because there's no title in the first search field. I've noticed that's the case in Prod and Cert as well, is this intentional? Or did I find another bug? 

Fixed: 
![screen shot 2017-11-28 at 3 37 34 pm](https://user-images.githubusercontent.com/17072191/33350261-b865a3a6-d452-11e7-8e54-7f8294b681aa.png)

Prod: 
![prod](https://user-images.githubusercontent.com/17072191/33350277-cba632fa-d452-11e7-9fcb-8d71721b0f5a.png)

**Comment by alexpflores** [comment]
Completed via #324 shoutout to @bdolor for making it defer and jQuery dependency check

**Comment by alexpflores** [comment]
@kathreenriel FYI when this to go to prod, it will require adding/updating the URL of the image in the custom HTML widget. Here's a screen shot: 

![footervid](https://user-images.githubusercontent.com/17072191/33400737-e25b4c2e-d50b-11e7-85e8-5773c7dec60f.png)

**Comment by alexpflores** [comment]
Here's the correct HTML for Prod widget:

`<a href="#video" data-toggle="modal"><img alt="video" src="https://earlyyearsbc.ca/wp-content/themes/early-years/assets/images/video.png"></a>`

**Comment by kathreenriel** [comment]
Niiiiiice! @alexpflores @bdolor  looks good on all my browsers and on my phone. @paulagaube would you check it on I.E. please?

**Comment by paulagaube** [comment]
Yes, it works in IE 11. Looks good. Full-screen mode works too.
