### ISSUE TITLE
HTML template creation

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#330]
TBD, the text of the message. 

starting point:

![image](https://user-images.githubusercontent.com/2048170/36390523-34656cde-1558-11e8-9f36-91b7abd4f60e.png)

There will be a dynamic aspect of the message which will include the title of most recent 5 events. The title will also contain a link back to the website (of the event). Using the same logic of the recently posted tab in the home page.  

Link to unsubscribe functionality needs to be included. This will take the user back to their user profile page.

**Comment by paulagaube** [comment]
Hi Kathreen, I think this looks great! How about adding one more line prodding them to look for more events? Something like this, a line just above the "earlyyearsbc.ca" link:
Explore, Learn, and Grow with EYPD
**_Find more events on_**
earlyyearsbc.ca

**Comment by kathreenriel** [comment]
Thanks @paulagaube I'll add that phrase

**Comment by kathreenriel** [comment]
<img width="685" alt="screen shot 2018-02-22 at 12 50 21 pm" src="https://user-images.githubusercontent.com/16693738/36563466-0219938a-17cf-11e8-80e2-1e369ffaa886.png">

**Comment by lindsayseg** [comment]
Hi @kathreenriel this looks good to me! The one suggestion I thought of was putting "find more events at earlyyearsbc.ca" ahead of "explore, learn, and grow with EYPD". I just thought that the "explore, learn, grow with EYPD" feels more of a ending tagline, and the "find more events" seems to make sense to follow directly after the top 5 events listed. Other than that i think it looks great!

**Comment by paulagaube** [comment]
Found here:
eypd.bccampus.ca > Dashboard > Settings > Custom WP Notify

**Comment by paulagaube** [comment]
I have added some text to the Template to test the email notifications. 

Why does the unsubscribe link in the email go to the list of members, here: https://eypd.bccampus.ca/members/

I can see where to change the link on the Template page in WP, but what should the link be, if not the members page?

Does this link need to include some smart URL to take me directly to my member page where I can change my notifications? Or is that too sophisticated for what we are doing? Does the link take me to the members page so I can find my name, and then login and change my notifications/subscription? 

Is this "members" page a good thing to share with all other users?

**Comment by kathreenriel** [comment]
Last comment was addressed in issue #364
