### ISSUE TITLE
Subscribe Unsubscribe feature in User Profile Section

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#331]
TBD - copy for the subscription preference area in the user's profile

Functionality - needs to be a clear way for the user to opt-out of notifications. Which page it's on needs to be determined.

**Comment by kathreenriel** [comment]
Seems like the best page is the edit profile page 
<img width="304" alt="screen shot 2018-02-21 at 12 40 56 pm" src="https://user-images.githubusercontent.com/16693738/36504221-9eda5c02-1704-11e8-9e43-89fa9db50a9e.png">

**Comment by kathreenriel** [comment]
How about specific language that indicates the exactly what the information is see below. 
![editprofilemenu](https://user-images.githubusercontent.com/16693738/36504245-bb8a12e8-1704-11e8-9d57-fb32617518ab.jpg)

**Comment by alexpflores** [comment]
Working on updating this user preference on change (when checkbox is clicked, or unlicked, and store their preference, without having to submit a form). This is needed for the shortcode to work regardless of where it's placed (on a form or a page etc).

**Comment by alex-418** [comment]
Default checkbox one liner shout out to @bdolor  https://github.com/BCcampus/custom-wp-notify/pull/6

**Comment by bdolor** [comment]
@paulagaube please validate on your `myEYPD` page - this will also mean you should start receiving emails (sometime within the next 24 hours)

**Comment by paulagaube** [comment]
Ok, I have signed up for notifications for myself and Bradner (an Organizer account).

**Comment by kathreenriel** [comment]
@bdolor logged Learner to eypd and do not see Subscribe to Event Notifications on the myEYPD page. I do see it when logged in as an Organizer

**Comment by bdolor** [comment]
Oh, thanks Kathreen — will take a look and rectify if necessary

**Comment by bdolor** [comment]
should be addressed in https://github.com/BCcampus/eypd/pull/355

**Comment by kathreenriel** [comment]
@bdolor The default for Notifications subscriptions is that the checkbox is selected with a checkmark - correct?

If yes, then I noticed the Learner has to select the checkbox.

**Comment by bdolor** [comment]
The default is unchecked (unsubscribed). You and Paula were automatically subscribed because I modified values for just the two of you in the database prior to this feature being available. I think we determined that we'd move the ability to manually unsubscribe/subscribe users to the admin area.

**Comment by alex-418** [comment]
@kathreenriel Anything else to do on this one?
