### ISSUE TITLE
Plugin Options page and shortcode hooks

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#332]
There needs to be the ability for users to customize options that the plugin offers. Possible options include templates, unsubscribe/subscribe, frequency, etc. 

Potential for short code hooks so that options can be presented on any page of a theme developer's choosing.

**Comment by alexpflores** [comment]
Options page and the shortcode` [cwp_notify]` created. It can be placed on any page. Working on #331 to store/retrieve this.

**Comment by alexpflores** [comment]
**Shortcode:**
![screen shot 2018-02-22 at 4 14 40 pm](https://user-images.githubusercontent.com/17072191/36571520-f555d7e0-17eb-11e8-81a0-bb301e3140c4.png)

**Plugin Options Page:**

![options](https://user-images.githubusercontent.com/17072191/36571517-f27d8612-17eb-11e8-82db-eaa325de39ac.png)
