### ISSUE TITLE
Business Logic for newsletter content

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#333]
When: Tie into wp_cron job

What: What is the logic for which events are being dissemination. (same as recently posted tabs) 

Who: Create the logic for looping through which users are receiving the email.

**Comment by alexpflores** [comment]
How: Tie into [wp_mail](https://developer.wordpress.org/reference/functions/wp_mail/)

**Comment by bdolor** [comment]
this is complete in https://github.com/BCcampus/custom-wp-notify/pull/2 though tying into cron has been broken off into its own ticket https://github.com/BCcampus/eypd/issues/339 - will be difficult to validate this from a UAT perspective until other pieces are in place.
