### ISSUE TITLE
Notification Plugin Git repository 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#336]
The notification plugin requires a repository, user license, Readme, .gitignore file, installation instructions etc. (And Add jenkins webhooks if necessary)

**Comment by alexpflores** [comment]
Repository created at https://github.com/BCcampus/custom-wp-notify

**Comment by bdolor** [comment]
jenkins?

**Comment by alexpflores** [comment]
Would like to instead require WordPress plugins as dependencies in our projects via composer. It makes sense to keep all dependencies in the same place. Could be a quick win via https://wpackagist.org/ which makes every wordpress.org hosted plugin and theme available through composer... also could add our plugin as a package on packagist and achieve same results.

**Comment by bdolor** [comment]
jenkins has functionality that we need above and beyond what composer and packagist can offer. Specifically, if our plugin custom-wp-notify has dependencies it will build them for us. Also, (eventually) phpunit tests. Then there's deployment to multiple servers. Continuous Integration and Continuous Deployment aren't features of dependency mgmt. Comparing a dependency manager with a build server is an inaccurate comparison.

**Comment by alexpflores** [comment]
Okay, I'll split jenkins into it's own issue and tackle that.
