### ISSUE TITLE
Jenkins for Notifications plugin 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#338]
Create a jenkins build configuration that pulls the dev branch to eypd-cert, and the master branch to eypd prod.

**Comment by alexpflores** [comment]
Build jobs created, configured, tested.
`cert-eypd-notify`
`prod-eypd-notify`

**Comment by bdolor** [comment]
renamed jobs to reflect name of plugin, added `--exclude` parameters to prevent uploading of unnecessary directories.

**Comment by bdolor** [comment]
added missing webhook to github configuration

**Comment by bdolor** [comment]
complete
