### ISSUE TITLE
Notifications options page: Option to choose the time of day the notifications get sent.

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#342]
As an administrator I wish to clearly observe and understand the time, the content and the recipients of a notification email sent to all users of EYPD. 

Currently, the WP Notify Dashboard does not provide enough specific information to the administrator to determine when and what has been sent and who has received this information. 

**Steps to Resolve Issue**
Add some clarifying descriptions functions to improve understanding of an activated notification. 
This includes:
**On the General Tab:**
- [ ] - Removing "Email Notifications" selection box
- [ ] - Editing "Notification Delayed Start (Hours)" to describe a specific date and time
**On the Logs Tab:** 
- [ ] - Clarifying the "Last Build" description with more context as to what has been built
- [ ] - Adding a date and time stamp to the emails that have been sent 
- [ ] - Clarifying the description "Number of attempts (20 emails at a time):" to "Number of batches sent"
**On a new Tab:** 
- [ ] Create a start and stop function on a separate tab that specifically indicates that the notification has been activated.

**Comment by kathreenriel** [comment]
Number of hours drop-down was created to specify a specific time. But tried it this morning for a second time and I don't think it works.

**Comment by bdolor** [comment]
I received an email from the plugin this morning at 9:28am

**Comment by kathreenriel** [comment]
I selected the notifications to be delayed for 17 hours (to happen after the build scheduled for tomorrow) but the notification was sent within minutes.

**Comment by bdolor** [comment]
ready for validation via https://github.com/BCcampus/custom-wp-notify/pull/45

**Comment by kathreenriel** [comment]
Reviewed this and will look for results at 1:58 :)

**Comment by paulagaube** [comment]
@bdolor I am testing email notifications as well, and so far, so good!

Is there a way I can modify what the "{Unsubscribe}" message is? Right now the subject on the unsubscribe email is only "remove" when it sends an email to earlyyears@bccampus.ca. Could we change that subject line to "Remove me from EYPD notifications" instead?

**Comment by kathreenriel** [comment]
@paulagaube I will create a new ticket for that "remove" request

**Comment by paulagaube** [comment]
Confirmed that this features is on Prod. Have not tested with an actual outgoing message, but the plugin shows the date and time when the next scheduled message will be sent, which matches the time I chose. 
Moved to Done on Prod.

**Comment by kathreenriel** [comment]
@paulagaube let's discuss activation of this customized notification for a first scheduled notification possibly mid February.
