### ISSUE TITLE
Notifications options page: day of the week notifications get sent.

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#343]
Create an option to let the plugin admin choose what day of the week the e-mail notifications are sent (for weekly and monthly frequencies only)

**Comment by bdolor** [comment]
By delaying the start of the notification, an admin can choose what day of the week the email-notifications are sent.

![image](https://user-images.githubusercontent.com/2048170/40797111-e8c458ae-64bb-11e8-816c-a14ac0c009c4.png)

Example: Today is Thursday, and I want weekly notifications to be sent out weekly starting on Sunday at 11 am. I set the `Notification Frequency` to `weekly` and delay the notification by 72 hours.
