### ISSUE TITLE
settings page admin log/archive of emails sent out

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#344]
The goal is to verify who has been sent what email and when. 

Specifically this is an admin/dashboard page where an admin can view the status of the queue. 

- how many have been sent out and to whom. (success/fail)

**Comment by bdolor** [comment]
initial pass included in https://github.com/BCcampus/custom-wp-notify/pull/16

**Comment by kathreenriel** [comment]
This log includes a time, # of emails, and # of events. Next iteration  would be adding a recipients line and success /fail?
