### ISSUE TITLE
settings page admin dashboard to unsubscribe/subscribe 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#346]
Administrators need to have a way to manually unsubscribe or subscribe users to the events/email notification. 

- bulk add subscribe/unsubscribe feature

**Comment by alex-418** [comment]
Happy to report this feature is now ready for validation. Here's a link to this new Subscription Management tab: https://eypd.bccampus.ca/wp-admin/options-general.php?page=custom-wp-notify&tab=manage-users

**Comment by kathreenriel** [comment]
This is a great start to subscription management. In the retrospective meeting on March 29 we discussed adding more columns so that there was three columns in the "Subscribed"  "Not Subscribed" boxes. This would be login name, first name, last name.
