### ISSUE TITLE
options page nonce and other default security measures

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#348]
Input validation, sanitation and page reference verification are things that need to be implemented with user input.

**Comment by bdolor** [comment]
this has mostly been taken care of by https://github.com/BCcampus/custom-wp-notify/commit/c3aafddfa2857084e568a6e9d40604fd920faf7d

**Comment by bdolor** [comment]
@alex-418  This shows a perpetual error now 
![image](https://user-images.githubusercontent.com/2048170/37742506-261ff440-2d23-11e8-8172-2ce71721abfd.png)

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/custom-wp-notify/commit/81a4217b09a51a28d78b73008617a74f9c979914

**Comment by bdolor** [comment]
cleared cache and all is well!
