### ISSUE TITLE
Allow Organizers to see past events and duplicate past events

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#349]
Organizers cannot currently see their "past" events in their myEYPD page, which means they can't duplicate a past event.

Since some Organizers offer events/courses at regular intervals (e.g., the same course is offered three times a year), they would like to be able to duplicate the past event and then update the dates and location for the future event (all other content remains the same).

As an Admin, we can duplicate a past event, but an Organizer cannot.

**Comment by kathreenriel** [comment]
This was started as an Archive issue look  at documentation in Issue #85

**Comment by paulagaube** [comment]
@kathreenriel If we have some time left on this sprint... this issue would be a good one to revisit. :)

**Comment by mandily-p** [comment]
👍

**Comment by dshaykewich** [comment]
Won't fix.
