### ISSUE TITLE
Add Help/FAQ page(s) to Wordpress

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#350]
Evaluate current FAQs
Update FAQs

Brad suggested adding a plug-in - Ultimate FAQ

**Comment by paulagaube** [comment]
This is a Work in Progress: I disabled the Ultimate FAQ plugin as it wasn't displaying answers by category. Installed Arconix FAQ plugin, which allows an FAQ to be displayed on the Help page if the answer has been tagged with a "Group" (category). Here is the URL:  https://eypd.bccampus.ca/help/

**Comment by mandily-p** [comment]
I'm curious to know why we need a plugin for FAQ's? Ideally this is just a regular page with headings for the question and the answer as a paragraph underneath. 

Accordions are great for hiding information when there's too much. But I generally find them to be a bandaid to the bigger problem - which is that there's too much information. Here's some more words that I didn't write, but that I totally agree with:

Forcing people to click on headings one at a time to display full content can be cumbersome, especially if there are many topics on the list that individuals care about. If people need to open the majority of subtopics to have their questions answered or to get the full story then an accordion is not the way to go. In this situation, it’s better to expose all the content at once. It is easier to scroll down the page than to decide which heading to click on. (Every single decision, no matter how minor or how easy, adds cognitive load.) The experience feels less fragmented with fewer attention switches.

Accordions increase interaction cost. Readers treat clicks like currency: they don’t mind spending it if the click is worthwhile and has value. However, resentment ensues when a click is considered a wasted effort; it doesn’t take many wasted clicks to escalate people’s reaction to full-blown defiance. Acquiring click targets, such as links and buttons, and waiting for content to appear requires work and wastes precious time that users don’t want to give.

Hiding content behind navigation diminishes people’s awareness of it. An extra step is required to see the information. Headings and titles must be descriptive and enticing enough to motivate people to “spend” clicks on them. When content is hidden, people might ignore information. Accessibility is an important consideration. Pages and widgets must be coded with accessibility in mind, which is an added development effort. In contrast, plain text is inherently accessible (though it can definitely be too complicated for disabled users to understand, but that’s a standard writing issue which you should consider in any case.)

Printing is another consideration. Accordions are often not well suited for printing documents and require people to print snippets of content at a time. Make sure to optimize your pages for printing.

**Comment by kathreenriel** [comment]
Some good points here @mandily-p 
@paulagaube I'm also wondering about 2 things:
1. We will be able to link instructions on other pages  to a specific question? For example the words Internet domain on the sign up page could be linked to the question "What is an Internet domain?"
2. Is there a search feature so that users can search for support by keyword on this Help page?

**Comment by mandily-p** [comment]
1 - I would suggest not using any language on a page that any user would have to visit a FAQ to understand. :) 

2 - I think help is a useful tool when there's a lot of content to shift through, but in this case, there's a very short list that would be easily scannable as just a list.

**Comment by kathreenriel** [comment]
The new FAQ plugin has been put on the production site. There are potential modifications that could be applied. Let's evaluate traffic patterns to this page and conduct some user testing to determine if further modifications warrant another plugin.

**Comment by paulagaube** [comment]
Tidying up. This issue is done and I will close. We are currently using the Arconix FAQ plugin.
