### ISSUE TITLE
Change the unsubscribe url to a mailto

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#364]
The unsubscribe link should be a mailto link to allow the recipient of the email to send an unsubscribe request to an e-mail address.

kriel 9:11 AM
Instead of setting up an "unsubscribe" page and writing additional code. How about making the unsubscribe link open an email to earlyyears@bccampus.ca? All senders of commercial email must provide a working opt-out mechanism for email recipients to unsubscribe from: a functioning URL or hyper link. The actual opt-out process can be as straight forward as sending a reply with the word “remove” in the subject line to a more complicated procedure where the link goes to a landing page (preference page) with subscriber options such as changing the frequency of emails.

https://mailing-list-services.com/eml/unsubscribe-compliance-rules-for-email/

**Comment by alex-418** [comment]
Ready for validation, replaced the `Unsubscribe URL` option for `Unsubscribe e-mail`, automated the generation of the mailto link (used the placeholder text that was in the template on cert), and using `sanitize_email()` along with `is_mail()` to make sure the e-mail address entered is actually valid.

**Comment by kathreenriel** [comment]
A slight change in the words - add the word "us" to the instructions

To unsubscribe from these updates, please send us an email

**Comment by bdolor** [comment]
closing to be covered in separate issue
