### ISSUE TITLE
Add more information to subscription section 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#366]
Add more user information to subscribed and unsubscribe boxes to quickly identify users. 
Add a search field to find specific users in the subscribed and unsubscribe box. 

<img width="753" alt="subscription box" src="https://user-images.githubusercontent.com/16693738/38437573-bdbe5c40-398c-11e8-8810-afd23a3e25dd.png">

**Comment by kathreenriel** [comment]
Priorities:
1. 1 more column of information (preferably email) 
2. Search

**Comment by bdolor** [comment]
Addressed in https://github.com/BCcampus/custom-wp-notify/pull/20, ready for validation
