### ISSUE TITLE
Extend email field to send test email to multiple recipients

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#367]
<img width="596" alt="screen shot 2018-04-06 at 11 28 56 am" src="https://user-images.githubusercontent.com/16693738/38437932-d7bd8ed0-398d-11e8-9d39-c6108b51ff89.png">

1. Extend email window in order to include more than one email. 
2. Change words for action link to send email
3. Clear the email address field once email test is sent.

**Comment by kathreenriel** [comment]
@bdolor I tried sending test emails (single and multiple) to three email addresses and they're not coming through.

**Comment by alex-418** [comment]
@kathreenriel Any error message, or does it say it's been successfully sent?

**Comment by bdolor** [comment]
Looking into that now, thanks Kathreen

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/custom-wp-notify/commit/f6eb320ee0498d2ea0958c38ab71bb00d1b51e56

**Comment by kathreenriel** [comment]
Ooo working now! Great!

**Comment by kathreenriel** [comment]
Behaviour:
Incorrect email address is typed in the address field user clicks on Send Test Email
Result: email address disappears
No confirmation that email is sent. 

Correct email address is typed in the address field user clicks on Sent Test Email
Result: email address disappears
**Same result/display as incorrect email address?**

Multiple email addresses are typed in address field, one incorrect email, user clicks on Send Test Email
Result: Only correct email addresses appear and remain in address field but **after** the user clicks on Send Test Email...does the user click on Sent Test Email again?

I think there needs to be more clarity about correcting incorrect emails some confirmation about the success or failure of the sent emails.

**Comment by bdolor** [comment]
updated error messages via https://github.com/BCcampus/custom-wp-notify/commit/6186975a174799b68d1a19169c9d3a9362b57226

**Comment by kathreenriel** [comment]
Awesome.
