### ISSUE TITLE
Provide day and time options for sending out notifications

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#370]
<img width="882" alt="screen shot 2018-04-06 at 11 51 26 am" src="https://user-images.githubusercontent.com/16693738/38439062-2f23d528-3991-11e8-84d3-ad99bcd7bb7d.png">

**Comment by bdolor** [comment]
will investigate if this is possible, what the limitations are with wp-cron

**Comment by bdolor** [comment]
added a start delay: 

![image](https://user-images.githubusercontent.com/2048170/38747394-9a1a9eca-3eff-11e8-8a9d-d4207383b312.png)
