### ISSUE TITLE
Investigate how to make the notifications plugin PWA compliant

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#371]
Potential Product: 
The icon on the mobile device will have a 'red' dot to indicate notifications.

**Comment by alex-418** [comment]
Looks like we might be too early to the party on this one... bleeding edge! Please see below for details.

**PWA Notifications:**
Currently very limited Browser/OS compatibility and experimental. This means notifications would only work for the supported Browser/Device combinations (no iOS/Safari support). Please see the [compatibility chart](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification#Browser_compatibility) and [showNotification()](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification) for the details.

**Badging API:** 
As for the "red dot" to indicate new notifications on mobile device, that would be achieved through the yet to be released [badging API](https://developers.google.com/web/updates/2018/12/badging-api). 

The Badging API defines a more subtle notification mechanism than [Web Notifications](https://developers.google.com/web/fundamentals/codelabs/push-notifications/), allowing Web applications that have been installed on the device (e.g. through a manifest file) to set an application-wide badge, typically shown next to the application's icon on the home screen, to notify the user when the state of the application has changed and might require their attention (e.g. a new message has arrived).

See the [explainer](https://github.com/WICG/badging/blob/master/explainer.md) and [spec draft](url) for more details. W3C also has it on their [Application Lifecycle Roadmap](https://www.w3.org/Mobile/roadmap/lifecycle.html) updated in December.

**Comment by alex-418** [comment]
- Investigate how the Badging API would be triggered 
- Investigate how we can determine if we can track if people have added EYPD to their home screen
- Investigate what devices people are using and their compatibility with these features

**Comment by bdolor** [comment]
would like to suggest preferring the PushAPI over Badging if the data for desktop users shows a majority

**Comment by kathreenriel** [comment]
Here some data about user tools/browsers. Almost 50% of the visitors use Chrome the rest are distributed among other browser
 
In 2018 until yesterday there were 16,523 visits
7,478 use Chrome/Chrome Mobile
893 use Firefox
889 use Edge 

![browsers](https://user-images.githubusercontent.com/16693738/51270981-31483b80-197b-11e9-8244-091a63f6a109.jpg)

**Comment by alex-418** [comment]
Thanks @bdolor agree there could be a good use case for Push Notifications as well, @kathreenriel [Here's a demo](https://web-push-book.gauntface.com/demos/notification-examples/) of the notifications he's referring to. That's what the PWA Notifications section in my [comment](https://github.com/BCcampus/eypd/issues/371#issuecomment-454581532) above talks about. Safari on both desktop/mobile would not be able to see these at this time. And here's the definition of what they mean by [experimental](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Conventions_definitions#Experimental).

Here's a Summary of the two

**Push Notifications:**
- Doesn't depend on the user adding EYPD to their Home Screen (shown to users with a [compatible browser](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification#Browser_compatibility)) 
- The browser Prompts to allow notifications from EYPD
- Good retention tool if used correctly, but there's also data suggesting users may find push notifications annoying or don't allow them at all in the first place (how could we test/verify this?)

**The Badging API:**
- Defines a more subtle notification mechanism than Push Notifications
- Doesn't require or prompt the user for any permissions
- Depends on adding EYPD to their Homescreen (how many people are actually doing this?)
- Not yet released (soon?)

**Comment by kathreenriel** [comment]
I don't know how many people add EYPD to their Homescreen but the stats indicate that 5,030 people last year accessed EYPD through direct entry.

**Comment by kathreenriel** [comment]
Given that almost 50% of the traffic is from Chrome I think it is reasonable to pursue development of push notifications. I like the looks of this one but I don't have and understanding of which type of push notification would be most effective. 
<img width="623" alt="screen shot 2019-01-16 at 10 59 16 am" src="https://user-images.githubusercontent.com/16693738/51272213-5ee2b400-197e-11e9-8fd6-09f405e0f203.png">

**Comment by alex-418** [comment]
> I don't know how many people add EYPD to their Homescreen but the stats indicate that 5,030 people last year accessed EYPD through direct entry.

I don't imagine it would be very many right now... we could look into prompting them so they know they are actually able to do this. [Here's](https://developers.google.com/web/fundamentals/app-install-banners/) what that would look like. Just not sure how we'd be able to track this.

**Comment by alex-418** [comment]
> Given that almost 50% of the traffic is from Chrome I think it is reasonable to pursue development of push notifications. I like the looks of this one but I don't have an understanding of which type of push notification would be most effective.
> <img alt="screen shot 2019-01-16 at 10 59 16 am" width="623" src="https://user-images.githubusercontent.com/16693738/51272213-5ee2b400-197e-11e9-8fd6-09f405e0f203.png">

UX/Marketing expert would really nice right about now lol. Looks like we might be able to get it done for Safari as well... Apple independently created their own push notifications for their web browser! Please see [Safari Push Notifications.](https://developer.apple.com/notifications/safari-push-notifications/) The implementation video is 46 minutes long, so I haven't watched it... but good to know there's an option.

**Comment by kathreenriel** [comment]
The "Add To Homescreen" prompt is already there...I think
I just observed Mirjam going to earlyyearsbc.ca and a message "Add EYPD to homescreen" appeared at the bottom of her phone on the homepage. The rest of us (except for George) are iPhone users so I can' verify.

**Comment by alex-418** [comment]
Started down the road of figuring out exactly what would trigger push notifications. After some research, discovered that for push notifications to be effective in increasing engagement and retention, they need to be tailored for each role, otherwise we risk having the opposite effect (people turn them off, or get annoyed and don't come back). The notification should provide targeted, actionable, and useful information for the specific user at the right time with an appropriate frequency (so we don't spam them with notifications). 

Below is a diagram I created to provide examples of what could trigger these notifications based on existing functionality of the site for each role, and what the contents of these notification could be: 
![eypd_push_notifications](https://user-images.githubusercontent.com/17072191/51289085-bea78200-19b3-11e9-8a54-77cd85d0937f.png)

The triggers are by no means an exhaustive list, but it provides an indication what we could accomplish.

**Comment by kathreenriel** [comment]
I think the most relevant notification triggers right now would be for Learners who have signed up for an account but not used any/all the features of the myEYPD page or have not interacted with the myEYPD page for some time. (Drip Campaign?)

Types Notifications sent to Learners:
- Keep track of when your certificate expires!
- Your certificate expired! Do you have 40 credits?
- You have ## hours left find upcoming training events based on your interest
- You have % of this category find more training events in this category
- Looking for the right fit? Update your professional interests to find just the right training.

**Comment by alex-418** [comment]
Thanks @kathreenriel updated the graphic to reflect most of the ones you've added

![eypd_push](https://user-images.githubusercontent.com/17072191/51350056-0a156b00-1a5c-11e9-8b21-f6c44c024e7f.png)

**Comment by alex-418** [comment]
Meeting summary: We decided on starting with a notification for Learners and Organizers based on the certification expiry. Proceeding with creating the required issues on the backlog that will be needed to implement that specific notification.

**Comment by alex-418** [comment]
During today's standup we identified the need for an options page to allow users to configure and setup push notifications.

**Comment by alex-418** [comment]
Also including https://github.com/BCcampus/eypd/issues/647 to ensure we have enough information to develop /proceed with a well thought out implementation.

**Comment by dshaykewich** [comment]
Won't fix.
