### ISSUE TITLE
Change the logic of event notifications  from upcoming events to recently posted events.

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#373]
It makes more sense to notify people using the recently posted events logic - not upcoming events.

**Comment by bdolor** [comment]
The most recent email sent out by the system should verify that this is working as expected
![image](https://user-images.githubusercontent.com/2048170/38691880-f58aadbe-3e36-11e8-9209-27fee60d8bec.png)

![image](https://user-images.githubusercontent.com/2048170/38691891-00205576-3e37-11e8-870e-9b6d7ae0c313.png)

**Comment by paulagaube** [comment]
Yes, thank you, this is great.
