### ISSUE TITLE
Search, sort or filter

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#375]
Create a mechanism that allows administrators  to sort or filter users in the subscribed or not subscribed window.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/custom-wp-notify/pull/20. (Will move to validating once merged) 

![filter](https://user-images.githubusercontent.com/17072191/38528959-f5b9c2b0-3c16-11e8-8080-d2106f900caa.png)

**Comment by bdolor** [comment]
@paulagaube @kathreenriel ready for validation

**Comment by kathreenriel** [comment]
I Liiiiiiike it! Way to go you guys!!

**Comment by paulagaube** [comment]
I like how this works as well. Filter by email or username... seems to work quite well! 

Thumbs up from me.
