### ISSUE TITLE
add ability to track events from links in emails

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#376]
### Description 

Knowing how successful engagement is, may be tied to seeing if people are actually clicking on the links in the email.

**Expected behaviour** 

When people click on a link in an email template, pass a parameter or something unique that can be registered with Piwik.

**Actual behaviour** 

The links in email templates are not tracked and we won't know if these efforts have been successful to encourage users to return to the site.

**Comment by kathreenriel** [comment]
@bdolor @alex-418 Do I need to create an 'event' now in p-wik to validate this? Need some direction on how to validate this

**Comment by bdolor** [comment]
Certification server likely isn't tied to piwik/matomo. You can check that the value of the links in the email template are modified after enabling the setting: 

![image](https://user-images.githubusercontent.com/2048170/38638061-ddd6e918-3d81-11e8-88d5-c28f5b986f8b.png)

**Comment by alex-418** [comment]
@kathreenriel no need to do anything besides visit piwik, and find the campaign (associated with the parameter you choose to add in the settings). This will only exist after one of the links has been clicked. Let me know if you have any more questions on how to test, this, here are the documents for more info: https://matomo.org/docs/tracking-campaigns/

**Comment by kathreenriel** [comment]
@alex-418 Okay thanks I'll look at the documentation
