### ISSUE TITLE
New information around what appears in the 'Log' dashboard

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#377]
### Description 

In order to respond to the potential for user concerns that they didn't receive an email, create a list of email addresses that have *not* been sent and *have* been sent. 

**Expected behaviour** 

An archive/list of email addresses that have successfully been sent an email. The limitation for how long the archive list is the most recently sent batch

**Actual behaviour** 

No current archiving mechanism.

**Comment by kathreenriel** [comment]
Check what 

"Number of published events:"
--
means
