### ISSUE TITLE
Show difference between UTC and local time on Logs page

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#378]
### Description 

Expanded from issue #370 
In the Custom WP Notify plug-in, show the time difference between UTC/GMT and Pacific Time (local time). E.g., We are here, on the west coast of North America, in Pacific Time, currently Pacific Daylight Savings time. UTC time is 7 or 8 hours ahead of us.

**Expected behaviour** 

Allow a user or Admin to specify the local time zone and show the difference between local time and UTC/GMT. 
OR:
Add some explanatory text to the Logs page to show the time difference between UTC and our local BC time.

For example:
PDT = UTC/GMT -7 hours
PST = UTC/GMT -8 hours

**Actual behaviour** 

"Last build:" and "Next scheduled:" time is displayed as UTC time, which is seven hours in the future: **April 13, 2018 9:25 PM (UTC)**

- EYPD: Version: April 13, 2:30PM PST on eypd.bccampus.ca in Plugin Custom WP Notify

**Comment by kathreenriel** [comment]
Thanks @paulagaube we'll put this in the Sprint round after the Advisory Group reviews plugin
