### ISSUE TITLE
Events Attended Accordian

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#380]
### Description 

Limit the number of Event's Attended that are displayed to 5, and add pagination.

**Expected behavior** 

If there's more than 5 events, a pagination menu appears at the bottom of the list, so I can view more of the events I've attended. They will be sorted by the most recent events attended.

**Comment by alex-418** [comment]
@kathreenriel  @paulagaube  @bdolor 
Moving back to sprint backlog for discussion. Pagination sees both the future/past events list as one list instead of two separate event lists. So it's not possible to paginate only the past events without affecting the entire list of future/past events. 

Possible Solutions to explore:
- Custom Pagination (on $past_ids only). 
- Build the past and future lists independently and hope pagination behaves accordingly then.
- Add according style dropdown to the past and future event list (easiest).

**Comment by kathreenriel** [comment]
@alex-418 thank you for this investigation. I'll consider these options you have presented.

**Comment by kathreenriel** [comment]
Go with Accordian style dropdown

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/eypd/pull/390

**Comment by kathreenriel** [comment]
This looks good on my desktop and phone Firefox, Safari, Chrome. @paulagaube would you check this on beloved IE?

**Comment by kathreenriel** [comment]
Looked again at this @paulagaube looked in IE... all behaves at it should.
