### ISSUE TITLE
professional interests brought into myEYPD page

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#382]
### Description 

We would like to give both organizers and learners the ability to modify their 'professional interests' on the myEYPD page. 

**Expected behaviour** 

we are creating a new section on the myEYPD place that displays the current user's professional development interests. We'd like them to be able to update/edit which categories they have selected without leaving that page. 

**Actual behaviour** 

The edit my profile page and myEYPD page are separate.

**Comment by bdolor** [comment]
blocked by #379

**Comment by kathreenriel** [comment]
@bdolor Two ideas:

1. Are "categories" an element that may be implemented better on myEYPD if they could be modified by admin?
2. We're waiting to format these categories, alphabetically and in columns correct?

**Comment by kathreenriel** [comment]
@bdolor just tested selecting categories and think clicking on submit in Firefox. When I do this in FF instead of displaying the word "saved" the window jumps so that one views the top of the page.

**Comment by paulagaube** [comment]
I know this is still in "open" and not validating column yet, but there is a typo that can be fixed...
![myeypd-categories-new-user](https://user-images.githubusercontent.com/26391359/39214301-da85c616-47c8-11e8-8571-c0825f49bfdf.jpg)

**Comment by bdolor** [comment]
typo fixed via https://github.com/BCcampus/custom-wp-notify/commit/0484f3b7748571d50c23de2a30630064cd0283af

cannot recreate error message. please clear browser cache and try again.

**Comment by bdolor** [comment]
Firefox issue corrected via https://github.com/BCcampus/custom-wp-notify/commit/f3b34c66af7c8d5f3edef6d4cff8b5899343abd3

**Comment by paulagaube** [comment]
Thanks, @bdolor for fixing the typo. I cleared my cache and tried a different browser and the categories saved. I want to try again to break this after creating a new user.

**Comment by kathreenriel** [comment]
@paulagaube I created a new user, added the categories in myEYPD, saved, recommended categories. It all seems to work as expected on Chrome now going to Firefox

**Comment by kathreenriel** [comment]
Looks good in Firefox...as a Learner why did I leave Firefox?

**Comment by kathreenriel** [comment]
Isn't that because the new user needs to select professional interests now on myEYPD? So the message should read, "Select professional interests on myEYPD" to see upcoming train events based on your interests.".... or something like this

**Comment by kathreenriel** [comment]
Added new Organizer using, Chrome, Safari and Firefox cannot replicate this issue.
