### ISSUE TITLE
web page that displays a curated list of personalized events based on categories selected

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#383]
### Description 

In order to encourage learners to be aware of and sign up for events that are related to their interests, we need to build a page that presents events, grouped by category based on the personal interests (categories) that they have selected. 

**Expected behaviour** 

Learner is signed in, Learner is on myEYPD page, they click a link that takes them to a page with this curated list of events. 

**Actual behaviour** 

No such personalized page exists.

**Comment by bdolor** [comment]
@alex-418 @kathreenriel @paulagaube Two separate data sets related to personal interests exist in the database tables of two separate plugins. The sign up form puts personal interests into the buddypress `bp_x profile_data` table and the events manager plugin creates event categories using default WP taxonomy terms. The source of truth for event categories are the taxonomy terms in the database table `wp_terms` and would be preferable to rely on, though those categories have no connection, except in name only, to the professional interest categories that a user selects on sign up. Maintaining parity between these two datasets is problematic. 

Thoughts?

**Comment by kathreenriel** [comment]
Thinking....

**Comment by kathreenriel** [comment]
How about if all the categories appear on the myEYPD dashboard by default. But only those categories selected after attending a specific training event have a number colour associated with them?

Or how about a group of categories that appear as a word cloud with those categories most attended appearing larger than the others ?
<img width="644" alt="screen shot 2018-04-17 at 1 35 11 pm" src="https://user-images.githubusercontent.com/16693738/38895588-4ad49d9a-4245-11e8-909a-afc2332123f3.png">

That's all I got...I think I need a donut:)

**Comment by kathreenriel** [comment]
Along with word cloud when hovered over # of hours associated with category appears over word

**Comment by bdolor** [comment]
Sorry, I left that question open ended but intended only to highlight that the two datasets means we must divorce ourselves from any data a user submitted in the sign up form relating to personal interests.

**Comment by paulagaube** [comment]
How can we keep only one of those datasets? Is it possible to eliminate the professional interests from Buddy Press, or populate the Buddy Press data from the events manager? I think we would want to keep the Buddy Press dataset if possible. Hmmm. ... also thinking.

**Comment by alex-418** [comment]
This is ready for validation on cert. Here's a screenshot of what you should see in your MyEYPD and those preferences should be saved when you hit the submit button. 

![prefs](https://user-images.githubusercontent.com/17072191/39076733-152a3a3c-44b2-11e8-8b07-c7e3a05b6a2f.png)

**Comment by kathreenriel** [comment]
Logged in as Organizer:
Subscribe to Event Notifications:
When I select  Subscribe To Notifications:

- An error message appears
- When I log out and log in again the Subscribe to Notifications is not selected

Submit Button:

- When I click on submit there is an error message
- When I log out then log in again the selected categories remain selected from the previous session. 
- 

<img width="1107" alt="error on my myeypdpage" src="https://user-images.githubusercontent.com/16693738/39097134-241816d4-460d-11e8-992e-bc5bba789815.png">

**Comment by kathreenriel** [comment]
Suggested changes to the design/appearance of the categories illustrated below:
<img width="607" alt="screen shot 2018-04-22 at 9 29 32 am" src="https://user-images.githubusercontent.com/16693738/39097334-cb886a84-460f-11e8-957f-ba42f0d5c844.png">

**Comment by bdolor** [comment]
errors resolved via https://github.com/BCcampus/custom-wp-notify/commit/060d943695b293338866dc0f996cb472c73a4fd8

**Comment by alex-418** [comment]
@kathreenriel Clearing the browsers cache resolved the first error for me.

**Comment by bdolor** [comment]
- add a link on the left nav that says 'My Professional Interests'
- add a link in the body of the category selection area that says 'Recommend Events'
- create a Recommended Events page that has header for Category and an unordered list of events.

**Comment by bdolor** [comment]
ready for validation via https://github.com/BCcampus/eypd/pull/389

**Comment by kathreenriel** [comment]
Wow, this is really sweet - better than an Empire donut. @paulagaube would you test this too.

**Comment by kathreenriel** [comment]
In Firefox 59.0.02 for Mac when I select the categories and click on Submit the selections do not "stick" and they boxes I checked become unchecked. This error works in reverse too. Cannot deselect boxes either.

**Comment by kathreenriel** [comment]
All selections work correctly in Firefox on my phone....hmmmm...

**Comment by alex-418** [comment]
@kathreenriel @bdolor Found the issue and fixed. Even though Brad pushed to the dev branch in github (cert) https://github.com/bccampus/custom-wp-notify/commit/f3b34c66af7c8d5f3edef6d4cff8b5899343abd3 to fix these types of issues in FF, it never actually made it onto cert. I compared the JS file in dev branch, with cert website, and could see the fix was missing. Jumped into Jenkins and confirmed this commit never triggered a build. So building manually got this commit into cert, fixing the problem. Please test, should be okay now.

**Comment by kathreenriel** [comment]
All selections and deselections are saved as expected and checkmarks now "stick" in the checkboxes as expected. Tested in Firefox, Safari, Chrome,  - Mac  and Safari, Firefox iPhone
