### ISSUE TITLE
Not Subscribed list not populated for existing users

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#385]
### Description 

The "Not Subscribed" list of the "Subscription Management" tab in the Custom WP Notify options page is not populated. 

**Expected behaviour** 

All users who aren't opted in should be on the Not Subscribed list.

**Actual behavior** 

No users are on the list. To get a user on the "Not Subscribed" list, they first have to opt-in, and then opt-out to appear on the not subscribed list.

### System Information

- EYPD: earlyyearsbc.ca

**Comment by alex-418** [comment]
@kathreenriel FYI, this would probably need to be resolved before we send out notifications.

**Comment by bdolor** [comment]
duplicate issue, addressed in https://github.com/BCcampus/custom-wp-notify/issues/30
