### ISSUE TITLE
Remove professional interests from signup form

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#388]
Professional interests are no longer needed on the signup form, and will live in the myEYPD page instead, so we need to remove the BP extended profile fields from the signup form.

**Comment by alex-418** [comment]
@kathreenriel @paulagaube Done, no code required. I was able to remove the professional interests by going to `Users -> Profile Fields` and deleting that profile field. You can see it doesn't exist any longer on the cert signup form. This will need to happen on prod when you're ready to implement this change.

**Comment by kathreenriel** [comment]
Right. I know the location. Will complete this once we move to prod.

**Comment by kathreenriel** [comment]
Shorter form. looks good

**Comment by paulagaube** [comment]
Yes, looks good to me too.  Confirmed that the Buddy Press Extended Profile is shorter.
