### ISSUE TITLE
myEYPD page: My Professional Interests List

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#396]
Add a "Select All" option at the end of the professional interests list.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/custom-wp-notify/pull/37

**Comment by kathreenriel** [comment]
The "select all" option does not work on Chrome on my iPhone 7
![image-1](https://user-images.githubusercontent.com/16693738/40866811-ad39f902-65b4-11e8-8ae0-72da8eea659e.jpg)

**Comment by kathreenriel** [comment]
To revisions needed:

1. If user manually selects all the interests, the select all box should automatically be selected.
2. If user clicks the box beside "select all" and then deselects one or more professional interests then the "select all" box should automatically be deselected.

**Comment by kathreenriel** [comment]
This is related to #457
