### ISSUE TITLE
myEYPD Page: My Professional Interests

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#398]
Currently, the list under My Professional Interests is horizontally displayed. Change the format of the categories to be columns in alphabetical order. 
<img width="618" alt="screen shot 2018-04-26 at 10 10 00 am" src="https://user-images.githubusercontent.com/16693738/39320866-37a9f548-493a-11e8-9894-eef7c174145f.png">

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/custom-wp-notify/pull/35
