### ISSUE TITLE
Create a user forum for Appetite to Play

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#400]
### Description 

Create a user forum for Organizers (and subscribers?) to discuss Appetite to Play on the EYPD Certification site. 

**Expected behaviour** 

Logged-in users (editors/contributors or subscribers/learners) can join the discussion group/forum we create to discuss the Appetite to Play interactive workshop.

Buddy Press groups will be used to create the Appetite to Play group.

**Comment by paulagaube** [comment]
Created this group using my Admin account. 
Invited a number of our test users on EYPD. 
Added the first post about Healthy Eating.

**Comment by bdolor** [comment]
@kathreenriel - this has already been created by Paula https://eypd.bccampus.ca/groups-2/appetite-to-play/forum/
