### ISSUE TITLE
Add an Event that doesn't have a start or end date

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#403]
### Description 

An Organizer would like to be able to add an online, self-directed course that has no fixed start or end date as an Event. 

This could be an online course a learner takes where credit is given at the end of the completed course. The credited hours would count toward EYPD hours, but the course is self-directed and not time-limited.

**Expected behaviour** 

Organizer enters the Event details, but fixed start and end dates are not required.

**Actual behaviour** 

A start and end date is needed when creating an event to be posted.

###Considerations

How could we handle these types of "online" courses?
If no start or end date, how will these events appear on the calendar or map?
What will the location be? Is a location required?
Could there be an option to say the course is "ongoing" or a "fixed length" or something like that, but not related to fixed dates?

**Comment by kathreenriel** [comment]
This is related to #557 closing this issue
