### ISSUE TITLE
Wishlist: Share information about community events (not from Organizers)

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#404]
### Description 

Wishlist item:

We have received a number of requests from learners/users in the field who wish to share their event/website/expertise with us. Some have asked if we could share their information on a blog. While these aren't "sanctioned" events, many events could be considered community service announcements (and not just advertising). 
 
**Expected behaviour** 

Could we explore adding a community bulletin board, blog, or similar feature to the site's home page? 
Maybe only people who have created an account can post in the bulletin board area.

Or maybe add an RSS Twitter feed that shows certain hashtags when they pop up online. e.g., #eypdonline

**Advantages**
Adds variety to the site and has potential to keep the site interesting and current (encouraging more return visits).

**Disadvantages**
Public information needs to be monitored and/or moderated.
A Twitter feed may be harder to monitor than posts by logged in learners.

**Actual behaviour** 

The only way we share a public events is if someone requests this directly; then the information is shared through the static area at the bottom of the home page, under the heading "Explore the professional learning showcase".

**Comment by dshaykewich** [comment]
Won't fix.
