### ISSUE TITLE
myEYPD: Heading sizes

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#405]
### Description 

There are three heading font sizes used in the design. Let's set them up so that they're more accessible to screen readers.

**Expected behaviour** 
All headings should be Roboto, regular, 1.2 line-height, #404042
The page title should be an H1 - 48px
Section titles should be H2 - 32px
Sub-section titles should be H3 - 20px
<img width="425" alt="screen shot 2018-05-16 at 2 20 20 pm" src="https://user-images.githubusercontent.com/20425828/40144683-4cf0742e-5914-11e8-9ba1-02f9cb1d2a4c.png">

**Comment by mandily-p** [comment]
The font sizes look like they were updated, but not the line-height. (An example of why unitless line-heights are preferred: https://codepen.io/pen/)

The markup needs to be edited: 
* The titles `Event summary` `Training` and `Professional Interests` are all currently set as h3's and should be h2's. 
* `Upcoming events` and `Past events` are currently set as h5's and should be h3's.

@kathreenriel Can you update the content please?

It also looks like `#item-body h3` is overriding the generic `h3` So it's appearing at a larger font size than it needs to. @bdolor Can you let me know if this is a content issue or class issue? I'm not sure how this was setup and if that id is needed on the page.
![screen shot 2018-05-30 at 2 05 48 pm](https://user-images.githubusercontent.com/20425828/40747581-95858aea-6412-11e8-833b-ff63cead1834.png)

**Comment by kathreenriel** [comment]
@mandily-p let me know the content update you're referring to

**Comment by mandily-p** [comment]
@kathreenriel The two bullet points above have the headings that need to be updated :)

**Comment by kathreenriel** [comment]
@mandily-p ahh okay - @bdolor will work on the headers

**Comment by bdolor** [comment]
- first bullet point is taken care of in https://github.com/BCcampus/eypd/pull/444
- second bullet point will be taken care of in #414
