### ISSUE TITLE
myEYPD: At a glance summary

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#407]
### Description 
Create an "at a glance summary" section at the top of the page for users to see the stats that are most relevant to them when they first visit the page.

### Expected behaviour
- Total days, completed certification hours, and certification hours needed values are displayed on page load.
- If there is 30 days or less remaining before the certification expires AND certification hours <0 Change the border and background colours to red (same opacity as the blue properties)
- Edit expiry date link: When clicked/tapped, the "Your professional certification expires in [variable] days." is replaced with a datepicker field (calendar icon displayed for added accessibility) and a save button. 
- The "completed" link should scroll the user down to the "My past events" section of the page. There should be 3em of space between the heading "Past events" and the top of the browser window.
- The "needed" link should scroll the user down to the "Event summary" section of the page. "All my training events" should be in view. There should be 3em of space between the heading "Event summary" and the top of the browser window.

### Error states/messaging
If the user tries to navigate away from the page while in the middle of editing a field, they should be prompted with a message, "Are you sure you want to leave this page? You changes will not be saved" with a "stay on this page" and "leave this page" button.

### Content
Your professional certification expires in [variable] days.
[variable]/40 certification hours completed
[40-variable] certification hours needed

### Styles
- Full width of the content area
- 1.5em padding
- 1px blue border
- 10% opacity blue bg
- Expiration message is 18px, 1.4 line height
- Edit link is 14px
- Body text is 16px, 1.4 line height

### Assumptions
- There is a blue and red colour already defined in the colour palette.
- We're reusing currently defined text colour, link inactive and hover styles
- The user has already entered their certification date

![screen shot 2018-05-18 at 10 31 08 am](https://user-images.githubusercontent.com/20425828/40249694-97c9c85e-5a88-11e8-8f26-7af034e18db8.png)

**Comment by bdolor** [comment]
- move the section from the bottom of the page to the top
- apply the CSS to the area
- hardcode the 40 hours as a value to work against 
- leave error messages for the time being.

**Comment by kathreenriel** [comment]
Currently the the words "completed" and "needed" are just italicized. They should behave as links as seen below. 

The "completed" link should scroll the user down to the "My past events" section of the page. There should be 3em of space between the heading "Past events" and the top of the browser window.

The "needed" link should scroll the user down to the "Event summary" section of the page. "All my training events" should be in view. There should be 3em of space between the heading "Event summary" and the top of the browser window.

**Comment by kathreenriel** [comment]
Running into calendar view issues in Chrome when the window is smaller than the maximum dimensions. 
<img width="1280" alt="screen shot 2018-05-29 at 12 30 53 pm" src="https://user-images.githubusercontent.com/16693738/40680914-7b0abe50-633c-11e8-9a50-26837442c8c4.png">\

**Comment by kathreenriel** [comment]
Is this suppose to happen? Currently does not. 
If there is 30 days or less remaining before the certification expires AND certification hours <0 Change the border and background colours to red (same opacity as the blue properties)

**Comment by bdolor** [comment]
Is the understanding that a suggestion to modify spacing on the headers was made in isolation of the rest of the site correct?

**Comment by kathreenriel** [comment]
Yes, my understanding is that @mandily-p only looked at the myEYPD page not the rest of the site.

**Comment by bdolor** [comment]
re: red/blue change being conditional on the value of an expiry date that may or may not be saved - I like the idea but I'm not comfortable committing to it because the expectations were set prior to understanding the limitations of the environment that we're working in.

**Comment by kathreenriel** [comment]
<img width="488" alt="screen shot 2018-05-29 at 1 59 03 pm" src="https://user-images.githubusercontent.com/16693738/40685233-8713a516-6348-11e8-9c61-45835be29253.png">

**Comment by kathreenriel** [comment]
Okay, @mandily-p please check.

**Comment by mandily-p** [comment]
I've checked and made notes in #437. How/where did you want to discuss the blue/red state change @bdolor

**Comment by bdolor** [comment]
A good time for discussion around red/blue change and other javascript dependent behaviours will be in the next sprint planning session.

**Comment by kathreenriel** [comment]
Red/blue considerations will be done after user testing.
