### ISSUE TITLE
myEYPD: Sharing events

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#409]
### Description 
A link to allow organizers to email the event URL through their desktop email client.

**Expected behaviour** 
- When the user clicks or taps on the link, a new email is created with the link in the body of the message.

**Content**
Link label: Share

Email subject line: Check out the event I'm organizing
Email body: I'm organizing an Early Years Professional Development event and I thought you'd be interested. You can [get the details on the EYPD site](link to the event page). I hope to see you there!

**Assumptions**
- We're reusing currently defined text colour, link inactive and hover styles

**Related**
- To be completed after #408

**Comment by bdolor** [comment]
sharriff plugin takes care of this. complete.
