### ISSUE TITLE
myEYPD: Event details

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#410]
### Description 
A text link to the event details page. An icon link to the event details page in edit state. Both of these redirect the user in the same window.

### Expected behaviour
- Text links to the event details page in a view state. 
- Icon link to the event details page in edit state.
- Both of these redirect the user in the same window.

## Content
Link label: [event name variable]
Icon: edit icon from fontawesome

## Assumptions
- We're reusing currently defined text colour, link inactive and hover styles.

## Blocked by
#408 - Create "My posted events" section
<img width="734" alt="screen shot 2018-05-27 at 1 04 57 pm" src="https://user-images.githubusercontent.com/20425828/40590758-5623e4ba-61b9-11e8-91e9-e23ed07b5dad.png">

**Comment by bdolor** [comment]
- leaving this for review

**Comment by mandily-p** [comment]
I'm not sure who officially has the say here, but I'm all for putting it on it's own page and moving it to a table format.

**Comment by kathreenriel** [comment]
For now I think this should all stay on the same page.
