### ISSUE TITLE
myEYPD: Professional interest suggestion

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#411]
### Description 
A form available for users that would like to make a suggestion for a new professional interest category.

### Expected behaviour
- A user can enter a maximum of 50 characters in the text field
- At least 3 characters must be entered in the text field for the user to be able to submit the form
- After the user has submitted the form, they are presented with a confirmation and thank you message for the feedback.

- Suggestion should be stored in a spreadsheet with the user's name, email address, and suggestion using Contact7. If this can't be embedded in the page, consider presenting it in a modal instead of taking the user away from the page. A notification should be sent to earlyyears@bccampus.ca when a new record has been created.

### Content
Body text: Don’t see what you’re looking for? Make a suggestion. If there’s enough interest and workshop facilitators available, we’ll update our calendar with new events.

Text field helper text: Suggest a new category
Button text: Send suggestion

Suggestion sent confirmation message: "Thanks for the suggestion!" [Send another suggestion](link to refresh this section and see the form again to send another idea)

### Styles
Text field
Can use default browser style with the exception of:
padding: .5em 1.25em .6em

Secondary button style
background: #fff
color: existing blue colour
border: 2px solid existing blue colour inside
padding: .5em 1.25em .6em

There is 1em of space between the text field and the button
(the text field is small on purpose so we don't get long winded answers)

### Blocked by
#417 Create a professional interests section

<img width="381" alt="screen shot 2018-05-28 at 1 05 35 pm" src="https://user-images.githubusercontent.com/20425828/40628127-01c29172-6278-11e8-9b69-ea9c7cb0c763.png">

**Comment by mandily-p** [comment]
@kathreenriel Can you confirm which way of collecting suggestions would be best? Via email or dumping feedback directly into a spreadsheet until you're ready to deal with it?

**Comment by kathreenriel** [comment]
Email

**Comment by alex-418** [comment]
Attempt to put this in a modal.
