### ISSUE TITLE
myEYPD: Consistent table styling

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#412]
### Description 
Create a consistent styling across all tables in the site

### Expected behaviour
- If the data contained in the table is self explanatory, do not display the table header row. Otherwise, show the table header row.
- Dates and times should not be truncated, and columns that contain them should have a minimum width declared so that dates and time don't wrap

### Styles
- Full width of the content area
- Table does not display <th> row
- Horizontal table borders are 1px, #ddd
- Text is top, left aligned
- Text is 14px, 1.4, 10px bottom margin
- Top and bottom table cell padding: 1em

### Related
#408 - Create "My posted events" section
#414 - Create "Training" section

<img width="744" alt="screen shot 2018-05-27 at 9 41 09 pm" src="https://user-images.githubusercontent.com/20425828/40597496-b8573348-61f6-11e8-8c84-43847650aefe.png">

**Comment by bdolor** [comment]
- @mandily-p will provide an option for tables with headers. 
- valign to top
- change line height
- cell padding

**Comment by mandily-p** [comment]
thead{
  border-bottom: 2px solid #979797
}
th {
  font-size: 14px;
  font-weight: bold;
  letter-spacing: .1;
  padding: same as td
}

![screen shot 2018-05-30 at 1 51 54 pm](https://user-images.githubusercontent.com/20425828/40746954-abd68c1a-6410-11e8-8606-f454395fada2.png)

**Comment by kathreenriel** [comment]
The original objective was to create a consistent style in the tables. This was achieved. I missed the change in content in the table as seen Amanda's last posted graphic. After user testing the suggested content change could be added as a separate ticket.  Also the labels were not omitted as first proposed in this ticket.
