### ISSUE TITLE
myEYPD: Event summary

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#413]
### Description 
A visual summary of the events a user has attended in the past and/or plan to attend in the future

### Expected behaviour
There are two states of this section:

1. Users that have no events
- Users that have no events should not see the select box dropdown filter. (White space should be adjusted for the removal of this)
- Users that have no events should see an additional message under the heading. 

2. Users that have at least one event

Unless noted above, both states should contain the following functionality:

**Filter dropdown**
Using the select box dropdown, users can select a customized view of:
- all events (default view)
- past events only
- current and upcoming events

**Doughnut pie graph**
- Each professional interest category in which the user has attended an event will appear as part of the graph
- in the "all events" view, there is an additional slice of the graph that represents the number of credits still needed (if applicable). 
- If the user has no events, they will see an outlined pie graph with no other categories represented.
- note that a user may complete MORE than 40 credits and the "still needed" section may not appear

**Legend**
- Each coloured section in the pie graph is represented in the same order, with a block of the same colour in the legend.
- The number of credits that a user has attended/signed up for (depending on the filtered view), followed by a dash, and then the professional interest it relates to. This information will need to be pulled from the db.

### Content
Section title: Event summary
No event text: You have no events. Please add events you're interested in attending to see a summary.
Left aligned select box label: Show

### Styles
- Full width of the content area
- Graph and legend should be grouped and centered in the content area
- 2em of space between select box and the chart
- 3em of space between chart and legend
- .5em of space between each legend colour block and it's label
- Title is H2
- Body (including link) text is 16px, 1.4 line height
- Select box dropdown can remain browser default styling
- Chart has an outer diameter of 250px and and inner "hole" diameter of 100px (this is different than the current styling)
- Chart outline is #979797 (or something similar that already exists in the colour palette if applicable)
- White colour block is outlined on the inside by #333 (or something similar that already exists in the colour palette if applicable)

### Assumptions
- We're reusing currently defined text colour, link inactive and hover styles
- We can reuse the existing colour block styles and logic for determining which interest gets which colour

Desktop mockup
<img width="687" alt="screen shot 2018-05-27 at 9 43 59 pm" src="https://user-images.githubusercontent.com/20425828/40597581-29e1995e-61f7-11e8-9735-9adfac0cfec0.png">

Mobile mockup
<img width="362" alt="screen shot 2018-05-27 at 9 44 19 pm" src="https://user-images.githubusercontent.com/20425828/40597580-29cb1c6a-61f7-11e8-9fba-536b999d3ac6.png">
<img width="639" alt="screen shot 2018-05-28 at 11 05 33 am" src="https://user-images.githubusercontent.com/20425828/40626278-620a4554-626c-11e8-9416-a0486dfa05b5.png">

**Comment by alex-418** [comment]
Skip the filters
