### ISSUE TITLE
myEYPD: Create training section

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#414]
### Description 
A detailed look at all of the upcoming, current and past events that a user has added to their profile along with functionality for their managing how they show up on their profile.

### Expected behaviour
- Subsection headers should display the number of events in brackets that are listed in this section. 
- Always show the upcoming events subsection header
- If a user has current and upcoming events, show the upcoming events table; otherwise display a prompting message to add one.
- If a user has past events, display the h3 title for past events and the expand toggle link; otherwise hide this section altogether.
- Upcoming events is ordered by soonest to latest.
- Past events is ordered by most recent to least recent

### Content
Title: Training
Paragraph for all users: Adding an event to myEYPD does not confirm your registration, nor does deleting an event cancel your registration. Visit the event page to register or cancel with the agency who posted the event.
Second paragraph addition for users that DO NOT HAVE past events: You have no events. Please add events you're interested in attending to see the details.
Subsection title: Upcoming events ([variable: row count in this section])
Subsection title: Past events ([number attended]/[row count in this section])
Default link state (collapsed): "Expand to see all past events" With right pointed caret from Font Awesome.

### Styles
- 4em of space between sections
- 3em of space between subsections
- Title is H2
- Subtitle is H3
- Body (including link) text is 16px, 1.4 line height

### Assumptions
- We're reusing currently defined text colour, link inactive and hover styles
- Table, subscription and collapse/expand functionality is handled in other tickets
- Table cell data is pulled from a db
- Table cell data can be used in other areas of the page, but it is not required
- Table styles are consistent throughout the site
- Functionality of pulling db data and displaying time, date, event name, venue, venue address, and event length is already complete/can be reused from what already exists.
- Add to iCal functionality already exists and can be reused.
- Delete functionality already exists and can be reused.

### Related
#412 myEYPD consistent table styles

### Blocking
#415  myEYPD email subscription
#416  myEYPD collapse/expand functionality

**Desktop**
<img width="761" alt="screen shot 2018-05-27 at 9 47 23 pm" src="https://user-images.githubusercontent.com/20425828/40597698-de04cb04-61f7-11e8-95ff-a686c28aefe8.png">

<img width="724" alt="screen shot 2018-05-27 at 9 49 03 pm" src="https://user-images.githubusercontent.com/20425828/40597696-ddd8c11c-61f7-11e8-9a05-39a406f136a0.png">

**Mobile**
<img width="190" alt="screen shot 2018-05-27 at 9 48 02 pm" src="https://user-images.githubusercontent.com/20425828/40597697-ddee4d16-61f7-11e8-95a9-225ba0293e51.png">

**Comment by kathreenriel** [comment]
If no upcoming training events are listed link to Professional Interests down the myEYPD page. User fills in Professional Interests to populate Recommended Events. 
User click ons "Plan to Attend" in the Recommended Events table.

**Comment by kathreenriel** [comment]
Is changing the way the summary of events attended are displayed part of this ticket?
<img width="524" alt="screen shot 2018-05-29 at 9 23 15 am" src="https://user-images.githubusercontent.com/16693738/40671943-2d4fb84c-6322-11e8-9c62-05f5883addc2.png">

**Comment by kathreenriel** [comment]
Also as referenced in #423 please insert descriptive paragraph under Training  with

"Adding an event to myEYPD does not confirm your registration, nor does deleting an event cancel your registration. To officially register for a professional development event you must contact the agency responsible for the training event."

**Comment by bdolor** [comment]
It's not clear to me either. Though we attempted to draw out the specifics in a long list of asks I think we can improve the specificity.

**Comment by kathreenriel** [comment]
I think there are 4 remaining to do's on this ticket
<img width="695" alt="screen shot 2018-05-29 at 10 13 12 am" src="https://user-images.githubusercontent.com/16693738/40674229-01aa3224-6329-11e8-9df3-4207db3efa20.png">

**Comment by kathreenriel** [comment]
@alex-418  is this ready to be validated?

**Comment by alex-418** [comment]
@kathreenriel The PR https://github.com/BCcampus/eypd/pull/455 was just merged, should be good to go (allow a few moments for changes to propagate to cert)

**Comment by alex-418** [comment]
@kathreenriel Please clear cache and try again to be sure the new JS file takes effect, and let me know the results. The only issue that should remain is the one we discussed this morning, brad has captured it at https://github.com/BCcampus/eypd/issues/457

**Comment by kathreenriel** [comment]
Checked this again in Firefox collapses and expands when user clicks on words.
