### ISSUE TITLE
[content]myEYPD: Email subscription

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#415]
### Description 
User's can sign up or unsubscribe from an automated mailing list that sends updates when new events are added that are in the categories they're interested in.

### Expected behaviour 
- Default is unticked.
- If the checkbox is ticked, the user should receive the emails that are sent out when new events are added to the site
- If the user ticks the checkbox when it was unticked at the start of the session, send an automated email to them telling them that they've subscribed
- If the checkbox is not ticked, the user should not receive any promotional emails
- If the user unticks the checkbox when it was ticked at the start of a session, send an automated email to them telling them that they've unsubscribed.
- The user should be able to click/tap the checkbox or the label to tick/untick the box.
- This selection/non-selection is saved with the user's profile

### Content
- Checkbox label: Get emails when new training opportunities are added

### Styles
- Label{ 14px, 1.4 line height, color: 4A4A4A
- Bottom margin: 1em

### Assumptions
- Confirmation emails exist for the addition to the mailing list and the removal from it.

### Related
#414 Create training section

<img width="734" alt="screen shot 2018-05-27 at 9 53 20 pm" src="https://user-images.githubusercontent.com/20425828/40597774-7060746c-61f8-11e8-90d5-c8cd0b53f4b1.png">
<img width="365" alt="screen shot 2018-05-27 at 9 53 32 pm" src="https://user-images.githubusercontent.com/20425828/40597783-7bb34556-61f8-11e8-9b13-ac81246bb619.png">

**Comment by bdolor** [comment]
- move the checkbox to the left of the words
- investigate making the label 'clickable'
- automated email confirmation is not required.

**Comment by kathreenriel** [comment]
Sweeeeet.

**Comment by kathreenriel** [comment]
@mandily-p would you check this

**Comment by mandily-p** [comment]
The `text-transform: uppercase` needs to be removed from the style please. Maybe this is a bit too picky and I do realize it's browser specific, but would it be possible to vertically align that checkbox with it's label better? It looks like there's a second lighter box underneath it. Maybe that's what's causing the misalignment.

<img width="453" alt="screen shot 2018-05-30 at 8 05 19 am" src="https://user-images.githubusercontent.com/20425828/40729049-5cd45564-63e0-11e8-996c-c94bab99e61b.png">

**Comment by mandily-p** [comment]
There should be 3em of space between this checkbox and the section under it. Not sure if that's covered by this ticket or not. I'll let you decide @bdolor

**Comment by bdolor** [comment]
I don't see that in the ticket but is likely dependent on what happens with https://github.com/BCcampus/eypd/issues/414

**Comment by kathreenriel** [comment]
This works as expected. The call to action text is not as prominent on a mobile device.
