### ISSUE TITLE
myEYPD: Collapse and expand functionality

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#416]
### Description 
Users can toggle the visibility of content using a expand/collapse link. (aka an accordion)

### Expected behaviour
- If content is collapsed, display link with right pointed caret
- If content is expanded, display link with down pointed caret, and the content that belongs under that section. 
- Content should appear to slide down, pushing the content underneath it further down the page, when it is expanded
- Content should appear to slide up, allowing content underneath it to move back up the page to fill the empty space.
- The page location should not change with the collapsing/expanding of the extra content.

### Content
Past event link when collapsed: "Expand to see all past events" With right pointed caret from Font Awesome.
Past event link when expanded: "Collapse to hide all past events" with down pointed caret from Font Awesome.

### Styles
- Link is general body/link styled
- Try a transistion time of 500ms to expand and 300ms to collapse (this may need to be tweaked)

### Assumptions
- This would be coded from scratch. (But I'm also open to using a library if it's easier)

<img width="406" alt="screen shot 2018-05-27 at 9 57 06 pm" src="https://user-images.githubusercontent.com/20425828/40597843-f33678a0-61f8-11e8-96ee-34a7006f39f9.png">
<img width="359" alt="screen shot 2018-05-27 at 9 56 47 pm" src="https://user-images.githubusercontent.com/20425828/40597844-f34c441e-61f8-11e8-910d-165de9cbc598.png">

**Comment by bdolor** [comment]
already complete!
