### ISSUE TITLE
myEYPD: Remove the separate page and create a professional interests section in myEYPD

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#417]
### Description 
A checklist of professional interests that the user can select to get recommendations for upcoming events. 

### Expected behaviour
- When a checkbox is ticked, events in that category should populate below in the "Recommended upcoming training" section in real time (a small delay may be negotiable to help load the page quicker after the user has made all of their selections)
- When a checkbox is unticked, events in that category should be removed from the "Recommended upcoming training" section in real time.
- No checkboxes are ticked by default.
- These options are saved with the user's profile

### Content
Title: Professional interests
Body text: I'm interested in learning about:
Checkbox items: List to be determined by adding to the current list on the website (with the removal of online) in addition to new ideas from Kathreen. 
Checkbox items are ordered so that similar items are next to each other. @Kathreen to provide final list.

### Styles
- Uses standard checkbox styles as what's used for the email subscription. 
- List is in two columns on desktop and one on mobile

### Assumptions
This functionality currently exists, but with user interaction to submit and refresh the page. 

### Related
#417 Create a professional interest suggestion
#415 Email subscription
#414 Create training section

<img width="381" alt="screen shot 2018-05-28 at 1 05 35 pm" src="https://user-images.githubusercontent.com/20425828/40628175-4e384786-6278-11e8-8f2a-c86916e9a0a2.png">

<img width="373" alt="screen shot 2018-05-27 at 10 00 30 pm" src="https://user-images.githubusercontent.com/20425828/40597921-7055c55c-61f9-11e8-90ad-894c788e480d.png">

**Comment by bdolor** [comment]
- depends on the outcome of #424
