### ISSUE TITLE
myEYPD: Attendance toggle

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#418]
### Description 
Users can use a toggle switch to indicate whether they attended an event they saved to their profile.

### Expected behaviour
- Toggle options include:
  - Attended (default state)
  - Did not attend
- Button should appear to slide left or right with ease, and a cross fade between button styles as it slides
- The count of "attended" state buttons should be the first number in the subsection title
- The total count of table rows should be the second number in the subsection title
- The count in the header should be live updated in the page as the user toggles switches.

### Content
True label: Attended
False label: Did not attend

### Styles
- Total toggle switch width: 10em
- Toggle button padding: null .5em
- Toggle button width: 7em
- Outside two corners of each button is rounded with a 6px radius
- Attended label: use existing green colour for the bg, #979797 for 1px inner border, #fff for text-color
- Did not attend label: #ddd for bg, #979797 for 1px inner border, #333 for text-color
- Mobile attended label: font awesome checkmark
- Mobile did not attend label: font awesome times 

### Assumptions
- The user has attended at least one event

### Related
#414 Create training section
#416 Collapse and expand functionality

<img width="197" alt="screen shot 2018-05-27 at 10 04 42 pm" src="https://user-images.githubusercontent.com/20425828/40598012-0de2976e-61fa-11e8-91f8-9cf8640db1c6.png">
<img width="98" alt="screen shot 2018-05-27 at 10 04 25 pm" src="https://user-images.githubusercontent.com/20425828/40598013-0df6ffa6-61fa-11e8-81e4-1a95d15b7b08.png">

**Comment by bdolor** [comment]
- depends on what can be 'ajax-ified'

**Comment by alex-418** [comment]
Blocked by #424

**Comment by kathreenriel** [comment]
This was investigated by Alex in #424 and current developing resources constrain this enhancement.
