### ISSUE TITLE
myEYPD: Create consistent buttons styles across the site

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#419]
### Description 
Create a consistent styling across all buttons in the site

### Expected behaviour 
Primary buttons work best for high priority/high visibility functions and preferred functions when a button is presented in a group
Secondary buttons work best for lower priority functions and less desirable functions when a button is presented in a group or by itself.

### Styles
Primary button style
background: existing blue colour
color: #fff
border: none
padding: .5em 1.25em .6em
font-size: 14px

Secondary button style
background: #fff
color: existing blue colour
border: 2px solid existing blue colour inside
padding: .5em 1.25em .6em
font-size: 14px

Primary button hover and active state:
background: darken 15%
transition: fade on hover

Secondary button hover and active state:
color & border: darken 15%
transition: fade on hover

### Related
Professional interest suggestion

<img width="686" alt="screen shot 2018-05-27 at 10 09 22 pm" src="https://user-images.githubusercontent.com/20425828/40598113-a58c4d26-61fa-11e8-8cef-78d31dc5a394.png">

**Comment by mandily-p** [comment]
I'm sorry, I swapped the top and bottom padding values. They should be: `padding: .6em 1.25em .5em;`

Can you also increase the timing on the transition to 200ms instead of 300ms please?

The save button is Helvetica Neue instead of Roboto. (Recommend events is Roboto) Can you please update the button styles so that all buttons are Roboto?
![screen shot 2018-05-30 at 1 37 16 pm](https://user-images.githubusercontent.com/20425828/40746197-98490ea4-640e-11e8-964b-e6b233e72886.png)

**Comment by alex-418** [comment]
Completed via https://github.com/bccampus/eypd/commit/81c77cc4e54e6e21a0c1242794cc1ef5602e81d6
