### ISSUE TITLE
myEYPD: Create recommended training section

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#420]
### Description 
A filterable table for users to find upcoming training events that they may be interested in attending.

### Expected behaviour
- Each of the five select boxes represent a list of checklist items that the user can use to filter the results in the column/table below. By default, per each session this section should list all options.
  - Interest: Contains a list of the professional interest categories that the user has selected above. They should be presented in the same order as what's above. (first the left list followed by the right)
  - Date: Contains a list of months that events (of the selected categories) are being held in order of soonest to latest
  - Location: Options include: Online, within 25 km, within 50km, within 100km, over 100km. This field will require calculating the user's location and distance to events based on stored addresses.
  - Length: Options include: 1 hour or less, 1.5 - 2 hours, 2.5 - 4 hours, half day - full day, multi day. Sorted by shortest to longest
  - Cost: Options include: free, less than $20, $20 to $49, $50 to $100, $100 to $249. $250 or more (Dependent on data, these options might need to be changed)

### Content
Section heading: Recommended upcoming training
Body copy: Based on your professional interests, we suggest the following training opportunities.

### Styles
Reuse styles already defined elsewhere in the page
1em of space between body text and filter row
1.5em of space between filter row and table

**Filter dropdown**
1em of padding
background: #fff
border: 1px solid #979797
corner radius: 0, .5em, .5em, .5em

### Assumptions
- We're reusing currently defined text colour, link inactive and hover styles- 
- Table cell data is pulled from a db
- Table cell data can be used in other areas of the page, but it is not required
- Table styles are consistent throughout the site (or at least the page for MVP)
- Functionality of pulling db data and displaying time, date, event name, venue, venue address, event length, and cost is already complete/can be reused from what already exists.

### Blocked by
- #417 Create a professional interests section

<img width="764" alt="screen shot 2018-05-27 at 10 30 47 pm" src="https://user-images.githubusercontent.com/20425828/40598625-b171238e-61fd-11e8-9541-eff43ab33fbf.png">

**Comment by kathreenriel** [comment]
Instead of section on the myEYPD a Recommend Events page has been created based on Professional Interests selected in a checklist.
