### ISSUE TITLE
myEYPD: Training wheel legend

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#422]
### Description 

- take out labels on top of donut, and put them in a legend. 
- ensure that the measurement (hours is included)

**Comment by kathreenriel** [comment]
The legend is cut off ( this happens in Safari, Chrome and Firefox)
<img width="666" alt="screen shot 2018-05-29 at 2 11 45 pm" src="https://user-images.githubusercontent.com/16693738/40685963-87d45138-634a-11e8-848b-c7f4ffac6027.png">

**Comment by bdolor** [comment]
merging a PR triggered this issue to close prematurely, re-opening

**Comment by mandily-p** [comment]
My donut isn't being rendered.

![screen shot 2018-05-30 at 1 28 23 pm](https://user-images.githubusercontent.com/20425828/40745882-910f59f0-640d-11e8-932f-6a3423923cb4.png)

testing account details: I only have one past event and one I've signed up for. I'm on chrome for mac.

@bdolor Let me know what other details you need to troubleshoot this.

**Comment by bdolor** [comment]
if it's not resolved by clearing your browser cache, then I'd check the javascript console for errors.

**Comment by kathreenriel** [comment]
@mandily-p make sure you click on "attended" in the Past Events section then the donut should be revealed

**Comment by kathreenriel** [comment]
Donut doesn't seem to have a purpose when seen on a phone 
![img_2201](https://user-images.githubusercontent.com/16693738/40805270-92a97910-64d2-11e8-8a45-ec750f571a12.png)

**Comment by bdolor** [comment]
will need to look at this then.

**Comment by kathreenriel** [comment]
Yes, at minimum a short description. "This is not a donut. If this were a donut you would be directed to the nearest fitness room."

**Comment by kathreenriel** [comment]
Or maybe something else :)

**Comment by bdolor** [comment]
the requirements in this ticket have been fulfilled - captured responsiveness issue in https://github.com/BCcampus/eypd/issues/462
