### ISSUE TITLE
myEYPD section re-ordering 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#423]
### Description 

- based on the PDF document provided, re-order all sections 
- observe changes to heading values 

ref: https://doc-0c-a0-apps-viewer.googleusercontent.com/viewer/secure/pdf/3nb9bdfcv3e2h2k1cmql0ee9cvc5lole/7crgge09jl2n2c9n1fm7f9mqr115ivnj/1527524775000/drive/*/ACFrOgDCo7nyoByWHtapSXKlAObwe9GPcSzWUYDOXplM9D_AnS4u_jsXbcxmZ1eOiM_io3BDdxc2F-8LldzTaDtPS7G32yQ7U0-xXRvG7GTEPiV7mRQ8W8F4m_-lLEk=?print=true&nonce=14m81j96eniis&user=*&hash=tbg3mi70g2nhf28l9pto0dn5jkmuo19a

**Comment by kathreenriel** [comment]
Remove "This is your professional development activity page - a personal record of your training events, events you plan on 
attending, and record of professional development hours you have accumulated."

from the top of the page
