### ISSUE TITLE
myEYPD: Cache images and minify css and js on desktop

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#428]
### Description 
As recommended by Google page insights
Cache images and minify css and js on desktop
(This is already done on mobile)

**Comment by bdolor** [comment]
- server was optimized to leverage browser cache in https://github.com/BCcampus/eypd/issues/272
- minify of JS/CSS occurs as a result of our build process introduced in https://github.com/BCcampus/eypd/pull/263
- The only blocking CSS file is a dashicon.min.css file belonging to WordPress. 
- The only image that isn't cached by the browser is a google map image (not on our servers)
- The only image not optimized is one under the control of content owners, in appetite to play


Google page insights confirms the above: 
![image](https://user-images.githubusercontent.com/2048170/40674639-4913a1da-632a-11e8-888b-c227bc9278bb.png)
