### ISSUE TITLE
Group Event Option 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#441]
### Description 

There is an extra description and drop-down box that appears on the cert. site Post An Event form. See pic below
**Expected behaviour** 

Omit this sentence and drop down option 
<img width="881" alt="screen shot 2018-05-30 at 11 24 12 am" src="https://user-images.githubusercontent.com/16693738/40739905-39405348-63fc-11e8-8439-6c1c9b57d5e1.png">

**Comment by bdolor** [comment]
This only appears on eypd and is a result of enabling buddypress 'Groups' functionality. Related to having a group forum in https://github.com/BCcampus/eypd/issues/400

![image](https://user-images.githubusercontent.com/2048170/40794919-604f8a30-64b5-11e8-809a-6d42bfa4172a.png)

**Comment by kathreenriel** [comment]
Relief!
