### ISSUE TITLE
 myEYPD: New user - Training section

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#450]
### Description 
When a user is new to this page, we can reduce the amount of empty sections (clutter) we show them and prompt them to add events that they're interested in.

### Expected behaviour
- The number appended to the header should be 0
- Text link should redirect user to the event list page.
- Past events subsection is removed altogether

### Content
You have no upcoming events. Browse all events.

![screen shot 2018-05-30 at 4 00 55 pm](https://user-images.githubusercontent.com/20425828/40752099-f6044374-6422-11e8-8a6f-3e5b4bbf94d5.png)

**Comment by kathreenriel** [comment]
This currently  appears after the user clicks on the black triangle
<img width="384" alt="screen shot 2018-05-31 at 8 55 26 am" src="https://user-images.githubusercontent.com/16693738/40793153-84562bb4-64b0-11e8-9ce5-d9c38806408a.png">

**Comment by mandily-p** [comment]
There should be no toggle triangle on the upcoming events section in the new design.

**Comment by alex-418** [comment]
Brining in to complete along with #414
