### ISSUE TITLE
myEYPD: Plan to attend button in recommended events

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#452]
### Description 
Allowing the user to choose whether they want to attend an event or not right where we're marketing to them is the ideal situation. Let's add a button that behaves the same as the one on the individual event page to allow a use to do just that. 

### Expected behaviour
- Clicking/tapping on the button associated with the event in each row will add the event to the user's "Upcoming events" table.
- The button text should update and the style should update from a secondary style to a primary style
- The user should receive a text confirmation that the event has been added. If we could make this fade out after 3 seconds that would be divine.

### Content
- non-added event: Plan to attend - secondary style
- added event: Attending - primary style

![screen shot 2018-05-30 at 4 34 18 pm](https://user-images.githubusercontent.com/20425828/40753173-b669e020-6427-11e8-8f72-98ad8010477b.png)

**Comment by kathreenriel** [comment]
This issue has been investigated as part of #424 and development resource constrains implementation of these enhancements.
