### ISSUE TITLE
Donut heading and div create whitespace if there's no data

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#454]
### Description 

Donut div leaves the heading along with white space for the donut svg if there is no data. 

**Expected behaviour** 

No data = no donut. 

**Actual behaviour** 

Heading and donut div leave white space 

### Steps to reproduce the problem

Go to myEYPD, and select "did not attend" on all of your past events, then save the form.

**Comment by bdolor** [comment]
feels like a duplicate of https://github.com/BCcampus/eypd/issues/449 - @alex-418 can you confirm?

**Comment by alex-418** [comment]
@bdolor yes, #449 is better solution, will close this
