### ISSUE TITLE
myEYPD page: Redirect Access to non registered users

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#456]
Right now the myEYPD page may be visible to non-registered users. 

Redirect non-registered users who attempt to view a myEYPD page back to the EYPD homepage. 

Registered users may only view their own myEYPD page.

**Comment by bdolor** [comment]
is this not handled to some degree in https://github.com/BCcampus/eypd/pull/459 ?

**Comment by alex-418** [comment]
@bdolor can confirm, logged out user is prompted to login or register, logged in user can see only their own.

**Comment by kathreenriel** [comment]
There's something quirky about this.. it's happened twice. See kate1 logged in here

**Comment by kathreenriel** [comment]
Let me figure out how this keeps happening...if I can

**Comment by kathreenriel** [comment]
I think this happens when I have multiple tabs open under the same user at the cert site. I've tried replicating but cannot.

**Comment by kathreenriel** [comment]
AH HA I figured it out! When I log in in Chrome this is the screen it takes me to
<img width="1079" alt="screen shot 2018-06-01 at 1 14 45 pm" src="https://user-images.githubusercontent.com/16693738/40861429-ea7268de-659d-11e8-8ee8-0614dde13d9e.png">

**Comment by kathreenriel** [comment]
It doesn't seem to allow non-logged in users to see other people's pages. Moving to done.
