### ISSUE TITLE
myEYPD: Clicking on the arrows of the accordion do not collapse/expand the accordion

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#464]
### Description 
Clicking on the caret arrows of the accordion do not collapse/expand the accordion. But it does change the text from expand to collapse

**Expected behaviour** 
When the user clicks on the arrow, it should collapse or expand the content underneath it. (similar to how clicking on the text works)

**Actual behaviour** 
Clicking on the caret arrows of the accordion do not collapse/expand the accordion.

### Steps to reproduce the problem
1. Populate your past events
2. Click on the `expand` text link to validate accordion works as desired and again on the `collapse` text link.
3. Click on the `expand` arrow, and again on the collapse arrow.
4. See only the text link change and not expand/collapse the content underneath.

Description
The triangle beside expand to "Expand To See All Past Events" does not work

Expected behaviour

When user clicks on the arrow the table expands

Actual behaviour

When user clicks on the triangle, it rotates but the table does not appear.
<img width="460" alt="arrow" src="https://user-images.githubusercontent.com/16693738/41801457-89aca206-762f-11e8-8bf4-e6777b9a3572.png">

**Comment by alex-418** [comment]
Please clear browser cache for fix to take effect.

**Comment by kathreenriel** [comment]
@alex-418 
This works in Safari and Chrome . It does not work in Firefox(60.0.2) on the Mac desktop.

**Comment by alex-418** [comment]
@kathreenriel please try clearing cache in Firefox once more? I'm also on Firefox(60.0.2) and Mac, working great here.

**Comment by kathreenriel** [comment]
Sorry @alex-418 yes it works as expected.
