### ISSUE TITLE
Unique nav links for non-logged in/logged in learners/logged in organizers

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#466]
### Description 
The main navigation is always visible, but can only be used if a user is logged in.

**Expected behaviour** 
If a user is not logged in, they **should not** see the main nav links.
If a user is logged in, they **should** see the main nav links.
Depending on whether a user is a learner or an organizer, they would see their own respective navigation.

**Actual behaviour** 
A user sees the main nav links even when they're not logged in.

**Comment by kathreenriel** [comment]
This needs to be part of a bigger re- design of the homepage of what users see when they are not logged in.

**Comment by mandily-p** [comment]
@kathreenriel I agree that the homepage needs some work, but I don't think it's dependent on the navigation. Can I sway you to prioritize navigation right now?

Here's what I was thinking (only the nav is different, it's just within the home page to give it context):

**Non-signed in users**
![non-signed in users](https://user-images.githubusercontent.com/20425828/49096645-d23e3400-f21f-11e8-8287-09d6cb80746d.png)

**Learners**
![learners](https://user-images.githubusercontent.com/20425828/49096644-d23e3400-f21f-11e8-8adc-114941fefe94.png)

**Organizers**
![organizers](https://user-images.githubusercontent.com/20425828/49096646-d23e3400-f21f-11e8-8f87-f07a083ec5e7.png)

If a user was both a learner AND an organizer. 
(Also shows sub menu and hover states)
![learner and organizer](https://user-images.githubusercontent.com/20425828/49096643-d23e3400-f21f-11e8-8829-b249c1691010.png)
