### ISSUE TITLE
myEYPD page: Navigation back to homepage on mobile device

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#467]
When a user clicks on myEYPD on a mobile device an opens the page, currently there is no way for the user to navigate back to the homepage from the myEYPD page to the home page. 

Make the header consistent with mobile devices so that they user can click on the EYPD logo to navigate back to the homepage from the myEYPD page. 

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- EYPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by paulagaube** [comment]
Alternately, what about adding a "Home" text link on the same blue line as "Log in" and "Sign Up"?
(image to come)

**Comment by bdolor** [comment]
just add the word 'home' for now

**Comment by paulagaube** [comment]
Thank you, this works on an iPhone!
