### ISSUE TITLE
My Professional Interests Page: Event Listings

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#468]
Currently, a listing of events that match a users interests appear on the My Professional Interests Page. 
**Expected behaviour** 
Create a table view similar to the Upcoming Events and Past Events that includes
- Location below the event title
- Date and time
- Length of time
- Cost
- Links "Registration link" or "Contact to register"
![screen shot 2018-06-25 at 9 43 27 am](https://user-images.githubusercontent.com/20425828/41863642-3c6066de-785c-11e8-9dd4-4a5c0556d7bd.png)

**Comment by alex-418** [comment]
Take out attending and plan to attend

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/custom-wp-notify/pull/40
