### ISSUE TITLE
myEYPD Page: Professional Interests

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#472]
Change the title of save button to Save Selected Interests
<img width="261" alt="screen shot 2018-06-22 at 11 20 17 am" src="https://user-images.githubusercontent.com/16693738/41792627-5cfaee50-760e-11e8-8154-43c9cd1ac186.png">

**Comment by mandily-p** [comment]
@alex-418 or @bdolor Is it possible to combine these two functions into a "save and recommend events" button? Or can we use ajax to save the list, but require user input to generate the event page?

**Comment by alex-418** [comment]
For MyEYPD Refinement Sprint Part 3, focusing only on updating the title of the button.
