### ISSUE TITLE
myEYPD: Take user to myEYPD when they login

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#476]
**Expected behaviour** 
When the user logs in to their account, immediately take them to the myEYPD page.

**Actual behaviour** 
The user is currently brought back to the home page.

**Comment by kathreenriel** [comment]
If the navigation redirected users to myEYPD there would need to be a prominent button (top center?) that would show users the option to just search for training.

**Comment by kathreenriel** [comment]
This needs be be part of a bigger re-design plan

**Comment by brettjforsyth** [comment]
@kathreenriel @mandily-p At this point do we want all users who login to be redirect to myEYPD page. Is there any set plan on the big search button?

**Comment by mandily-p** [comment]
@kathreenriel We have the "find events" menu item. We don't need a second button. 

@brettjforsyth Yes, ideally in the future organizers would be sent to their own dashboard type of page where they'd see all of their own posted events, but we don't have that at the moment so the myEYPD dashboard will work for them now too.

**Comment by brettjforsyth** [comment]
@mandily-p perfect

**Comment by paulagaube** [comment]
@kathreenriel I have confirmed that login directs users to their myEYPD page.

**Comment by kkilbey** [comment]
This worked for me on prod.
