### ISSUE TITLE
myEYPD: Certificate expiry message and colour

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#477]
**Expected behaviour** 

When the user's expiry date has past, display a message telling them how to fix it and bring attention to it by colouring it red.

**Copy** 
Your certificate has expired. Please update your account with a new expiry date.

**Current**
![screen shot 2018-06-24 at 4 20 09 pm](https://user-images.githubusercontent.com/20425828/41824746-80fafd46-77ca-11e8-9959-ccbb13c50552.png)

**Desired**
![screen shot 2018-06-24 at 4 18 04 pm](https://user-images.githubusercontent.com/20425828/41824749-8c89bc2e-77ca-11e8-9651-e1c4abff6e32.png)

**Comment by kathreenriel** [comment]
The red colour of the text appears on my desktop when viewing this message but the text is in black when I view it on my phone.

**Comment by alex-418** [comment]
@kathreenriel clear phone browsers cache please and see if that resolves the issue.

**Comment by kathreenriel** [comment]
AUGH you're right! Sorry @alex-418
