### ISSUE TITLE
EYPD home: Number of events

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#478]
Add the number of events in the system above the search field so that users are confident that there's enough events in the system to make it worth their while to use it.

**Copy**
There are [number] upcoming events

**Styling**
font-weight: bold;
margin-top: 3em

![screen shot 2018-06-24 at 4 28 48 pm](https://user-images.githubusercontent.com/20425828/41824838-ec941b04-77cb-11e8-81f4-339e42796b51.png)

**Comment by kathreenriel** [comment]
I wonder if the number of training events should be positioned above "Search for training events".

**Comment by kathreenriel** [comment]
This issue is part of a bigger plan for a re-design of the homepage.
