### ISSUE TITLE
myEYPD: Total attended/did not attend events

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#479]
Add the number in brackets after each column header in the 'attended,' and 'did not attend' columns so it’s contextual.

![screen shot 2018-06-24 at 5 21 48 pm](https://user-images.githubusercontent.com/20425828/41825349-8cb025a4-77d3-11e8-998c-d6e60c4520d9.png)

**Comment by kathreenriel** [comment]
@mandily-p just to clarify, the number represents the number of training events attended not the number of hours collected or not collected thus far correct?

**Comment by mandily-p** [comment]
@kathreenriel That's correct. It's the number of events attended.
