### ISSUE TITLE
Investigate: Saving, Previewing, Posting Event

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#48]
Feature Request for Post an Event Page. 

 Save for later button: 
 Preview and Post button – mandatory?
 Post How about the Post button only appears on the preview window?

**Comment by kathreenriel** [comment]
Duplicating dashboard functionality on a front end form has been a persistent issue during EYPD web development. On of the foremost goals of this project was to design and present a simple user interface for Organizers to post events; therefore, we opted not to open the dashboard functionality to Organizers.
