### ISSUE TITLE
EYPD: Add multiple images when creating an event

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#480]
Users would like the ability to add multiple images to an event. This could include photos from previous events, a photo of the speaker, participants interacting with each other etc.

Display a confirmation message when the image has been successfully uploaded and attached.

**Comment by kathreenriel** [comment]
Investigate how many  training events in the past year utilized a graphic in their post.

**Comment by kathreenriel** [comment]
This is identified in #521
