### ISSUE TITLE
myEYPD: Select all checkbox functionality on professional interests

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#484]
### Description 
**Expected behaviour** 
If all checkboxes are selected, the "select all" checkbox should automatically be ticked. If one or more of the checkboxes are unticked, the "select all" checkbox should automatically be unticked.

**Actual behaviour** 
The select all checkbox is not selected when the page loads with all of the items checked.
The select all checkbox can be ticked with other items in the list unticked.

![screen shot 2018-06-24 at 7 44 35 pm](https://user-images.githubusercontent.com/20425828/41827933-164a9aca-77e7-11e8-8f66-9187cb9bd1cd.png)
![screen shot 2018-06-24 at 7 44 44 pm](https://user-images.githubusercontent.com/20425828/41827934-165eface-77e7-11e8-96f3-f946a6e89e19.png)

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/custom-wp-notify/commit/2bd0e8ad3c14c467e445ffb06590d00ca4904805 
Note: Please clear browser cache to ensure the changes to the JavaScript file are applied.

**Comment by kathreenriel** [comment]
Works on Chrome, Firefox, Safari, laptop and iPhone.
