### ISSUE TITLE
EYPD - Event list page: Add attending/plan to attend buttons

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#487]
### Description 
Give users an at a glance way to tell if they're already planning on going to an event, and also let them add it to their events without needing to go into the details. Create buttons using the primary and secondary style in the last column of the table.

**Blocked by #468**
![screen shot 2018-06-25 at 9 44 25 am](https://user-images.githubusercontent.com/20425828/41863764-abff5414-785c-11e8-9a9a-436daef35bd4.png)

**Comment by kathreenriel** [comment]
Given results by Alex #424 as to what can be "ajaxified" this is being closed
