### ISSUE TITLE
On SignUp to EarlyYearsbc.ca - Users asked for Activation Code and can't verify their account

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#489]
### Description 

After completing Sign Up on EarlyYearsbc.ca or EYPD.bccampus.ca, Learners and Organizers are asked for an Activation Key before they can verify their account. The account stays in the Users > "Pending" list.

**Expected behaviour** 

After a user completes and submits the Sign Up form as either an Organizer or a Learner, their account is added to the User list as "Pending" and an email including an activation link is sent to the user's email address. After clicking the activation link, the user's account becomes active. 

**Actual behaviour** 

Clicking the link to activate the account does not activate the account, and the account stays in the User > Pending list.

SCREENSHOT:
![eypd-activate-screen shot 2018-06-25 at 1 34 41 pm](https://user-images.githubusercontent.com/26391359/41879776-f1cf5ed4-788f-11e8-91c7-7ee6ce4583ab.png)

### Steps to reproduce the problem

Went to earlyyearsbc.ca, clicked Sign Up. Entered user information. Submitted form. 

Onscreen message says "Sign Up Complete! You have successfully created your account! To begin using this site you will need to activate your account via the email we have just sent to your address."

Waited for email. 
(Though I tested with three separate email accounts, only one account received the email.)

Clicked the link in the email I received on my shaw account (not a domain validated) and received email from wordpress@earlyyearsbc.ca.

After clicking the link, was taken to the earlyyearsbc.ca site URL: https://earlyyearsbc.ca/activate/nmMmzlobKv0Fxh77S3jFs3NmKTh7KX0Z/

I have verified that accounts are created and added to the Users > "Pending" list page on both EYPD and earlyyearsbc: 
https://eypd.bccampus.ca/wp-admin/users.php?page=bp-signups
https://earlyyearsbc.ca/wp-admin/users.php?page=bp-signups
(The text on the top browser tab is "Manage Signups") 

### System Information

- EYPD: eypd.bccampus.ca and earlyyearsbc.ca
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
An explanation is here: https://buddypress.trac.wordpress.org/ticket/6049 (tldr; some email clients/filters scan emails and follow links embedded in those emails which inadvertently activate an account.) 

The fix was brought into buddypress 3.0 as far as I can tell. 

The reason we're not seeing the fix is because commons-in-a-box currently has buddypress at v2.9.4

One workaround is to copy the token parameter (the Activation key) from the url and paste it into the activation box

**Comment by bdolor** [comment]
@kathreenriel - that is correct. It's not ideal, but it works for now as a stop gap measure until c-in-a-box upgrades bp version.

**Comment by kathreenriel** [comment]
@bdolor thanks for clarifying

**Comment by kathreenriel** [comment]
@paulagaube This activation code requirement needs to be part of the confirmation email and the Help questions. Would you please draft copy for this?

**Comment by paulagaube** [comment]
Ok, I'm going to test this and draft something up. Also was going to add an FAQ for this.

**Comment by paulagaube** [comment]
@kathreenriel I created a draft of an FAQ (pasted below here), and I'm thinking about the confirmation email. 

As well as tell people how to copy and paste the key, I'd like to give them the option to email earlyyears@bccampus.ca and then we can validate the account manually. (We do get copies of emails that say when people create a new account already.)

_Here is what I wrote in version 1 of the FAQ, but will add instructions to copy the activation key, as I tested this again and it worked:_
**Question:**
What is my Activation Key? I was asked to enter this when I clicked the link to activate my EYPD account.
**Answer:**
If you were asked to enter an Activation Key when you signed up for an EYPD account, please email earlyyears@bccampus.ca with your name and email address and we will validate your account manually.
This is a known issue that our development team is working on correcting.

**Comment by paulagaube** [comment]
Created issue to add text to activation auto-email new account holders receive: https://github.com/BCcampus/eypd/issues/507

**Comment by alex-418** [comment]
Bug commons in a box to update BuddyPress https://wordpress.org/support/plugin/commons-in-a-box

**Comment by bdolor** [comment]
taking over the activation template solved this via https://github.com/BCcampus/eypd/commit/7eb104902149c65029883bb4ee09ebf150584fc9 

hotfix pushed to cert and prod.

now the expected behaviour is that the activation code is automatically pasted into the area. The user only has to click 'Activate' and they're in. 

![image](https://user-images.githubusercontent.com/2048170/45654232-b2f09100-ba8f-11e8-94cc-351d74b34b72.png)

**Comment by paulagaube** [comment]
This is a lovely fix, thank you. I tested with both Learner and Organizer accounts, and account creation was successful in each case. Wonderful.

**Comment by kathreenriel** [comment]
WOW @bdolor this works for me! Just tested it again it works. @paulagaube we'll change the FAQ to go with this.
