### ISSUE TITLE
myEYPD page: Calculate my Hours function 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#495]
### Description 

When user makes changes to the Past Events that they have attended and clicks on "Calculate My Hours" the table closes and the page "jumps" to the top of the myEYPD page forcing the user to scroll down the page, click on "Expand to see all past events" and view the new total number of hours collected. 

It would reduce the number of scrolls and clicks if the user may click on "Calculate My Hours" and see the changes immediately in the table without having to scroll down the page and open the table again.

**Comment by kathreenriel** [comment]
Discussed this with Brad (June 28) and determined that once #482 is clarified we will consider the rendering of the table after user clicks on "Calculate My Hours"

**Comment by mandily-p** [comment]
Another thing that might help (but is a different ticket) is remembering what state the user left that past events table in during their site visit and leaving it that way for the duration.
