### ISSUE TITLE
myEYPD: List of Upcoming and Past Events - Add ability to sort columns by date (oldest or most recent first)

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#504]
### Description 

PG Wish List item - on myEYPD page, under the "Training" section, allow the table columns to be sorted by date (as well as alphabetically?). 

**Expected behaviour** 

On the myEYPD page, both **Upcoming Events** and **Past Events** are currently sorted Alphabetically by Event Description, regardless of when the event took place. I would like to be able to sort the events by date, either ascending or descending date order (oldest first or most recent first). 
This would allow me to easily scan the events by date, and also see at a glance when the courses were taken, and in what order. Date order would also allow me to answer this question: "What was the name of that course I attended last November?" 

**Actual behaviour** 

The list of Upcoming Events and Past Events are only listed alphabetically by Event Title.

### System Information

- EYPD: https://eypd.bccampus.ca/members/pgaube/events/

![myeypd-pastevents-sortingcolumns](https://user-images.githubusercontent.com/26391359/42073013-ee65533a-7b18-11e8-988c-00411ba6a9f0.png)

**Comment by mandily-p** [comment]
I second that!

**Comment by alex-418** [comment]
Modifying the order would impact other tables, look into splitting up the data so each table can be sorted independently, and the addition of a JS library to add to tables to enable the user to toogle the sorting order.

**Comment by alex-418** [comment]
Sort by date for now, descending order.

**Comment by alex-418** [comment]
@kathreenriel requires further investigation to sort events tables independently based on the date. Moving to backlog as discussed.

**Comment by kathreenriel** [comment]
Alex applied a lot of effort and time to determine if this is possible. Concluded that there were a lot of dependencies that we do not wish to address or modify at this time.
