### ISSUE TITLE
Restrict Organizer access to the dashboard

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#505]
An organizer was able to access the dashboard by appending the URL with wp-admin, and created a recurring event which created over 300 events at once. Limit their access by redirecting anyone who doesn't have admin privileges to the homepage when they attempt to access the backend dashboard.

**Comment by alex-418** [comment]
@kathreenriel found the setting which allowed the creation of recurring events on the front-end form: 

![recurring](https://user-images.githubusercontent.com/17072191/42107589-d498db1a-7b8c-11e8-867c-dd261254b413.png)

I've turned this off on prod, so everything should be back to normal. Does that complete this issue, or would you still like me to re-direct everyone except admins if the manually enter the dashboard by appending the url with wp-admin ?

**Comment by kathreenriel** [comment]
I think given this recurrent event was likely accessed from the front end this is complete thank you
