### ISSUE TITLE
Add explanatory text to the account-creation email (re: Activation Key)

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#507]
### Description 
Add explanatory text to the account-creation email to tell users how to find their Activation Key and complete their account activation.

**Expected behaviour** 

Informational text tells new user how to activate their account by either copying the Activation Key or contacting support for help.

**Actual behaviour** 

The basic email says "Thanks for registering!" and includes a link "To complete the activation of your account, go to the following link:" <activation link>

### Replace/Update the text in the email as below

(New text for the email:)
--------
Thanks for registering!

To complete the activation of your account, go to the following link: <activation link>

If you are asked to enter an "Activation Key" when you click this link, there are two options:
​
1. Copy the Activation Key from the URL (link) in the email and paste it in the Activation Key box, then click "Activate". Copy the part of the URL between "https://earlyyearsbc.ca/activate/" and the final "/". Do not copy the slash "/" at the beginning or end of the Activation Key.
For example:
https://earlyyearsbc.ca/activate/**TUdOYj7qflcpt02aWWIW6ErW8L4hYMcf**/

2. Email earlyyears@bccampus.ca with your name and email address and we will validate your account manually.
​

**Comment by paulagaube** [comment]
@kathreenriel @mandily-p @alex-418 I am still manually approving/activating new user accounts on earlyyearsbc.ca, and rethinking this auto-email message that new signups/users receive. 

The message currently says: "Thanks for registering!" and includes a link "To complete the activation of your account, go to the following link:" (and the link does not work). 

What do you think about replacing the text with this revised message? (I'm not sure if we can remove the activation link or not.) Alex, is this something Amanda or I can edit/fix?
------
Thanks for signing up for an Early Years Professional Development account!

If you click the link below to activate your account, you will be asked to enter an Activation Key. This is a known issue that our development team is working on correcting. _<If we can remove the Activation Key link, we don't need this sentence.>_

To complete activation of your EYPD account, please email earlyyears@bccampus.ca with your name and email address and we will validate your account manually.

**Comment by kathreenriel** [comment]
@paulagaube Yes, go ahead with the text you suggested above (sigh....) Looking forward to a implementing different process.

**Comment by kathreenriel** [comment]
<img width="712" alt="screen shot 2018-09-17 at 2 29 27 pm" src="https://user-images.githubusercontent.com/16693738/45651464-694f7880-ba86-11e8-8fd5-5f36a4c0e3d9.png">

**Comment by bdolor** [comment]
wondering if this is still valid in light of: https://github.com/BCcampus/eypd/issues/489#issuecomment-422194798

**Comment by paulagaube** [comment]
It looks like adding this text is no longer necessary! Thanks, @bdolor 
@kathreenriel Since the Activation Key now appears in the Activate box, we don't need this descriptive text. Time will tell if we need other descriptive text on this page, but for now, let's close this ticket?
