### ISSUE TITLE
google maps pricing evaluation

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#508]
### Description 

Google has started charging for the use of its API. Events Manager functionality is integrated tightly with Google maps. 

https://wp-events-plugin.com/documentation/google-maps/api-usage/
https://wp-events-plugin.com/blog/2018/07/17/google-maps-api-pricing-increases/
https://cloud.google.com/maps-platform/pricing/sheet/
https://cloud.google.com/maps-platform/user-guide/

**Expected behaviour** 

Would like to evaluate the current API token used in all sites that use the map and transition the API token to a BCcampus controlled account, OR look at other options for a map service, or manage the potential costs associated with using the API. 

**Actual behaviour** 

We know very little at this point about what the impact could be.

**Comment by kathreenriel** [comment]
This could be an issue if this project progresses to scale-up stage.

**Comment by dshaykewich** [comment]
Done.
