### ISSUE TITLE
Allow users to type www.earlyyearsbc.ca

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#511]
### Description 
Users can't access the site if they type www.earlyyearsbc.ca

**Expected behaviour** 
Users can access the site at www.earlyyearsbc.ca, https://earlyyearsbc.ca, and earlyyearsbc.ca
![screen shot 2018-08-14 at 11 22 03 am](https://user-images.githubusercontent.com/20425828/44110388-642c1a62-9fb4-11e8-9f6e-8d6f28cff063.png)

**Comment by paulagaube** [comment]
Paula to create a JIRA issue and follow up with George.

**Comment by paulagaube** [comment]
Created JIRA issue: https://jira.bccampus.ca/browse/SH-1246
Brian Case is investigating.

**Comment by paulagaube** [comment]
Redirection for both www.earlyyearsbc.ca and https://www.earlyyearsbc.ca/
go to https://earlyyearsbc.ca 

I have tested. Will someone else test too, please?

**Comment by kathreenriel** [comment]
Good for me too.
