### ISSUE TITLE
BUG: My profile page

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#514]
### Description 
I'm not sure what's supposed to be on this page. But whatever it is, it's not working

**Expected behaviour** 
@kathreenriel Can you comment on what this *should* look like please?

**Current view**
![screencapture-eypd-bccampus-ca-members-ahealey-profile-2018-08-14-22_45_05](https://user-images.githubusercontent.com/20425828/44133281-e095a30c-a013-11e8-8e9f-73b0a054f069.png)

**Comment by kathreenriel** [comment]
I cannot replicate this issue
