### ISSUE TITLE
Revise FAQs 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#515]
### Description 

THe current Help needs to be updated both technically and in the content. **Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- EYPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by paulagaube** [comment]
This is a duplicate of issue #350

**Comment by kathreenriel** [comment]
@paulagaube looking at it on my iphone it renders really well I like the option of swiping down the topics without the extra text. There's no extra white space at the bottom on my phone
