### ISSUE TITLE
myEYPD: Allow users to add images of certificates to the events that they've attended

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#517]
### Description 
Users need to submit certificates every five years to prove their hours. It would be great to give them one space to store everything.

**This needs more investigation to see what's technically feasible.**

**Comment by mandily-p** [comment]
Blocked by #264

**Comment by kathreenriel** [comment]
I think we should consider another validation process other than manually uploading certificates. The Advisory Group also suggested Organizers following a system that validates the professional development taken by Learners - may a unique number or word that is entered by the Learner as a validation key.

**Comment by mandily-p** [comment]
I like the idea of this eventually moving to something the organizers and governing certification body can use to validate hours, but it would probably be best to do this in a multi-step process. Especially as the system of unique identifiers would need to be a project taken on by the governing body before we could do anything with it on the site.

1. **Track hours** - Allow learners to manually enter event details including hours
2. **Documentation collection** (proof) - Allow learners to upload certificate images and attach to event details 
3. **Minimize fraud** - Create a system to create and track unique ID's for all certification certificates in the province (I don't expect this would be our responsibility)
4. **Streamline record keeping** - Connect learner's documentation to organizers unique ID's and give both the ability to report these items directly to the governing body through the website.

@kathreenriel Are you in contact with anybody in the governing body (is that the ministry?) that you would be able to talk to about the creation of a unique ID system for every certificate awarded?

**Comment by mandily-p** [comment]
👍

**Comment by kathreenriel** [comment]
this is detailed more explicitly in #264
