### ISSUE TITLE
Install YouTube thumbnail plugin

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#519]
### Description 
There is a [brain development blog post](https://earlyyearsbc.ca/brain-development-and-behaviour/) that has a youtube playlist linked within it. In order to provide the best user experience for our site visitors, I'd like to present the playlist to them on default, instead of requiring them to click the teeny tiny playlist icon in the top left of the player.

I researched some open source and paid options, but found that this [paid option](https://codecanyon.net/item/youtube-and-vimeo-video-player-with-playlist/7964882) meets all of the requirements best. [Here's the demo](http://www.videoplayerhtml5.com/youtubeandvimeo/index_fixed_youtube_imgandtext.html).

- Playlist with image, title and description
- Responsive
- Can be styled to fit with the branding of the site

![screen shot 2018-08-21 at 12 59 54 pm](https://user-images.githubusercontent.com/20425828/44425927-20b5a580-a542-11e8-92da-9c76633e291e.png)

**Comment by alex-418** [comment]
@mandily-p  Here's the process we usually go through to evaluate new plugins, it helps reduce risk and technical debt. For example, if there's an update/change to either WP/Youtube API/This plugin and it stops working (inevitable)... we'll be at their mercy to fix it with an update. Otherwise we'd have to reverse engineer it and fix it, but by doing we'd loose ability to update it and have to now support it ourselves. Also important to test for any conflicts with other plugins or JS libraries. 

If we've gone through these and @kathreenriel is comfortable with the risks/impact this plugin has, then by all means please proceed to test/install. 

![plugin-decision](https://user-images.githubusercontent.com/17072191/44481003-8d3fab80-a5f9-11e8-997b-a611332ab486.png)

**Comment by mandily-p** [comment]
@alex-418 With regards to the second decision - Can I do what I need without a plugin? - I suspect you could code this yourself, but I don't have that skill. It's a bit more complicated than just adding everything in once for this blog post. Kathreen has mentioned that it would be nice to have this available for future promotion of Youtube lists as well. 

Alex, how would you suggest to proceed from here? Do you want to take a look and see if you want to code something from scratch or should I go ahead with evaluating the competing products?

**Comment by alex-418** [comment]
@mandily-p Please go ahead with evaluating, I think I'll be updating that process so it's clearer what we're concerned about from a technical/maintenance perspective, and separate that out from the tasks you guys can do to help expedite this type of decision.

**Comment by mandily-p** [comment]
I sent an email to the developer to ask about impacts to the site. I wasn't sure how to get answers without going that route. 

Here's a copy of the questions in that email:
- Does it access/send any of my data to a third party?
- Would the plugin affect page/site performance any more than embedding a native YouTube video?
- Are there any ads shown in the Wordpress admin when this is installed?

**Comment by alex-418** [comment]
@mandily-p That's great, good idea to verify if we can get a response from the developer incase we ever needed support for this. Usually I could help answer those questions by looking at the source code, but this isn't an open source solution... so that would only possible after you've purchased it. 

We could definitely code this functionality ourselves, just depends if it's worth the time based on our priorities. If there's a solution out there that does the job that won't create any technical debt/issues with our site or other plugins, i'm all for it.

**Comment by mandily-p** [comment]
He was quick to respond!

1. The plugin uses Vimeo and YouTube API so we don't store or send any information. We are only using Vimeo and YouTube API
2. Similar performance
3. Since is a paid plugin, there's o ad on your WP admin. The only ad which might appear when you watch a video is the one added by YouTube, just like when you use an YouTube iframe The ad is not inserted by us but by YouTube and it has no connection with our plugin. It doesn't matter if you use our player or an iframe, the ad will appear if YouTube decided to show it.

**Comment by alex-418** [comment]
@kathreenriel would like to ensure it doesn't conflict with any existing functionality or plugins. That would require testing it on cert.

**Comment by kathreenriel** [comment]
@alex-418 Thanks Alex. @mandily-p please set up the page on cert and test

**Comment by mandily-p** [comment]
@kathreenriel Will someone be providing thumbnails and descriptions for each of these videos or are we (me?) supposed to be coming up with both?

**Comment by mandily-p** [comment]
It looks like "responsive" and "mobile-friendly" meant that it works with touchscreens and shrinks down to fit small screens. Not that there's a unique mobile experience that would use the space better.
**Desktop**
![screen shot 2018-08-27 at 3 59 58 pm](https://user-images.githubusercontent.com/20425828/44691194-94f4bb00-aa12-11e8-9d2a-fd07a53d15c7.png)


**Mobile**
![screen shot 2018-08-27 at 4 04 02 pm](https://user-images.githubusercontent.com/20425828/44691284-e43aeb80-aa12-11e8-9b2b-9e21580b3030.png)
![screen shot 2018-08-27 at 4 01 44 pm](https://user-images.githubusercontent.com/20425828/44691195-94f4bb00-aa12-11e8-8bea-b80b10ec3238.png)

It does support full screen though, so maybe it's not so bad? @kathreenriel What do you think?
![img_5888](https://user-images.githubusercontent.com/20425828/44691470-970b4980-aa13-11e8-8167-98226c6880d6.jpeg)

**Comment by mandily-p** [comment]
My best guess is yes because it's just a link I add into the plugin, so my guess is that it pulls from Youtube every time. It's not hosted on WP anywhere. I'm not sure how to test it to be sure though. @alex-418 Do you have any thoughts on this?

**Comment by mandily-p** [comment]
@kathreenriel Are you ok with me moving forward and installing this plugin on prod? We don't need to populate it in the post yet, but I'd like to get it installed if you're ok with the mobile look and feel of the plugin.

**Comment by kathreenriel** [comment]
@mandily-p yes, please proceed with installation of plugin on prod and formatting of this post page.

**Comment by mandily-p** [comment]
Plugin is installed and configured the same as what I've done on cert. Unfortunately it's not showing up properly in the post though. I've sent an email to the developer with details on what I've tried to debug and asking for assistance in next steps for troubleshooting. He's been fairly responsive in the past so I'm confident he should get back to me soon.

**Comment by kathreenriel** [comment]
@mandily-p The issue I've had with blog posts in the past is this Images Glitch with Blog Posts #268
But I don't this is related.

**Comment by alex-418** [comment]
@kathreenriel I can confirm these would not be related.

**Comment by mandily-p** [comment]
I did a little more debugging this morning and realized that it works with 3 items, but as soon as a scroll bar would appear with the fourth - it no longer works. I've emailed the dev with a screenshot of the log errors to see if he can help.

**Comment by mandily-p** [comment]
The dev responded:

> This file is modified or corrupt in a way: https://earlyyearsbc.ca/wp-includes/js/jquery/ui/mouse.min.js
If you use this one http://two.lambertgroup.ro/wp-includes/js/jquery/ui/mouse.min.js it will not throw the error.

@alex-418 The file he’s suggesting we use is minified, so I can’t tell what this is actually running. Should we (you) be trying to figure out why our file is corrupt and fix it, or is it ok to use the one he’s suggesting after testing on cert?

**Comment by alex-418** [comment]
@mandily-p That is definitely not the cause of this issue... those two files are actually identical. jQuery is part of WordPress core, and both of those links are to the exact same file. So definitely won't be swapping that out. I also ran them through a diff checker to be sure (even without doing that you can see they are the same version of jQuery).

**Comment by mandily-p** [comment]
Another option might be not using a plugin. I accidentally bought/downloaded the jquery version of the plugin. @alex-418 What do you think?

[codecanyon-7964882-youtube-and-vimeo-video-player-with-playlist.zip](https://github.com/BCcampus/eypd/files/2341569/codecanyon-7964882-youtube-and-vimeo-video-player-with-playlist.zip)

**Comment by kathreenriel** [comment]
@mandily-p @alex-418  No please stop further development with this plugin. I think the post/page should be designed manually.

**Comment by mandily-p** [comment]
By "Manually" so you mean without the use of a script? So just html and css?

**Comment by kathreenriel** [comment]
@mandily-p yes

**Comment by mandily-p** [comment]
How about this? Native Youtube player with instructions for accessing the playlist.

<img width="853" alt="screen shot 2018-08-31 at 4 43 21 pm" src="https://user-images.githubusercontent.com/20425828/44939811-0bf4c100-ad3d-11e8-99e7-6f6f0ba30a07.png">

**Comment by kathreenriel** [comment]
This would help to clarify the location of the content but I would like to see each video  illustrated with a thumbnail and a short description.

**Comment by mandily-p** [comment]
At the moment, all of the thumbnails look relatively the same - just the same guy with half a blue screen, and the description of each video is exactly the same too.

If we have a list of video thumbs - they'd link to youtube.com, away from the site. It's probably better to keep them on our site, is it not?

I'd suggest using what we've got, knowing the user can click that icon to get the full list - until we are able to get unique descriptions and thumbnails from the group that uploaded these videos.


<img width="831" alt="screen shot 2018-08-31 at 4 57 33 pm" src="https://user-images.githubusercontent.com/20425828/44940054-01d3c200-ad3f-11e8-8958-93d68d3e8d15.png">

**Comment by kathreenriel** [comment]
@mandily-p I agree it's optimal to keep them at our site 

Here's original  request they sent us 
Actually, the preferred format would be for each of the video segments to be posted separately.  That requires going into the playlist and pulling out each link, and posting each one. 

I think they want each video to be more prominently illustrated on the page.

**Comment by kathreenriel** [comment]
In the end this plugin did not work at expected. Blog post was created with all of the videos on one page.

**Comment by mandily-p** [comment]
The developer emailed back again, adamant that our file was corrupt. He said he swapped out his for ours and it worked fine.


________________________________

**Comment by alex-418** [comment]
@mandily-p Please see my comment in https://github.com/BCcampus/eypd/issues/519#issuecomment-417766361
That file is part of WordPress core. We never modify WordPress core files.
