### ISSUE TITLE
BUG: Organizer cannot see the banner image that they've uploaded

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#521]
### Description 
When an organizer is creating an event, they have the option to upload a banner image.

**Expected behaviour** 
After selecting the banner image, they should be able to see it in the WYSIWYG editor. 

**Actual behaviour** 
After selecting the banner image, they can't see it in the WYSIWYG editor, nor do they get any other kind of confirmation that it's been attached.

**I don't see the image in the editor**
![screen shot 2018-08-21 at 3 42 08 pm](https://user-images.githubusercontent.com/20425828/44432909-e1468380-a558-11e8-9408-1711f8f7051e.png)

**I can see in the code that it's been added**
![screen shot 2018-08-21 at 3 42 16 pm](https://user-images.githubusercontent.com/20425828/44432920-eefc0900-a558-11e8-980c-a4bde8afb73f.png)

**Comment by kathreenriel** [comment]
@mandily-p This isn't a bug because we were aware of this behaviour however this is connected with #480. It would be ideal if the user saw confirmation message when inserting an image and was also able to upload multiple images, and see them before publishing.
