### ISSUE TITLE
Install a link checker on the site

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#523]
**User stories**
**As an organizer and website owner,**
I want to make sure that there are no broken links in our training events,
So that all interested learners can reach the content that every link provides (usually registration form)

**As a project owner** this supports the objectives of the EYPD project charter "to promote quality and workforce capacity" by offering information and specifically links that are accurate. 

**As an Organizer** a link checker will help provide the most accurate information by ensuring that the content and registration links are correct. 

**As a Learner** when participating in the Forum and sharing content as links, a link checker will be helpful to ensure the accuracy of the content. 

### Description 

There are broken links on the EYPD site. The EYPD admin and Organizers could revise these links without manual testing if we had an automated check for broken links.

We can also allow organizers to test their links before posting their events, similar to how Gmail works. (see screenshot)
<img width="622" alt="screen shot 2018-12-04 at 10 32 00 pm" src="https://user-images.githubusercontent.com/20425828/49600633-833b8180-f938-11e8-94f0-49b6bd20d376.png">

### Requirements/acceptance criteria
- Scan entire learner/organizer site for broken links
- Link checking shouldn't affect analytics. (This could either be part of the solution or as a second step in filtering the analytics account to exclude hits from the checker)
- Automated weekly check 
- Emails sent to earlyyears@bccampus.ca

- Allow users to check the links they've included in their event before the event is posted.

**Comment by mandily-p** [comment]
WRT Wordpress plugins, it looks like [this is the best option](https://www.marcobeierer.com/wordpress-plugins/link-checker):
We can check for links manually through the WP interface for free, or upgrade to pro for 95 Euro a year so that we could enable email notifications. I'm not sure it's worth it.

The alternative (which I didn't know existed previous to this exploration) is to use a [free online service](https://www.brokenlinkcheck.com/). That would prevent the addition of another plugin, but it's one step removed, and I'm not sure if they collect any data while crawling the site.

@bdolor Can I get your review/thoughts on this?

**Comment by bdolor** [comment]
The 500 URLs limit is going to be an immediate barrier and we'll soon find ourselves in a position where the pro option will seem less like an option. Locally I installed and ran [linkchecker](https://github.com/linkchecker/linkchecker) and put it against `earlyyearsbc.ca` for about 20 minutes before cancelling the operation prior to completion and it ran checks on 689 URLs. 

While this is one of many solutions that can be installed locally, it's also served as a linux package which can then be updated as part of the OS and tied into cron jobs that can be configured to email error reports on a [regular basis](https://github.com/linkchecker/linkchecker/blob/master/doc/examples/check_urls.sh) . The other benefit is how a solution like this can scale to other web properties besides eypd. 

Are you working with a list of requirements that the solution is meant to serve, or was the initiative behind this primarily an admin tool that does the very basics of link checking?

**Comment by bdolor** [comment]
Depending on the requirements and where the need is coming from I would need to confirm that this is the right solution, or look for an alternate solution or drill down on some of the details or adjust the estimated time. If the scope of this is changing significantly, then we would want to bring this back into a discussion about how this fits in the current sprint. 

If this is a one off, and the above solution is satisfactory then I would advise running it locally on your machine and generating the report from there. As you mention, online solutions are also available. I'll add this to the list: 

https://validator.w3.org/checklink

**Comment by mandily-p** [comment]
Ideally, I'm looking for a persistent, automated weekly check. I don't think the scope is changing significantly, there's just a low cost opportunity to reap benefit from this ticket across other properties. 

The need is one I identified, but I don't think it's wise than an external contractor assume ownership of a permanent solution that covers multiple sites within the org - That's why I was asking if you had bandwidth to own it. If you don't, maybe @kathreenriel has an idea of who can?

**Comment by bdolor** [comment]
issue is less about bandwidth and more about requirements...

**Comment by mandily-p** [comment]
@kathreenriel @paulagaube Who's the best person to email the list of broken links? (They would need to contact organizers if the links belonged to them.)

**Comment by kathreenriel** [comment]
@mandily-p @bdolor see revisions in the description at the top of the page

**Comment by paulagaube** [comment]
@mandily-p @kathreenriel I would say email the list of broken links to earlyyears@bccampus.ca.

**Comment by kathreenriel** [comment]
@bdolor Worked with @mandily-p to refine the requirements and reasoning about this ticket. Putting it back in the Sprint backlog to discuss with you when you can

**Comment by kathreenriel** [comment]
Kathreen to investigate the email options from Matomo about broken links a weekly report.
