### ISSUE TITLE
Organize list of agencies on the profile page

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#525]
### Description 
There is a VERY long list of agencies to choose from when setting up an account. Users have a tendency to choose the first option that will work, instead of the option that is best for them.

**Expected behaviour** 
I'd like to investigate organizing these options in a better way. We could either provide a progressive disclosure style double select box or organize the current select box with sections.

**Comment by kathreenriel** [comment]
@mandily-p shall we tackle this next week?

**Comment by mandily-p** [comment]
Let's do it!
