### ISSUE TITLE
Sign up/Login: Create modal box

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#527]
Currently, when a user signs up they are directed to a sign up page. Create a modal box that allows users to sign up with Facebook, Google or email. 

1. "Track Your Professional Development" is inserted near the top of the modal box below the logo
2. Agreement to terms and conditions is by checkbox
3. Terms of Service is hyperlinked to Terms and Service page
4. Sign Up button  automatically registers a user
5. Sign Up button links registered user to their profile page
6. Login option link is at the bottom of the modal box. 
7. All users are automatically signed up as Learners

Updated mocks:
![login no social media](https://user-images.githubusercontent.com/20425828/44673215-b7211580-a9df-11e8-9a8f-a3692fc57087.png)
![register no social media](https://user-images.githubusercontent.com/20425828/44673216-b7b9ac00-a9df-11e8-8c84-05a00df52545.png)

**Comment by mandily-p** [comment]
We might want to break this up into a couple of stories. 

1. Create a modal with email and password sign up
2. Add social media sign ups


On another note - it looks like when I upgraded computers the icon font I use didn't load properly. That box with the question mark inside should be an eyeball to show the password in plain text. It would switch to the eyeball with a slash through it when the user is viewing the password in plain text. Here's the eyeball icons that will be needed for the password field.

[Icons.zip](https://github.com/BCcampus/eypd/files/2322353/Icons.zip)

**Comment by mandily-p** [comment]
Login is pretty similar in the look, but with a couple of language changes at the bottom.

![login](https://user-images.githubusercontent.com/20425828/44672725-24cc4200-a9de-11e8-8b05-a355bd8a5a00.png)

**Comment by mandily-p** [comment]
Old mockup (just for archiving purposes)
<img width="715" alt="44629816-3f80b700-a909-11e8-9dfb-d6f1145d4f94-1" src="https://user-images.githubusercontent.com/20425828/44673313-08310980-a9e0-11e8-8490-f1d0610577e1.png">

**Comment by kathreenriel** [comment]
Closing for now. We need to consider more implications tying in social media accounts.
