### ISSUE TITLE
Revise the Sign up and Profile page 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#528]
The current sign up page has a high bounce rate and we need to work on reducing it. We think that we can get more people to sign up by creating an account with only an email and password needed, and leaving the rest of the information to be collected on the profile page. This page would be available at any time, not just when the user is signing up.

The only mandatory fields on either account are the email and password, however if an organizer wishes to post an event, they must fill out all of the fields on the page so that we can verify that they're a real organization.

1. Add an info box message area. Learners and Organizers get shown two different messages.

2. Create an account section including: 
  a) Email field
  b) Password with edit link "Change password". A text box with a save button to it's right would appear if the user chose to edit this. There only needs to be one field here, not a second for validation.
  c) Account type: (option can be either learner or organizer) in plain text.
  d) In a learner account, there would also be instructions for the user to upgrade their account to an organizer.

3. Create a profile section including:
  a) Profile picture 150px square with a link to upload a new one
  b) First name and last name (these are currently one field)
  c) Organizers would see an Agency/Institution dropdown with the same options list as what's currently shown
  d) Organizers would see a Department text field
  e) City (Same as the current form)
  f) Province (Same options as the current form) with BC selected as default.

4. Show professional interests to learners only. These would all be selected by default. This would include:
  a) A group of checkboxes that are topics of education
  b) A group of checkboxes that are more about the management of education
  c) A checkbox to allow users to indicate they're interested in online courses
  d) A checkbox to allow users to receive notifications when new events that they're interested in are added.

5. A save button.
If the user makes changes to this page and tries to navigate away without saving, prompt the user to save before navigating away.

6. Related to #4 - email 
  a) The notification email should include the following text (or something similar) You are receiving this email because you've opted in to get notifications about new events as they're added. To change your professional interests and notification settings, [adjust your profile settings](#).
<img width="549" alt="profile page" src="https://user-images.githubusercontent.com/16693738/44629980-d484af80-a90b-11e8-8091-21cb7691f22e.png">

**Comment by mandily-p** [comment]
@kathreenriel The mock was updated since I sent this one last week. I ended up creating two different ones - one for learner and one for organizer. 

I was also chatting with a friend tonight about the bounce rate on the current signup form and she asked if all of the fields were needed and adhered to FOIPPA. You may be able to figure out what you're allowed to ask for and what not - here: https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/foippa-manual/purpose-collect-personal-information

**Comment by mandily-p** [comment]
For conversation during sprint planning, here's the updated mocks:

![profile learner](https://user-images.githubusercontent.com/20425828/44672212-a15e2100-a9dc-11e8-820b-c925128576b0.png)
![profile organizer](https://user-images.githubusercontent.com/20425828/44672213-a1f6b780-a9dc-11e8-9fc8-3d8889132cab.png)

**Comment by kathreenriel** [comment]
Moving this to the Sprint for November

**Comment by kathreenriel** [comment]
Stay tuned for most recent mock-ups for the Sign up and profile page.

**Comment by mandily-p** [comment]
I broke this up into multiple issues. @kathreenriel and @bdolor Can you review these and make sure we have enough information please? We'll also need to chat about whether we want to through these new issues into this sprint or leave them until later - or a combination of the two. As long as the information contained in this ticket is covered in the others, I think it might be best to close this one and start fresh.

#602 Persistent messaging
#606 Email notification: Remind users to complete their profile
#608 Modal sign up form
#609 Revised profile page
