### ISSUE TITLE
Sign up form: Organization drop-down menu

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#529]
Current drop down menu of organizations on sign up form is very long. Reorganize drop-down menu so that organizations are grouped into broader categories that users may choose from. 

Aboriginal
Child Development/Special Needs
CCRR
Community Organization? 
Government
Independent Business
Health
Post-Secondary Institution
School District

**Comment by kathreenriel** [comment]
<img width="512" alt="sector" src="https://user-images.githubusercontent.com/16693738/44745325-3edc5200-aabc-11e8-873d-c83e0f60d712.png">

@paulagaube @mandily-p What do you think of this alternative to menus and submenus?

**Comment by paulagaube** [comment]
I like this @kathreenriel. I like that people can type in their "other" sector so we can track and add categories later if we need to.

Would we still also ask where our users work? (Name of organization or company?) 

I am thinking about the information the advisory committee wants to collect. For example, they were interested to know which CCRRs had not signed up for an account yet, and who had posted the most events (and least). Will we still have enough data to collect this information if we don't include a sub-category?

**Comment by kathreenriel** [comment]
Okay let's Keep "Name your place of Work" and the domain plug in but  go with the broader categories that are visible on the form.  @alex-418 Is this something we can do on the front end or does this need to be coded?

**Comment by alex-418** [comment]
@kathreenriel pretty sure this is a profile field you can edit in the dashboard yo please. Validate by domain only cares about the whitelist of domains, it uses that to check against the email addres they enter.

**Comment by mandily-p** [comment]
The more I think about this form, the more I think we should tell the users why we're collecting this information. People are way more trusting and likely to fill things in if they know how their person information is going to be used. And no one will ever read the terms and conditions or privacy policy to figure that out. So I'd like to remind them here.

I'm not 100% sure on the reasoning for collecting this info (and like the users, I don't want to go read the fine print). @kathreenriel Can you craft up a one or two liner that tells users how we're using this data?

**Comment by mandily-p** [comment]
@kathreenriel or @paulagaube before I bother the guys I was wondering - do you know where these settings are? I keep looking in the admin and I just don't see them. :/

**Comment by paulagaube** [comment]
Look in Users > Profile... or is it Profile Settings? 

Edit the group with the organizations. 

Paula

______________________
Paula Gaube
Project Support Coordinator 
BCcampus

**Comment by mandily-p** [comment]
We don't have the capability to add in a dynamic "other" field without sone extra code. In lieu of that, I added the other option, and thought if anyone selects it and we want to know more - we can reach out to that person.

**Comment by paulagaube** [comment]
@kathreenriel @mandily-p The "Sector" drop-down list was only added to the sign up page of the PROD site, so I added this to CERT site so they match.
