### ISSUE TITLE
Reduce font size of headings on mobile

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#533]
### Description 
The page title font size on mobile devices is huge! (48px high to be exact) It's the same as the desktop site. Sometimes that works, but not in this case. Let's shrink down that heading (and the h2 while we're at it so they're proportional) so it's more reasonable and each word doesn't fill a whole line on a mobile device.

**Expected behaviour** 
```
@media mobile {
  h1 {
    font-size: 32px;
  }
  h2{
    font-size: 26px;
  }
}
```

This is what it currently looks like:
![screen shot 2018-08-27 at 4 12 39 pm](https://user-images.githubusercontent.com/20425828/44691778-ddad7380-aa14-11e8-96e2-b53cf87a04d2.png)

**Comment by kathreenriel** [comment]
@mandily-p I'll need help validating this :)
