### ISSUE TITLE
User friendly layout of "edit events" page

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#534]
### Description 
The delete and duplicate functionality of each event is smushed right up against the title of the event. We can make it more clear for users that this functionality exists, and also make the table easier to scan, by moving that functionality to the right side of each row and spelling out what it does. 

**Current screen**
The current screen displays "Delete" underneath the title of the event and has a tiny "+" for duplicating events. 
![screencapture-eypd-bccampus-ca-edit-events-2018-08-28-09_27_34](https://user-images.githubusercontent.com/20425828/44736916-61af3c00-aaa5-11e8-91c5-8f0abead4e61.png)

**Desired design** 
We create 2 new columns at the end of the table for the delete and duplicate functionality
Remove the empty cell between the event name and location. 
![screencapture-eypd-bccampus-ca-edit-events-2018-08-28-09_27_20](https://user-images.githubusercontent.com/20425828/44736909-5cea8800-aaa5-11e8-99d6-45c3b51195cd.png)

**Comment by kathreenriel** [comment]
@mandily-p reviewed this but it looks similar to the original. Please clarify what to validate

**Comment by mandily-p** [comment]
It needs to be merged into dev before you can validate :)
