### ISSUE TITLE
Indicate "copy" when user duplicates event

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#535]
### Description 
We give organizers the option of duplicating events, but we give no indication that the event they're creating has been duplicated. We need to reassure them that they aren't editing their original event, and also help reduce duplicate events in the system.

The improved design includes:
- remove `Edit event` and the quotation marks
- a visual tag that identifies a duplicated event
- add the word "copy" to the event name in the field
- change the submit button text to `Post Copy of Event`

```
.pill {
    background: black;
    border-radius: 100px;
    color: white;
    font-size: 12px;
    padding: 3px 10px 5px;
    vertical-align: top;
}
```
**Current design**
This looks like they're editing an event, not creating a copy of one
<img width="1163" alt="screen shot 2018-08-28 at 9 44 23 am" src="https://user-images.githubusercontent.com/20425828/44737770-bd7ac480-aaa7-11e8-9835-10c836934dbb.png">
<img width="1163" alt="screen shot 2018-08-28 at 9 45 37 am" src="https://user-images.githubusercontent.com/20425828/44737782-c66b9600-aaa7-11e8-89a4-dcdcb42b53d4.png">

**Desired design**

<img width="1164" alt="screen shot 2018-08-28 at 9 51 54 am" src="https://user-images.githubusercontent.com/20425828/44737993-61647000-aaa8-11e8-98f7-721aedf07a04.png">

<img width="1163" alt="screen shot 2018-08-28 at 9 48 01 am" src="https://user-images.githubusercontent.com/20425828/44737724-9e7c3280-aaa7-11e8-9b93-7fb0069eeb35.png">

**Comment by kathreenriel** [comment]
Needs documentation for Organizers in FAQ so that many duplicate events are not posted.
