### ISSUE TITLE
Analytics: Add marketing campaigns reporting to EYPD site

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#536]
### Description 
We'd like to be able to track conversions of our goals for the EYPD site. To do this, we need to install this plugin: https://plugins.matomo.org/MarketingCampaignsReporting

The conversion we'd like to track is how many new learner and organizer signups we're getting from the facebook page.

**Comment by bdolor** [comment]
I believe this is a matomo plugin, not a WP plugin.

**Comment by mandily-p** [comment]
@kathreenriel I'd still like to install this plugin on Matomo. Is there a process for that? or can I just go ahead and do it?

**Comment by mandily-p** [comment]
An investigation of goals and campaigns needs to be investigated prior to making a decision on this. If our requirements aren't met, @Kathreen will follow up with George.

**Comment by kathreenriel** [comment]
Understanding how to use the Goals functionality within Matomo is the direction of this ticket.
