### ISSUE TITLE
Add Facebook icon to the footer

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#537]
### Description 
As a learner or organizer,
I want to be able to see the Facebook link at a glance,
So that I can check out EYPD's social media posts.

Add this Facebook icon to the left side of the Facebook link: `https://www.facebook.com/BCEYPD/`
[facebook.svg.zip](https://github.com/BCcampus/eypd/files/2333529/facebook.svg.zip)

**Comment by brettjforsyth** [comment]
@bdolor Can we close this issue as we are going to put it in through the menus admin? Also should we capture that in the documents somewhere?

**Comment by bdolor** [comment]
I agree, labelling it non-dev and keeping it open is appropriate.

**Comment by paulagaube** [comment]
@brettjforsyth This Facebook "f" looks good in the footer. Tested on my iPhone and in Windows browsers.

As this link is going to an external site, is it possible to also add a  **add target="_blank" ** (or similar), so when clicked, a new window/tab is opened)?

**Comment by kathreenriel** [comment]
@brettjforsyth Yes, It would be good to have this open in a new tab/window

**Comment by brettjforsyth** [comment]
I have added this in (see https://support.vamtam.com/support/solutions/articles/202348-how-to-add-a-target-blank-on-a-wordpress-menu-item-or-other-elements for details on how to do this in the future).
@kathreenriel @bdolor Point of clarification: How will this be migrated to PROD since its added through the admin?

**Comment by kkilbey** [comment]
The Facebook icon looks good to me, and the link opened in a new tab each time. Checked on Chrome, Firefox, Edge, and Safari (iPhone 6).

**Comment by paulagaube** [comment]
The Facebook "f" icon now appears on the footer menu of PROD. 
Tested and working on Chrome, Firefox, Edge, Internet Explorer on PC; and Chrome on iPhone.

I updated the menu here: Appearance > Menus > "Contact Menu" > Custom Link for Facebook
Added this in the "Navigation Label" box: 
<i class="fa fa-facebook"></i> Facebook

Went up to "Screen Options" and dropped down the menu.
Under "Show advanced menu properties", click "Link Target" and then a checkbox appeared in the expanded Facebook Menu item. Clicked the link "Open in a new tab".

@kathreenriel would you test that this is displaying and working properly please?

**Comment by kathreenriel** [comment]
Yes this works as expected.
