### ISSUE TITLE
Content: About us page

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#540]
### Description 

1. On the about page, we link to the website, and tell the user to contact us at an email address that isn't a link. With @kathreenriel 's permission, I'd like to remove both the link to the website and the contact CTA. 

2. I'd also like to remove the links and text earlyyearsbc.ca and replace it with plain text in the Q&A's down below.

3. And I'd like to remove the bullets from the page. 

@kathreenriel If you're ok with this, Can you pop it into the sprint backlog for me and I'll get it fixed up?

![screencapture-earlyyearsbc-ca-about-us-2018-08-29-17_28_12](https://user-images.githubusercontent.com/20425828/44822686-2a2db600-abb1-11e8-88ea-1d2d4177f933.png)

**Comment by kathreenriel** [comment]
@mandily-p

**Comment by mandily-p** [comment]
My apologies @kathreenriel I feel like this is the first project all over again. I didn't read the page, but rather was only looking at the styling of it. I should have known that if even I didn't want to read it, it might not be the best format for our users either. 

I've went ahead and wrote a more story-like and hopefully engaging about page that I'd like to use instead of the copy that's currently on the site. I've written it in [Google Docs](https://docs.google.com/document/d/1a5xhc6fPodaR9gkZ4VyvG5Gv6YRHY_x-_aKU6PvnBMg/edit#) so that you, @paulagaube and I can collaborate on it. 

I'd like to use that copy, and post the video at the bottom of the page.

It might also be nice to include a picture of the group that is working regularly to put the site together. People always like seeing the faces behind an organization. It helps draw them in. We can save that thought for later, but right now, I'd like your thoughts on the attached copy :)

**Comment by kathreenriel** [comment]
@paulagaube would you read this over please.

**Comment by paulagaube** [comment]
@kathreenriel @mandily-p I'm not a fan of all the text on that About Us page. The first paragraph is government jargon and makes my eyes glaze over. The second paragraph is a better place to start, though needs some editing for tense and clarity.

It seems like this text is really about the EYPD project, and not About Us (Which I think is BCcampus and the BC Office for the Early Years, and possibly the Advisory Committee.)

I'd like to totally rewrite that page, when I have a bit more time. (i.e., not this afternoon)

**Comment by kathreenriel** [comment]
@paulagaube @mandily-p  Ha..ha..I'm chuckling...the "eye glazing" effect is due to my edits. Amanda's version was more approachable. I agree now when I read it again the second paragraph gets my attention. Given that Alex is not pushing anything to production until Wednesday there is time for edits.

**Comment by paulagaube** [comment]
@kathreenriel @mandily-p I really do like the text in the image shown above much better. It's clean, clear and organized. "Our Goals" and "Fast Facts" makes a lot of sense (but removing the second instance of "Our Goals" in the paragraph below the video). 
Could change "Fast Facts" to "About the Project" but that is not quite as fun as "Fast Facts".

**Comment by mandily-p** [comment]
We could also rename the page to "About" Instead of "About us" instead of rewriting it about BCcampus. Right now, there's no information on what the project is about anywhere else on the site. Although that being said, I can write it into a new home page.

**Comment by kathreenriel** [comment]
Added in some graphics and subtitles to break up the text .
