### ISSUE TITLE
Contextual validation errors

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#541]
### Description 
Currently when a user submits a form that has errors, we display a message at the top of the screen about where those errors are. 

**Expected behaviour** 
I'd like to give the users more context of what fields need to be filled in/corrected, by highlighting them with a red border.

**Current page**
![screencapture-earlyyearsbc-ca-post-event-2018-08-29-21_32_02](https://user-images.githubusercontent.com/20425828/44829876-c49ef100-abd3-11e8-8ebc-1f38cd522122.png)

**Desired design**
![screencapture-earlyyearsbc-ca-post-event-2018-08-29-21_37_24](https://user-images.githubusercontent.com/20425828/44829893-cc5e9580-abd3-11e8-93e5-99113b6c710e.png)

**Comment by dshaykewich** [comment]
Won't fix.
