### ISSUE TITLE
Content: Rename "Edit events" to "My posted events"

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#543]
### User story
As an organizer,
I want to be able to see my posted events at a glance
So that I can edit, remove, and add new ones as quickly as possible.

### Description 
The current `Edit events` page is the perfect dashboard for organizers - they can do everything from this page. Unfortunately the title and link to the page in the nav makes it look like users can only edit events here. I'd like to rename this to "My posted events" 

**This is a content issue in that we can update the page title in the WP-admin, but I'll need to go into the code to update the nav link text.**

**Comment by kathreenriel** [comment]
I disagree with this point. I think the audience of Organizers is not likely to change and they are used to Edit Events. Also Edit Events fits with all the other active descriptions. Find, Post,
