### ISSUE TITLE
Remove our IP's from analytics

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#551]
### User story
As a UX researcher,
I want to make sure that the user data I am looking at is only from users visiting outside of the EYPD office/contractors
So that I know the data isn't skewed

### Description 
Filter out IP addresses from the analytics tools. I'm not sure we should be posting them in a public repo though. Will set up a [spreadsheet](https://docs.google.com/spreadsheets/d/1GR9gq1n0W2Iz8cLIs-UijtYf2rn-C6I9jdYU3mqpl14/edit?usp=sharing) instead.

**Comment by bdolor** [comment]
Victoria and Vancouver office IP's are already excluded from being tracked on all websites.
