### ISSUE TITLE
Homepage: Extend the number of Search fields

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#557]
### Description 
Currently, organizers can post events that have phrases like, "Registration cannot be completed online. Please call to register" and those events will appear in a search for "online". I'd like to restrict searches for "online" to only search the category so that the results are better aligned with what a user is searching for.

**Comment by mandily-p** [comment]
This would probably also be useful for TLPD.

**Comment by kathreenriel** [comment]
This is related to issue #86

**Comment by kathreenriel** [comment]
This issue needs to be refined to include the needs as described in #86 and #403

**Comment by kathreenriel** [comment]
This is also connected to #550

**Comment by mandily-p** [comment]
@kathreenriel you asked for a mockup, but I'm not sure what you need mocked up. Can you give me some details please?

**Comment by kathreenriel** [comment]
Details found in Trello https://trello.com/c/BRNthyIV/49-eypd-homepage-mock-up-more-search-options-that-include-a-format-drop-down-menu-cost-and-sponsor

**Comment by kathreenriel** [comment]
Moving this to the Sprint for next week

**Comment by kathreenriel** [comment]
@mandily-p this design would replace the current view found on https://earlyyearsbc.ca/events/ correct?
I also wonder how this would render on a phone. How about the Cost, Location Category being accordian components thus less text on one page

**Comment by mandily-p** [comment]
Yes, these are recommendations to improve the current events page.

## Mobile
On a phone there would be a text label, "filter". When the user clicked on that, the whole screen would be the filters. Once selected, they could close the screen and see the filtered view of events. It would be similar to [this site](https://tommyjohn.com/collections/womens-underwear)

## Side filter bar
There's pros and cons of collapsing and expanding the side nav.

|  	| Pros 	| Cons 	|
|-----------	|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| Collapsed 	| - Less visual clutter, although with it being in it's own section, it's easily ignorable if the user just wants to browse in the main section  <br>- All filter titles are viewable on small screens if there are a lot of options underneath 	| - Easier to miss as it has less prominence on the page  <br> - Requires an extra interaction to use it  - Lose the opportunity to intrigue users with the options available 	|
| Expanded 	| - Users know what all their options are without any extra interaction  <br>- Users can be intrigued to explore when they see hints of what's contained within 	| - If there are a lot of options, they may not all be viewable on a small screen.   <br>- More visual clutter, although with it being in it's own section, it's easily ignorable if the user just wants to browse in the main section 	|

There's also the option of somewhere in the middle, where the first section is expanded to demonstrate to the user that there are more options hidden under the other titles, but it keeps it short enough that it's still contained on the screen without needing to scroll.
