### ISSUE TITLE
EYPD Notifications: Not sending to all registered users

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#558]
This morning, (October 16, 2018) I activated notifications on the production site EYPD. The logs indicate that the notification was only sent to 20 people and I think the notification was sent out twice. I randomly checked those registrations who did not receive the notification and their extended profile  indicates that notifications are permitted. 

**Expected behaviour** 
Notifications are sent to all the registered users of EYPD. 

**Actual behaviour** 
Notifications are only being sent to 20 people 

### Steps to reproduce the problem

It's ideal that the problem isn't reproduced in order to minimize unsubscription on the part of those 20 users.

**Comment by bdolor** [comment]
I received a notification this morning (just one at 7:26am) and it looks great. The 20 at a time is meant to slow the distribution down to avoid getting flagged as a spammer. If the cron job that breaks it up into chunks isn't triggering there can be a few things to look at. I notice the plugin is disabled on production. Is there risk in leaving it enabled?

**Comment by kathreenriel** [comment]
My BCcampus and gmail account did not receive a notification so after a few minutes I didn't think it was working. I'll leave it activated and see what happens tomorrow morning.

**Comment by kathreenriel** [comment]
Oh oh....I activated plugin to send a notification tomorrow morning but was sent immediately. I deactivated it again because I'm not sure if this will send a duplicate email tomorrow morning too so I'm going to deactivate and try again in a week's time.

**Comment by bdolor** [comment]
I should walk you through what to expect with that plugin...it sounds like it's working correctly, but perhaps not in line with expectations. Could speak to better documentation on our part. It's likely that everyone received a notification today, which I think is what we want.

**Comment by kathreenriel** [comment]
Yes, a walk-through would be great!
