### ISSUE TITLE
Add FAQ Duplicating an Event

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#559]
Write a question for the process of how an Organizer follows the process for duplicating an event. This needs to be done when #535 is completed.

**Comment by kkilbey** [comment]
This FAQ already existed on Cert, so I have added it to Prod as well. Here is the text for reference:

How do I duplicate an event?

To duplicate an event on the Early Years web portal:

1. [Log in](https://earlyyearsbc.ca/wp-login.php?redirect_to=https%3A%2F%2Fearlyyearsbc.ca%2F) as an Organizer.
2. Click “Edit Events” at the top of the page.
3. If the event you wish to duplicate appears on your list of posted events, click the “+” sign to the right of the event’s name.
4. Make the required changes to the duplicated event (e.g., date of event) and click “Update Event” at the bottom of the page.

** If the event you would like to duplicate does NOT show up in your event list, use the [Contact Us](https://earlyyearsbc.ca/contact-us/) form to send details about the event you would like to duplicate. **

I have also removed an outdated FAQ, "How can I copy one of my old events to make a new event?" by changing it to "Draft" on both Cert and Prod. However, I would like to delete this FAQ entirely to avoid confusion on our end, as the answer is no longer accurate. @paulagaube do you think it's okay to delete?

**Comment by paulagaube** [comment]
Thanks, @kkilbey , yes, delete that old FAQ if it is confusing. 

This is done on PROD.
