### ISSUE TITLE
Forum Home Page: Change Delete title to hide

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#585]
Currently the delete function is inconsistent in its purpose. While on the Forum homepage when a user clicks on delete beside a topic or response it hides that connected content from the homepage feed but if a user clicks on delete beside their announcement the announcement is deleted. 

Proposed Change:

1. Change the delete button to "hide" when it appears beside a topic or response on the forum homepage
2. Keep the delete button "as is" beside the announcement but warn the user (with a modal message?) that they are about to delete an announcement.

**Comment by mandily-p** [comment]
Does the 1st button hide it just from the user that hides it, or everybody? It would be nice if we could either put that context in the button text or at least in a hoverable tooltip.

**Comment by mandily-p** [comment]
Chatted with Kathreen. The hide button just hides the event from the user. Let's use the label "Hide from view"

**Comment by brettjforsyth** [comment]
@kathreenriel @mandily-p can I get a screen shot and URL for this? I can't find a trash button

**Comment by kathreenriel** [comment]
https://eypd.bccampus.ca/groups/community-of-practice-appetite-to-play/
<img width="812" alt="hidefromview" src="https://user-images.githubusercontent.com/16693738/49171848-5366fb00-f2f4-11e8-8c51-0deb75d7f3e1.png">

<img width="815" alt="announcement delete" src="https://user-images.githubusercontent.com/16693738/49171826-4813cf80-f2f4-11e8-8109-f64efb86be86.png">

**Comment by mandily-p** [comment]
I'm not sure how fontawesome works here, but here's two icons that you can use for hide and delete.

<img width="200" alt="screen shot 2018-11-29 at 12 18 59 am" src="https://user-images.githubusercontent.com/20425828/49208357-6e755180-f36c-11e8-8f80-7ed1b91800fd.png">
<img width="193" alt="screen shot 2018-11-29 at 12 19 12 am" src="https://user-images.githubusercontent.com/20425828/49208358-6e755180-f36c-11e8-8ba6-966597cd5777.png">
