### ISSUE TITLE
Dashboard for organizers

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#588]
The Organizers currently go to the same page as the learners, where they'll see a bunch of features that they don't need. I'd rather send them to their own type of dashboard where they can manage all of their existing events.

I think I've heard stories about some organizers posting a hundred events at a time, in which case, I think it would be valuable to give them the same kind of filtering options in the sidebar that we offer our learners. Except we would swap out location for status.

![my eypd - desktop organizer](https://user-images.githubusercontent.com/20425828/49096228-ffd6ad80-f21e-11e8-99dd-ceaec0ab8647.png)

**Comment by mandily-p** [comment]
Related to #466 Unique nav links for each user type: non-logged in, learner, organizer
Related to #557 Adding filters to the event page

**Comment by kathreenriel** [comment]
@mandily-p We don't want Organizers modifying past events as this would interfere with the records of past events that people have recorded as attended. But we could allow for Organizers to duplicate an event in this interface.

**Comment by mandily-p** [comment]
Ooh! Good catch! I was just throwing everything on the page.

I agree - Past events don't need share or edit buttons. I wonder if they need anything else though? Maybe the number of people who said they were going to attend? What do you think?

**Comment by dshaykewich** [comment]
Won't fix.
