### ISSUE TITLE
Add cost column to the events page

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#592]
### User story
As a learner,
I want to be able to see the cost of each event at a glance,
So I can decide if it's within my budget without needing to view the event details.

### Description
Add a cost column to the events page with a sort icon to allow users to sort events by low to high, or high to low cost.

**Comment by kathreenriel** [comment]
I really like this idea. We have encountered some challenges with applying filters to tables. Please documentation in #504

**Comment by mandily-p** [comment]
Ah, I missed that this was a problem that could not be solved previously. At the very least, I'd like to add cost to the table, even if we can't add sorting right now. What do you think @kathreenriel? Should we revise this ticket to only include adding cost as a filter?
