### ISSUE TITLE
Add delete and edit icon and functionality to the past events table

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#598]
Users may want to remove events they haven't attended so that their list isn't so cluttered. We can allow them to do this by including the same functionality as we do in the "upcoming events" section.
![screen shot 2018-11-30 at 9 40 32 am](https://user-images.githubusercontent.com/20425828/49305451-28131600-f484-11e8-9ca1-0d91df9d1e2d.png)

**Comment by dshaykewich** [comment]
Won't fix.
