### ISSUE TITLE
Persistent messaging

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#602]
## User story
As a site owner,
I want to remind learners and organizers to fill out their profile 
So that I can track who's signing up for our services.

As a site owner,
I want to remind learners to fill in their certification date,
So that we can set them up to use the site features as best as we can.

As a UX designer,
I want to provide a persistent messaging solution for site owners to communicate to site users,
So that we don't need to custom code a solution every time a new message is needed.

## Description 
A persistent messaging system with a user-friendly UI so that site owners and admins can manage important messages/reminders that need to be communicated to users.

## Acceptance criteria
- Persistent messaging across all site pages
- One message for learners who have not completed their profile
- One message for organizers who have not completed their profile
- One message for users that have not validated their email address
- No message for non-logged in users
- Messages may need to be combined if multiple conditions exist
- Message is hidden after a user completes the related request.
- WP admin to configure
  - Text field to enter text that users will see
  - Audience options include : Non-logged in, learners, organizers

## Mockup
To be completed after the appropriate technical solution is decided upon.

**Comment by dshaykewich** [comment]
Won't fix.
