### ISSUE TITLE
tooltip regression

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#604]
### Description 

A regression in the tooltip behaviour has been introduced recently

**Expected behaviour** 

Links in the tooltip area should bring unauthenticated users to the appropriate page.

**Actual behaviour** 

When unauthenticated, hovering over any of the main menu items triggers the tooltip functionality. Clinking on the menu items to generate the tooltip works, and hovering over the links in the tooltip area for 'sign up' or 'login' reveals the correct links. The action associated with clicking the links, however, fails to direct to the appropriate page. 

### Steps to reproduce the problem

go to the homepage on cert, unauthenticated, click on the main menu items, click on the login or sign up links.

**Comment by brettjforsyth** [comment]
@bdolor I can recreate on CERT but not my local. Are you seeing it on your local? I noticed some double quotes were missing so I have added them in there. Not seeing any JS issues.

**Comment by alex-418** [comment]
@bdolor tested this on both trellis/non-trellis local devs, I couldn't replicate the issue with the links, they work as expected for me with these changes.

**Comment by bdolor** [comment]
let's see how it looks on cert then.

**Comment by alex-418** [comment]
Looks okay to me on cert

**Comment by bdolor** [comment]
It still does not work on cert.

**Comment by alex-418** [comment]
Could @kathreenriel or @paulagaube please also test this on cert? Do the tooltip links bring you guys to the appropriate pages?

**Comment by kathreenriel** [comment]
On Mac Safari: None of the tool tip bubbles appear 

On Mac Firefox: All the tool tips work 

On Mac Chrome:Under Post An Event: The Login or Sign Up links  but do not link to their respective pages for unauthenticated users.

**Comment by alex-418** [comment]
Thanks @kathreenriel I'm also on a Mac and works great on both Chrome and FF for me, however Safari is the same results as you.

**Comment by paulagaube** [comment]
@alex-418 I tried on PC / MS Edge browser and after clicking "Post an Event" and "Edit Event", the links to login and sign up work. The links on the "myEYPD" menu item DON'T work on Edge.

Tested on IE and the links DO work, but it looks like I had to click the myEYPD links twice before it would go to the login or sign up screen. I did clear my cache first.

**Comment by kkilbey** [comment]
Check on Chrome, Firefox, Edge, and Safari (mobile)--looks good. Moving to Done.
