### ISSUE TITLE
Promote benefits of sign up to non-logged in users

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#607]
### User story
As a site owner
I want to market the benefits of signing up for an EYPD account to non-account holders
So that we can increase the number of people using the site, and help those people manage their PD more effectively than they are without the use of the site.

### Summary
Create a marketing-esque component that can be used on non-logged in areas of the site to promote the benefits of signing up for an account.

### Acceptance criteria
- Reusable component that can be used on multiple pages
- Advertises benefits (rather than features) of sign up.
- CTA that links to sign up modal
- Located on the events page and the bottom of each blog post

### Mockups
TBD

### Copy
TBD

**Comment by dshaykewich** [comment]
Won't fix.
