### ISSUE TITLE
Custom sort order for event categories

### ISSUE THREAD

**Issue by brettjforsyth** [BCcampus/eypd#611]
### User Story
As a site admin I want to be able to sort the event categories

### Summary 

Currently the "Event Categories" found under the myEYPD section of the dashboard are not sortable. This sort order is also to affect the display of the donut and donut legend on a users myEYPD page. This issue has emerged from conversation in #379 

**Expected behaviour** 

Would like a mechanism, preferably draggable items, that allows for the sorting of the categories. This sort order would also change the display of the donut and donut legend.

### Acceptance criteria

When an admin changes the sort order of items on the Event Categories page the donut and donut legend update accordingly.

**Comment by alex-418** [comment]
Sorting of categories by the admin is now possible on the dashboard on cert  (installed a [plugin](https://en-ca.wordpress.org/plugins/taxonomy-terms-order/).) Please keep in mind that sorting of the donut categories legend is done first by the **%** of the donut that a specific category represents, and then the custom sort order set by the admin. 

The donut data uses the sort order set by the administrator in the following screen (see screenshot):

![sort](https://user-images.githubusercontent.com/17072191/58137656-d6a04400-7be7-11e9-931d-f3ad9c706b27.png)

**Comment by kathreenriel** [comment]
In reviewing #379 I thought that custom sorting  the categories would solve the issue of matching the legend to the donut – as seen in the comments in the illustration.  However, I misinterpreted this logic. I think the custom sort function does not fix the way the legend renders the categories from largest to smallest %.  
<img width="449" alt="Screen Shot 2019-05-22 at 10 15 37 AM" src="https://user-images.githubusercontent.com/16693738/58200061-ba071900-7c86-11e9-98f8-dbba8a4713bc.png">

**Comment by alex-418** [comment]
Just spoke with @kathreenriel on the phone, we will revert https://github.com/BCcampus/eypd/commit/5c27a6a0ebe82ee282b0a6149703825198a727ce to remove the custom sorting behavior from the donut (no longer needed, see #675 instead), but we will keep the sort functionality for use elsewhere (Front end search form)

**Comment by alex-418** [comment]
Donut legend sort order was reverted via cd2b783 and I have started the build process for cert. Please give it a few minutes, the donut will now ignore the custom sort order set in the back-end.

**Comment by paulagaube** [comment]
I can confirm that the custom sort works on the eypd.bccampus.ca home page under the "Search by Category" AND that change does not appear to affect the donut order, which is by ordered by percentage, highest to lowest, AND the colours are showing in the same order as the legend. 
Excellent.

**Comment by kathreenriel** [comment]
Confirmed this too. This needs to be manually changed in the dashboard on Prod.

**Comment by kathreenriel** [comment]
This has been completed on Prod.

**Comment by paulagaube** [comment]
Yes, it looks good!

**Comment by paulagaube** [comment]
@kathreenriel just checking... do you want leave "Administration" after "Middle Years"? The categories drop-down list is not in alphabetical order

**Comment by kathreenriel** [comment]
@paulagaube thanks for checking. I changed the location of Administration.
