### ISSUE TITLE
Remove JS alert from "Save to myEYPD" button

### ISSUE THREAD

**Issue by brettjforsyth** [BCcampus/eypd#612]
### User story

As a user I don't need to see an alert confirmation when clicking on "Save to myEYPD" as there is already a visual loading icon and status message presented when saving events.

### Description 

Currently when you click on the the "Save to myEYPD" button for future events you trigger a JS alert that is redundant. This is found in bookingsform.js on line 13. We currently don't own this file. Related to #520 

**Expected behaviour** 

When you click the "Save to myEYPD" button you only see the loading icon and status messages related to save.

**Actual behaviour** 

When you click on the "Save to myEYPD" button you get presented with a native JS alert modal that you have to click ok on to close. You are also seeing the loading icon and status messages.

### Steps to reproduce the problem

Go to any future event that you are not currently registered for and click the "Save to myEYPD" button.

### System Information

- EYPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by paulagaube** [comment]
One suggestion is to change the text on this pop-up window from:
"Please wait while the booking is being submitted" to 
"This event is being added to your myEYPD page"

**Comment by kathreenriel** [comment]
> One suggestion is to change the text on this pop-up window from:
> "Please wait while the booking is being submitted" to
> "This event is being added to your myEYPD page"

**This event is being added to your myEYPD page** appears to be clearer.

**Comment by alex-418** [comment]
This has been fixed on cert and prod. I was able to remove the the unnecessary alert instead of just editing the text. Owning the file by bringing it over into our theme did not override the plugin file. So as discussed this alert was removed from the bookingsform.js file in the plugin.

**Comment by kathreenriel** [comment]
Great! I've checked this on Chrome, FF, and Safari and it works as expected without the message. 
@paulagaube or @kkilbey would you check this on IE and your phones to see if it works as expected?

**Comment by kkilbey** [comment]
I've tested on Cert and Prod using Edge (PC) and Safari (mobile). Works as expected!

**Comment by kathreenriel** [comment]
No extra messaging on Prod. This is done.
