### ISSUE TITLE
myEYPD: Donut displaying hours disproportionately

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/eypd#616]
### Description 

On the myEYPD page, the Event Summary donut is not displaying certificate hours accurately. The number of certificate hours attributed to an event in the My Past Events table does not align with the way those hours are distributed by category in the donut.

The images below show this issue in my myEYPD page (logged in as organizer). The top three categories beside the donut are associated with the Physical Literacy workshop, listed in the My Past Events table as worth 6 certificate hours. The bottom two categories are associated with the Privacy and Personal Responsibility event, worth 1 certificate hour. However, the top three categories display as 6.6 total certificate hours, while the bottom two display as only 0.4 total certificate hours.
![image](https://user-images.githubusercontent.com/44710357/49660214-e68de800-f9fa-11e8-8b78-6492ed8c0ba7.png)
![image](https://user-images.githubusercontent.com/44710357/49660222-e8f04200-f9fa-11e8-9144-f1c7e48b370d.png)

To test this further, @paulagaube and I added another event worth 1.5 certificate hours, and changed the Privacy event to 6 certificate hours (equal to the Physical Literacy workshop). The donut continued to distribute certificate hours disproportionately to how they are listed in the My Past Events table. In the images below, the Physical Literacy workshop, represented by the top three categories, is listed as 10.2 hours rather than 6. The Privacy event, represented by the fourth and fifth categories, is listed as 2.8 hours rather than 6. And the new event ("Thirsty Thursday"), represented by the last category, is listed as only 0.2 hours rather than 1.5.

Also notable: the centre of the donut displays the total certificate hours as 13.0, when the table lists 13.5 hours total.
![image](https://user-images.githubusercontent.com/44710357/49660691-17225180-f9fc-11e8-96e9-787f9765384c.png)
![image](https://user-images.githubusercontent.com/44710357/49660694-1984ab80-f9fc-11e8-8fa8-2b1c521e9ae6.png)

**Expected behaviour** 

The Event Summary donut displays accurate certificate hours for each event listed in the My Past Events table, even if the event is associated with multiple categories and thus divided into several segments of the donut.

**Actual behaviour** 

The Event Summary donut displays certificate hours disproportionately. Some events are represented as worth more certificate hours than is listed in the My Past Events table, and others are represented as worth fewer hours.

### Steps to reproduce the problem

Log in to a learner or organizer account on EYPD
Visit the myEYPD page to view Event Summary donut and My Past Events table

**Comment by brettjforsyth** [comment]
The issue should be resolved now but I am seeing some rounding errors. If we went to 2 decimals this would get reduced.
This example totals correctly
![screen shot 2018-12-07 at 12 35 13 pm](https://user-images.githubusercontent.com/439832/49663670-5dd47380-fa1d-11e8-8549-dfcd39c48b4c.png)

This one is up .2 on the legend
![screen shot 2018-12-07 at 12 36 45 pm](https://user-images.githubusercontent.com/439832/49663679-662cae80-fa1d-11e8-93ff-9b9d1be5b677.png)

**Comment by kathreenriel** [comment]
@mandily-p what's your thinking about 2 decimal places in terms of visual clarity for the user?

**Comment by kathreenriel** [comment]
@brettjforsyth please leave as one decimal point.

**Comment by mandily-p** [comment]
Just to play devil's advocate, we could do a bit more complex math like what's detailed in this article :) https://revs.runtime-revolution.com/getting-100-with-rounded-percentages-273ffa70252b
