### ISSUE TITLE
Open external links in a new tab

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#618]
** User story
As a site visitor, 
I want to open links external to the eypd site in a new tab, and know that behaviour will occur, before clicking on it,
So that I know what to expect and won't accidentally close my EYPD tab when I'm done with the external content.

** Acceptance criteria
- External link icon is on the right side of each external link
- External link icon does not wrap to a new line without the word to the left of it going with it.
- External links and pdfs open in a new tab/window (based on user's browser settings)

<img width="191" alt="screen shot 2018-12-10 at 5 06 07 pm" src="https://user-images.githubusercontent.com/20425828/49771444-f37e3600-fc9d-11e8-8a9e-73188f49cbb4.png">

**Comment by kathreenriel** [comment]
This requires editing of events manager plugin which requires unknown time and effort. There are disadvantages to providing "new tab" functionality with mobile devices.
