### ISSUE TITLE
Cert. vs Prod.:  Doc "create one" not working on Prod. 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#620]
As a forum moderator and participant I wish to load documents in to the Docs section of the Forum to share/link resources in discussions. 

The "create one" link goes to a 404 page on Prod. The "create one" link on Cert. goes to a "New Doc" page for the user to describe the doc and multiple attachments if necessary. 

**Expected behaviour** 

- Click on Docs in the Forum
- Create and entitle a folder
- click on the folder 
- Create a document in the newly created folder
- Save or Save and Continuing Editing

**Actual behaviour** 

- On Prod. 
- Click on Docs, 
- Click on folder, 
- Click on "create one", "Darn Nothing Found" page appears. 

### Steps to reproduce the problem

- Go to https://earlyyearsbc.ca/groups/appetite-to-play/docs/ 
- Click on the Recipes folder, 
- Click on the link "create one" 
- View "Darn Nothing Found" page. 

### System Information
Word Press 5.0.1
- EYPD: [5.0.1] 
- WordPress: [5.0.1]

**Comment by bdolor** [comment]
@kathreenriel I've copied some template files over from buddypress into the child theme on prod. Can you try this again and let me know if that fixed it?
