### ISSUE TITLE
Forum: remove myEYPD link 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#621]
### Description 
As an Organizer and a Learner I would like to view myEYPD page from the Forum left navigation bar to minimize scrolling to the top right hand corner to access myEYPD.  

**Expected behaviour** 
- Go to https://earlyyearsbc.ca/groups/appetite-to-play/
- Click on myEYPD on the left vertical navigation.
- MyEYPD page opens

**Actual behaviour** 

When a moderator or participant clicks on myEYPD a page opens that says "no events" 

### Steps to reproduce the problem
- Go to https://earlyyearsbc.ca/groups/appetite-to-play/
- Click on myEYPD on the left vertical navigation.
- A page opens that says "no events" 

### System Information
Wordpress: 5.0.1

**Comment by alex-418** [comment]
Done. Can be validated at on a group page on cert, such as: https://eypd.bccampus.ca/groups/appetite-to-play/

Please note: May require clearing your browsers cache.

**Comment by kathreenriel** [comment]
This is complete. The myEYPD option is no longer visible in the Forum .
