### ISSUE TITLE
Forum: Number beside myEYPD link 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#622]
### Description 

Currently there is a number beside the myEYPD link in the left vertical nav bar on the Forum page. This number is a little confusing. The number is currently "0".  What does this represent? The number of training events the user has attended? The number of training events plans to attend? The number of training events on the site?

**Expected behaviour** 
I'm not sure what the best "fix" is but I'm documenting it as an issue because the number may increase or sustain user engagement with myEYPD if the number  accurately depicts some element of the myEYPD page.  I suggest leaving the number and clarifying its purpose somehow. 

- WordPress: 5.0.1

**Comment by alex-418** [comment]
Covered in #621
