### ISSUE TITLE
Collect user data in a survey at the end of their visit

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#625]
**User Story**
As a member of the team who manage and make decisions about the EYPD site,
I want to know what actual users think about their experience on the site,
So that we can make improvements for them.

**Summary**
I'd like to collect free form data and maybe a few answers to specific questions from users in the context of them using the site. We can use this data to prioritize and even create new features and changes.

**TBD**
We need to decide what we should ask.

**Reference**
ICBC displays this modal when a user arrives on their site. 
![screen shot 2018-11-27 at 4 16 22 pm](https://user-images.githubusercontent.com/20425828/50620170-eaeed900-0eb2-11e9-9b42-28f901caf4bb.png)

**Comment by kathreenriel** [comment]
This is addressed in #57
