### ISSUE TITLE
Style forum buttons for consistency with the rest of the site

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#630]
### Description 
A while back we styled the site buttons so that they were consistent throughout. When we added the forum there were new button styles that are more specific than the site-wide ones. I'd like to make these buttons look like the rest of the site as per #419

**Expected behaviour** 
Button should look like a button consistent with the rest of the site.
See styling notes in #419 

**Actual behaviour** 
Button looks like regular text.
![screen shot 2019-01-10 at 9 32 26 am](https://user-images.githubusercontent.com/20425828/50986105-c5695d00-14ba-11e9-809a-5203012b59ac.png)

### Steps to reproduce the problem
current button style can be seen here: https://earlyyearsbc.ca/groups/appetite-to-play/forum/topic/this-is-a-test/

**Comment by paulagaube** [comment]
@alex-418 where do I need to go to validate this?

**Comment by kathreenriel** [comment]
In a forum post or reply

**Comment by kathreenriel** [comment]
This styling has been updated.

**Comment by paulagaube** [comment]
Thanks. Cleared my cache and see the new button styling now. :)
