### ISSUE TITLE
Table header text should be dark for optimal contrast

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#631]
### Description 
The table header row text in the forum is displaying very light text in all but the last column. 

**Expected behaviour** 
The table header row text should be the dark/black colour we use for text so that it's easiest to read.
The "tags" column is the correct colour of text. Please use this same value for the rest of the table head.

**Actual behaviour** 
There are two different styles of tables (one is just an unordered list)

1. The table header row text is light grey on a white background. This makes it difficult to read.
You can see an example of this here: https://earlyyearsbc.ca/groups/appetite-to-play/docs/
![screen shot 2019-01-10 at 9 38 34 am](https://user-images.githubusercontent.com/20425828/50986715-6278c580-14bc-11e9-89ea-1397a26f14a9.png)

2. The unordered list that looks like a table has a very light grey background with white test. This makes it difficult to read. 
You can see an example of this here: https://earlyyearsbc.ca/groups/appetite-to-play/forum/
![screen shot 2019-01-10 at 9 51 08 am](https://user-images.githubusercontent.com/20425828/50987168-b59f4800-14bd-11e9-96c2-3dc43538ca3b.png)

**Comment by alex-418** [comment]
Completed via https://github.com/bccampus/eypd/commit/81c77cc4e54e6e21a0c1242794cc1ef5602e81d6

**Comment by kathreenriel** [comment]
The headings are now clearer!

**Comment by paulagaube** [comment]
@kathreenriel @alex-418 I have an issue with the Table Header row. The word "Topic" is not Bold but the other Headings in the top row are. Is this a deliberate choice or an oversight? I'd prefer to see Topic in Bold to match the other headings.
<img width="686" alt="ForumTableHeaderRow-bold" src="https://user-images.githubusercontent.com/26391359/58291370-04b18f80-7d72-11e9-99f5-6d20c9f36cd1.png">
