### ISSUE TITLE
Forum: headings and alignment buttons in tinymce

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#637]
### Description 

The editor in the forums (bbPress) has by default the following buttons, but the Headings select list, and alignment buttons get stripped out. 
![tinymce](https://user-images.githubusercontent.com/17072191/51064719-fa0e0f00-15b5-11e9-9196-4496256b0fec.png)

**Expected behaviour** 

Using headings and alignment should result in the expected formatting. 

**Actual behaviour** 

The html gets filtered out, resulting in the code tags showing as text like `<h1></h1> `and `<text align="center">`

### Steps to reproduce the problem

Reply to a forum topic as editor or lower, add heading or alignment to your reply, and submit it. 

(Developers note: these non functional buttons were disabled via #636, to enable them remove the line which limits the buttons, and use `$args['tinymce'] = true` instead.)

**Comment by kathreenriel** [comment]
Discussion with @alex-418 alerted us disadvantages to giving users access to headings which may affect SEO etc. The editor will remain as it is.
