### ISSUE TITLE
Changes to Professional Interests checklist on Sign-Up page

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/eypd#640]
### Description 

On the prod sign-up page, there is a typo in the list of professional interests. "Child Grown and Development" should read "Child Growth and Development"
![image](https://user-images.githubusercontent.com/44710357/51197937-b6fab700-18a7-11e9-92f4-544c8837fab8.png)

Additionally, this checklist does not exist on the cert Sign Up page and needs to be added.

**Expected behaviour** 

"Child Growth and Development" is one of the options in the Professional Interests checklist. This checklist appears on both cert and prod.

**Actual behaviour** 

"Child Grown and Development" is one of the options in the Professional Interests checklist. This checklist appears only on prod.

### Steps to reproduce the problem

On Prod
1. Visit the prod site, unauthenticated
2. Click the "Sign Up" link in the upper right-hand corner
3. Scroll down to the Professional Interests checklist to see typo

On Cert
1. Visit the cert site, unauthenticated
2. Click the "Sign Up" link in the upper right-hand corner
3. Note the absence of the Professional Interests checklist

**Comment by bdolor** [comment]
These are fields that don't have any connection to code that we have control over...these are buddypress extended profile fields which can be accessed via the dashboard `Users->Profile Fields`

![image](https://user-images.githubusercontent.com/2048170/51200193-a77e6c80-18ad-11e9-8e7d-8aed9acc6e9f.png)

**Comment by kkilbey** [comment]
@bdolor thanks! I have corrected the typo on prod and added this checklist to the cert sign-up page.

**Comment by kkilbey** [comment]
As per our discussion in the stand-up meeting this morning, I have removed the Professional Interests fields  from Cert and Prod. As BuddyPress User Profile Fields, they were irrelevant to the Professional Interests categories on the myEYPD page that inform email notifications.
