### ISSUE TITLE
Notifications: Unsubscribed email 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#645]
### Description 
Right now, when a user unsubscribes from notifications via email, the subject line on the unsubscribe email is entitled, "remove" when it sends an email to earlyyears@bccampus.ca. Change the subject line from "remove" to "Remove me from EYPD notifications"  
[Description of the bug or feature]

**Expected behaviour** 
User clicks on "unsubscribe" at the bottom of the email. An email program opens and the subject line is automatically populated with the subject, "Remove me from EYPD notifications

**Actual behaviour** 
User clicks on "unsubscribe" at the bottom of the email. An email program opens and the subject line is automatically populated with the subject, "remove".

**Comment by bdolor** [comment]
addressed in https://github.com/BCcampus/custom-wp-notify/pull/48
