### ISSUE TITLE
Learner Role: Access to create Groups

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#652]
Currently Learners have access to create Groups at earlyyearsbc.ca. Two Learner accounts were created on March 8 and March 12 and these new registered Learners created to groups and then populated a new topic with SPAM content. 

There is no direct link to groups; however, if a registered Learner changes the web address to  https://earlyyearsbc.ca/groups/ a new webpage appears on the early years site with a list of all the public, private and hidden groups and a button at the top to create a new group. 
![group](https://user-images.githubusercontent.com/16693738/54853815-27f68a80-4cae-11e9-956a-1db8b1cd704a.jpg)

Resolution:
Restrict Learners from creating new Groups.

**Comment by alex-418** [comment]
Was able to restrict group creation to Admins only via the Buddypress admin menu (see screenshots below) Note: Changed this setting on PROD only. 

![bp_option](https://user-images.githubusercontent.com/17072191/54936278-66bf5700-4edf-11e9-88bf-a081cb1d3562.png)
![bp_menu](https://user-images.githubusercontent.com/17072191/54936282-68891a80-4edf-11e9-96a8-39aed1df00d0.png)


If there's a need for anyone other than admins to be allowed to create groups, then we would have to look at adding a filter to create our own logic to allow group creation for group organizers for example. 

For future reference developers reference:
https://buddypress.trac.wordpress.org/attachment/ticket/1150/restrict-group-creation.php

**Comment by paulagaube** [comment]
Thanks, @alex-418 !!

**Comment by kathreenriel** [comment]
@alex-418 Thank you I tested this on Prod as a Learner and the "create groups" access is no longer available.
