### ISSUE TITLE
Sign up page: Add Vancouver Early Years Training Collaborative to the Sector drop-down list

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#653]
As administrator I would like to be able  to see which Organizers or Learners self-identify as being a part of a Vancouver Early Years Partnership consortium so that we can measure the uptake of this target audience consisting of the greatest population of early care and learning professionals in British Columbia. 
Currently when a Learner or Organizer signs up on EYPD they select a sector from the drop-down list. 
Modification Request:
  Add "Vancouver Early Years Partnership" to the list. 
<img width="286" alt="Screen Shot 2019-03-22 at 2 36 22 PM" src="https://user-images.githubusercontent.com/16693738/54854382-fed6f980-4caf-11e9-88cd-f5cf2efada8c.png">

**Comment by alex-418** [comment]
@paulagaube @kkilbey You guys should be able to tackle this one, no development work needed. 

Here's the link to add to this field (BuddyPress extended profile fields show up on the registration form) 
https://eypd.bccampus.ca/wp-admin/users.php?page=bp-profile-setup&mode=edit_field&group_id=1&field_id=1474

**Comment by kkilbey** [comment]
Thanks @alex-418! Added on Cert. How do we validate this one?

**Comment by alex-418** [comment]
@kkilbey To verify, you can Visit the sign-up page after adding it, and ensure it's been added.

**Comment by kkilbey** [comment]
@alex-418 Ah, of course! Was confusing with the new Sector search field. Thank you!

**Comment by kathreenriel** [comment]
I checked this on FF, Safari and Chrome. It works as expected.

**Comment by paulagaube** [comment]
Confirmed this is on Prod. Thanks, Kathreen!
