### ISSUE TITLE
Homepage: Footer

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#657]
The Project Champion has changed for the EYPD website and the footer needs to reflect the new Champion/funder. 

Change the graphic in the footer from The Provincial Office For The Early Years to Ministry of Children and Families. See attached graphic. 
![Ministry-of-Children-and-Family](https://user-images.githubusercontent.com/16693738/55990944-dfebd780-5c5d-11e9-9f52-b79c6ec48888.jpg)

**Comment by paulagaube** [comment]
@kathreenriel That image does not look right. Missing the family??
"Ministry of Children and Family Development"

**Comment by kathreenriel** [comment]
Thanks @paulagaube I uploaded the revised graphic

**Comment by alex-418** [comment]
@kathreenriel I've replaced the image (please clear your browsers cache), but as you can see the new image has white background. The old one was a .png with a transparent background... if you can please provide a png with a transparent background, i'd be glad to update it again.

**Comment by dshaykewich** [comment]
![BC_CFD_H_RGB_pos](https://user-images.githubusercontent.com/43043264/58136030-70b0be00-7be1-11e9-818a-cf3fc8b238ba.png)

**Comment by alex-418** [comment]
Completed on cert via https://github.com/BCcampus/eypd/commit/e49a30dc126e27f213b7f1e964268e69e83759b3

**Comment by dshaykewich** [comment]
@alex-418 , move to validating?

**Comment by paulagaube** [comment]
Cleared cache on PC and this looks good on Chrome, Firefox and Edge. Good on iPad using Safari.
