### ISSUE TITLE
Bounced email notifications

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/eypd#660]
**Is your feature request related to a problem? Please describe.**
As a new user, when I sign up on EYPD, I receive an auto-email with a link to activate my account. However, if I mistype my email address when signing up, the activation email will not be delivered. As part of EYPD pending-accounts process to sustain engagement, we would like to contact new users shortly after they have signed up on EYPD to remind them to activate their account. If the email is incorrect the email will not be delivered.  This also  means the new user never receives the link to activate their account which compromises our goal to sustain engagement with the EYPD website. 

**Describe the solution you'd like**
It would be great to receive a notification of bounced or undeliverable emails sent from EYPD, if possible. Then, we'd know right away if a new user has not received the activation email. We also wouldn't waste time re-sending the activation email to pending users.

**Comment by kathreenriel** [comment]
@kkilbey Thank you for documenting this issue. I have updated it to follow the template of the user story.

**Comment by alex-418** [comment]
We decided to add a "Confirm email" field to the sign up form to reduces the number of people signing up with a typo in their email.

**Comment by mandily-p** [comment]
How many people signed up with the wrong email? The current trend is to reduce friction on signup by just asking for email and password once. But I’ve never seen data on how often a user signs up with a spelling error. Does anyone have data or references to other studies on this?


________________________________

**Comment by kkilbey** [comment]
@mandily-p Since we started tracking and managing pending accounts about five weeks ago, five users have mistyped their email addresses that we know of (I just looked back through our records to confirm this number).

We've developed a procedure for dealing with these cases, but we won't always notice when someone makes a typo, so there's a chance that some of our follow-up emails are being sent off into the void! From a Support perspective, it would be great to resolve this typo issue up front, even though it adds an extra field to the sign-up page.

**Comment by paulagaube** [comment]
The procedure Kelsey mentioned is one Kathreen initiated for us to review users whose accounts are still "Pending", because they haven't confirmed their account through the activation link in the auto email they were sent. We review each of these Pending users and then send a series of emails to them to encourage them to complete the sign-up and log in to their account. 

This procedure is time-consuming and may take up two hours a week of our time to deal with accounts created by people who simply mis-typed their email address. My argument is that if having a user confirm their email address, which would take about 10 seconds, can save us an hour of time, then that is worth the small amount of friction it takes the user to verify their own email.

**Comment by mandily-p** [comment]
Whoa! That’s crazy pants! I never would have expected it to be that high. That’s good to know for this project and any future ones! Thanks guys!

**Comment by alex-418** [comment]
New email field can be tested at https://eypd.bccampus.ca/sign-up/

**Comment by kathreenriel** [comment]
This works as expected. @paulagaube would you check this too?

**Comment by paulagaube** [comment]
I tested the "Confirm Email (required)" field and it works as expected. When the two emails don't match, an error message appears.
This appears done, @kathreenriel

**Comment by kathreenriel** [comment]
Signed up for a new account and purposely put in unmatching emails. This works on prod
