### ISSUE TITLE
Update FAQ/messaging for Organizer sign-up error

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/eypd#661]
If someone tries to sign up as an Organizer but their email address does not correspond to our list of valid domains, they will receive an error message and be unable to complete their sign up.

This is the error message:
![image](https://user-images.githubusercontent.com/44710357/57161968-bc6e0580-6da1-11e9-877a-2a2cfdca57fa.png)

If they then go to the Help page, they will find an outdated FAQ (there is no longer a drop-down list of organizations):
![image](https://user-images.githubusercontent.com/44710357/57162153-3c946b00-6da2-11e9-83d2-7225701983b5.png)

We would like to update the FAQ and the error message to make this process easier for new Organizers. The error message does not clearly/accurately tell the user why their email address is not accepted, so the wording needs to be updated. Perhaps the message could also say "Visit our Help page for more info" so the user knows the next step they need to take to complete their sign up.

The FAQ related to this issue also needs to be updated. The "If you are a Learner...." section is no longer necessary. Mentions of the drop-down list need to be updated (replaced by "Place of Work" text-entry field). Changing the question itself to include the error message may also help the user find the information they need (e.g., "I tried signing up as an Organizer, but I saw X error message").

Adding the "question" tag so we can discuss:
- Wording of error message?
- Wording of FAQ?
- Is this definitely a non-dev task? (We can change the FAQ, but what about the error message?)

**Comment by alex-418** [comment]
@paulagaube and @kkilbey to provide new error message text

**Comment by paulagaube** [comment]
Here is my suggested error message text to display when the "Work Email Address (required)" for an Organizer does not match a domain name on the whitelist:

**Your email must be associated with an authorized organization.**

@dshaykewich what do you think? @kkilbey

**Comment by alex-418** [comment]
@paulagaube @kkilbey this is now done on cert and prod

**Comment by kkilbey** [comment]
Perfect! I like this wording; it's much clearer. Moving to Done in Cert!
![image](https://user-images.githubusercontent.com/44710357/63624647-f6158700-c5b1-11e9-9992-13f5afef0a27.png)
