### ISSUE TITLE
Update Help page

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/eypd#667]
Combining two tickets from the Support repository into this ticket.

Read through the EYPD [Help page](https://earlyyearsbc.ca/help/) to update FAQs. Add an FAQ for Organizers with steps for duplicating an event.

**Comment by paulagaube** [comment]
First step: I changed the FAQ "What if my organization is not listed on the drop-down list on the Sign Up page?" to Draft as it is no longer applicable.

**Comment by kkilbey** [comment]
I have reviewed and updated all of the FAQs on the Help pages for Cert and Prod. This task included:
- general edit for spelling/grammar, checking links
- creating parity between Cert and Prod
- checking that answers with step-by-step procedures are still accurate, updating where needed

@paulagaube ready for validating! :) I wouldn't mind talking more about the FAQ "I'm an event Organizer. How do I create an account?" as I think the answer needs one more sentence. Right now it basically says what to do if your domain is accepted, but doesn't say what to do if you are NOT accepted. This discussion also may have to wait until the domain validation issue is completed.

**Comment by paulagaube** [comment]
Great, @kkilbey . Let's call this done for now and review the FAQ you mention above later... Or add the sentence you think is missing. Alex will be moving the Prod database to Cert so it might be best to revise this later.
