### ISSUE TITLE
Test email notifications

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/eypd#668]
We would like to test the email notification system that Brad set up in a previous sprint.

@kathreenriel Paula and I are wondering about the best way to do this. Can we test before activating the email notifications? Or could we activate them, and then monitor what we receive (testing while feature is already live)?

**Comment by kkilbey** [comment]
Related to issue #648

**Comment by kathreenriel** [comment]
I think we should "bite the bullet" and activate. Brad did take the time to show me how the interface works and assured me that it would work as expected.

**Comment by paulagaube** [comment]
Clarified this with Kathreen: Test the email notifications on CERT first. 
We will need to add new upcoming events in various categories and then test different users with different professional interests before sending out emails to the test Cert users. When we are satisfied that Cert users are receiving appropriate emails, we will be ready to activate the plugin on Prod to begin sending regular emails.

**Comment by kkilbey** [comment]
I have created some new events in EYPD Cert, one new event for each professional interest category. Each event is called "Summer Fun - [category]" so they will be easily distinguishable.

I have also logged in to both my EYPD Cert accounts and set my professional interests. When we test the email notifications, I will see if the emails I receive align with the interests I selected.

@paulagaube @kathreenriel Would you both mind checking all your Cert accounts to make sure your professional interests are set/saved? Then we'll be ready to send out some test emails, I think! Thanks. :)

**Comment by paulagaube** [comment]
Hmmm.... we did not get expected results when I turned on notifications. 
The first email was supposed to be delayed by one hour, and it wasn't. It looks like not all emails were received. We need to test this more.

**Comment by paulagaube** [comment]
We realized that we need to understand the Custom WP Notify better so that we can accurately document and use the email features this plug in provides. Kathreen suggested created a new issue so this task can be added to an upcoming development sprint.

**Comment by dshaykewich** [comment]
Per #681 , I feel we should disable this.
