### ISSUE TITLE
myEYPD Page: Event Summary Donut 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#672]
As a Learner I wish to view those training events that relate to the topic/concept categories I am pursuing. I do not wish to view those system services that sponsored the training event illustrated in the event summary donut. 

Create a white list that indicates those topics/concepts that can be illustrated in the event wheel. These include all categories except those prefaced with the words, System Service: ***

**Comment by kathreenriel** [comment]
@alex-418 did I describe this functionality correctly? May we bring this into the Sprint Backlog?

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/eypd/commit/e7f2bc5188380b104a7545491dd4e112441af0fc 
Because we have a predictable prefix, I opted to exclude these categories from the donut data by checking for the `System Service:` prefix. This eliminates the need for a whitelist.

**Comment by paulagaube** [comment]
This looks good to me!

**Comment by kathreenriel** [comment]
checked this under Olivia and Larry's myEYPD profile. Works on Prod.
