### ISSUE TITLE
Revise Category List

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#673]
As a visitor, Learner and Organizer I wish to view categories by topics / concepts and by service system. 

Add Service system to the category list in the dashboard.

**Comment by kathreenriel** [comment]
@paulagaube Would you take a look at this new list on cert. I also added two new categories as requested by the CCRR's Infant/Toddler and Cultural Safety.

**Comment by paulagaube** [comment]
On the EYPD.bccampus.ca home page, (as a visitor) on the drop-down list "Search by Category", I now see, beneath the category Special Needs: 
System Service: CCRR
System Service: Government
System Service: Post-Secondary
System Service: School District
System Service: Vancouver Early Years Partnership

I see these options using Chrome on my PC and on my iPhone. 

Logged in as a Learner, I see these options on the myEYPD page under Professional Interests and I am able to click the checkboxes to choose those interests.

Logged in as an Organizer,  I see these options on the myEYPD page under Professional Interests and I am able to click the checkboxes to choose those interests.

Looks good to me!

**Comment by kathreenriel** [comment]
I completed the content change on Production. I changed the description of Service System: Vancouver Early Years Partnership to Service Partnership: Vancouver Early Years Partnership. This change has been completed on CERT and PROD
