### ISSUE TITLE
Donut order

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#675]
As a Learner I wish to view the order of events as represented in the donut (with greatest % of events starting to show at "12:00" and tracking clockwise) in the same consecutive order as illustrated in the legend from largest % to smallest %. Where the  same % is represented by the two or more categories - alphabetical order will take precedence. This synchronous view is necessary so that the Learner may clearly identify those areas of predominant learning and those areas of learning that may require further exploration.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/eypd/commit/6fba0b3e5eb166fe1ae4f0cbff91b0433fa0e3e0

**Comment by paulagaube** [comment]
This looks good to me! Tested on a learner account and an organizer account.

**Comment by kathreenriel** [comment]
Events are illustrated according to % and colour on donut! Yeh!

**Comment by kathreenriel** [comment]
Order is working on Prod.
