### ISSUE TITLE
Synchronize Prod/Cert for parity 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#677]
Production and Development environments differ greatly. Synchronizing Server configurations, application settings, plugin settings is important to ensure we are getting the same results when validating and delivering new features. 

Do this manually and document the process, to ensure smooth handoff.

**Comment by kathreenriel** [comment]
@alex-418 @dshaykewich  is this a task that could be addressed during admin time on Mondays or does this require several hours/days?

**Comment by dshaykewich** [comment]
Let's invest some time in this, @alex-418 .

**Comment by alex-418** [comment]
Plan is to export the production database and files, and bring them over to cert. As part of this, I will also delete the dev branch of both EYPD and Validate by domain, and re-recreate them from master to synchronize the code base and commit history as it's currently out of whack.

**Comment by alex-418** [comment]
Production database and files exported successfully. We can proceed with this.

**Comment by alex-418** [comment]
Holding off until we get the green light from @paulagaube to export production database.

**Comment by paulagaube** [comment]
@alex-418 I talked with Kelsey and we want to give you the green light to go! Thank you!

**Comment by alex-418** [comment]
@dshaykewich Had to change strategy on this as download/upload speeds when connected to the VPN are incredibly slow. I've created a private repository at https://github.com/BCcampus/eypd_prod/tree/master and will be pushing our production files here, and then pulling them into cert. This should simplify the process going forward. I've added a .gitignore file to ensure none of our configuration makes it in there (wp-config for example, holds our database password etc).

**Comment by alex-418** [comment]
Cert and Prod now synchronized. 

Documenting steps taken for future reference:

1. Export Production database
2. Drop tables on cert database
3. Import Production database tables into cert database
4. Overwrite Early Years directory in `/var/www/html/eypd` with the contents of `/var/www/html/earlyyears` 
5. Update `wp-config.php` on cert with certification DB credentials
6. Update `Site URL` via `functions.php` file in EYPD theme
7. Clear workspace on Jenkins for cert, initiate a build 
8. Test cert URL to make sure it's not re-directing to prod (confirms Site URL was updated in DB)
9. Update permalink settings to re-link all content with new URL
10. Remove code in step 6 from `functions.php` file in EYPD theme

**Comment by alex-418** [comment]
@paulagaube @kkilbey @dshaykewich cert is now synced, feel free to kick the tires and see if you can break something :) 👍

**Comment by dshaykewich** [comment]
Sweet!  Nice job, @alex-418 .

**Comment by kkilbey** [comment]
@alex-418 I've been cruising through Cert, and so far haven't broken anything! Looks good :)

**Comment by alex-418** [comment]
@kkilbey thanks for doing that, glad to hear!
