### ISSUE TITLE
EYPD Infograph Review

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#678]
Review the EYPD infograph for the final report for distribution to the EYPD advisory group, sponsor and champion.

**Comment by kkilbey** [comment]
Reviewed! @paulagaube your turn :)

**Comment by kathreenriel** [comment]
@kkilbey would you email me your edits

**Comment by paulagaube** [comment]
@kathreenriel @kkilbey and I are just back from lunch and then called to something else. We'll send you combined comments shortly. It looks like there are only a couple small things to tweak.

**Comment by paulagaube** [comment]
@kathreenriel notes sent by email to you.

**Comment by paulagaube** [comment]
@kathreenriel will you move this to completed when done?

**Comment by dshaykewich** [comment]
Looks like this is done.
