### ISSUE TITLE
Remove custom WP notify plugin

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#684]
Ensure there's no other functionality disabled when removing this plugin. Deprecate repository, remove from dependencies.

**Comment by alex-418** [comment]
Documenting code to be removed from template to avoid fatal errors after https://github.com/BCcampus/custom-wp-notify has been removed. 

https://github.com/BCcampus/eypd/blob/b866099a8c465d865757b84a4d3066a17785d974/plugins/events-manager/buddypress/profile.php#L23

https://github.com/BCcampus/eypd/blob/81c77cc4e54e6e21a0c1242794cc1ef5602e81d6/functions.php#L878

**Comment by alex-418** [comment]
Also remove email notification checkbox on signup page:
![notifications](https://user-images.githubusercontent.com/17072191/62985497-6a9b3980-bdec-11e9-848c-3c3822c8025d.png)

**Comment by alex-418** [comment]
@paulagaube @kkilbey this is now on cert, ready for validation. The plugin is disabled, as is any functionality or wording associated with this in myEYPD and the registration page. Please let me know if you encounter any issues with these. Thanks @dshaykewich for pushing this to cert.

**Comment by paulagaube** [comment]
I have verified that the email notification checkbox is no longer showing up on the Sign up page as expected.

**Comment by paulagaube** [comment]
Also have confirmed that the plugin at this location is now gone: 
eypd.bccampus.ca > Dashboard > Settings > Custom WP Notify

This looks good, @alex-418 ! 

The Sign Up page seems less cluttered too, even though this is only one field.

**Comment by alex-418** [comment]
Awesome, thanks @paulagaube

**Comment by alex-418** [comment]
@dshaykewich @paulagaube @kkilbey FYI - this is now done in prod as well.
