### ISSUE TITLE
Resolve build errors on Travis CI

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#686]
All builds are failing on our continuous integration tool. I suspect this is isolated to our configuration in Travis CI, and that the builds on Jenkins would succeed. 

Here's the log, the error is specific to WP-CLI not being able to run unit tests.
 
https://travis-ci.com/BCcampus/validate-by-domain/jobs/225265814

**Comment by alex-418** [comment]
@dshaykewich Will require your help to troubleshoot this as my VPN is still not working. When you have time please get in touch. I just need to run a manual build on cert to see if succeeds and see the output of the log. All this will do is bring in the following commit: https://github.com/BCcampus/eypd/commit/5faafc6002ddb52d0439a97f2245a52f8f43ab54 which will then allow me to complete #684 on cert for testing.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/eypd/commit/fc7e9beb0af3d8253d2d23e58691e6de685ec3df and build are now successful see https://travis-ci.com/BCcampus/eypd/builds/123270294

@dshaykewich documenting our discussion on the reason for this change: We currently don't have any code coverage or unit tests in this code base, so this build step was unnecessary. We plan to ensure this happens going forward on new projects. Please note: Other repositories that suffer the same build error may also require this change.

**Comment by paulagaube** [comment]
@alex-418 I'm not sure who can validate this, because I don't know how to validate this.
