### ISSUE TITLE
Create logos for the cert site that clearly indicate that it's the testing instance

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/eypd#693]
**Is your feature request related to a problem? Please describe.**
Create logos for the cert site that clearly indicate that it's the testing instance

**Comment by dshaykewich** [comment]
@alex-418 , could you please set my account up as an WP admin on eypd.bccampus.ca?

**Comment by alex-418** [comment]
@dshaykewich Documenting our discussion on this during the stand up meeting: This will now be a dev task where we'll display the tagline on cert but not prod. What should the tagline say? Should I make text ted and just put "TEST Site" and call it a win? I've also given you admin on cert as well in case you changed your mind about this.

**Comment by alex-418** [comment]
@dshaykewich This is where I landed with this, let me know if this works for you:

![test](https://user-images.githubusercontent.com/17072191/63628654-80fe7d80-c5c2-11e9-9def-cd0ebd8d4dcc.png)

**Comment by dshaykewich** [comment]
Perfect!
