### ISSUE TITLE
Organizers are not automatically assigned the role of "Editor" on sign-up

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#697]
**Describe the bug**
When a new Organizer signs up for an Early Years account, and their email includes a valid domain from an authorized organization, they are not automatically assigned the role of "Editor". Their role remains "Subscriber" and they cannot post events without manual intervention from a site administrator. 

**To Reproduce**
1. Go to https://earlyyearsbc.ca/sign-up/
2. Fill in personal details and Click "Complete Sign Up"
3. Check email and click the account activation link
4. Login: https://earlyyearsbc.ca/wp-login.php?redirect_to=https%3A%2F%2Fearlyyearsbc.ca%2Fsign-up%2F
5. Go to Post an Event: https://earlyyearsbc.ca/post-event/

**Expected behavior**
After a new Organizer signs up and activates their account, their role is set to "Editor" and they can go to the Post an Event page and immediately begin adding events.

**Screenshots**
Currently, Organizers who sign up are assigned the role of "Subscriber" and cannot post events on the Post an Event page:
<img width="544" alt="Organizer-as-Subscriber" src="https://user-images.githubusercontent.com/26391359/64442593-eeabae80-d084-11e9-9592-8ee9ef0a078f.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome and Firefox
 - Version: latest version

**Comment by paulagaube** [comment]
Today two people signed up as Organizers on Earlyyearsbc.ca and were successfully assigned the role of Editor. 
This issue appears to be resolved. 
Did you do something magical, @alex-418 ?

**Comment by alex-418** [comment]
![giphy](https://user-images.githubusercontent.com/17072191/65361896-30c30d00-dbba-11e9-9242-3a9109983852.gif)
