### ISSUE TITLE
Google Maps error message on EarlyYearsbc.ca and EYPD.bccampus.ca

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#703]
**Describe the bug**
On earlyyearsbc.ca and eypd.bccampus.ca websites, in the "Find training events near you" section, Google Maps shows an error message: "This page can't load Google Maps correctly." A watermark appears on the map "For development purposes only"

**To Reproduce**
1. Go to earlyyearsbc.ca or eypd.bccampus.ca
2. Scroll down to "Find training events near you"
4. The map is slow to load, then an error message appears (see image below)

**Expected behavior**
The map loads and shows where locations of EYPD events are throughout British Columbia.

**Screenshots**
<img width="693" alt="EarlyYearsBC-GoogleMaps" src="https://user-images.githubusercontent.com/26391359/70670676-97424f00-1c2e-11ea-95f6-bf32b503051e.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Firefox
 - Version latest version

**Additional context**
Link on the error pop-up message says this is related to **API Key and Billing Errors**
https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors

**Comment by dshaykewich** [comment]
The free Google account had expired.  I upgraded the account.  This appears fixed to me now.  Could you please confirm and close this ticket (if so), @paulagaube ?

**Comment by paulagaube** [comment]
Thanks, @dshaykewich. Googlemaps are now displaying without the error message. 
Closing this ticket. :)
